"""每项算法「大模型赋能分析」四段正文。不重算、不改代码、不写处方。"""

from __future__ import annotations

SECTION_ORDER = (
    ("improveRun", "提高本次运行"),
    ("toApplication", "接到应用"),
    ("bounds", "方法限制"),
    ("guard", "拦住说错"),
)

_DOWNSTREAM = "这是下游用法，不是本页已交付的业务产品。"

SECTIONS: dict[str, dict[str, str]] = {
    "01_flight_planning": {
        "improveRun": "对照航高、像元尺寸、焦距、旁向重叠和航点间距，核本次外包矩形航线是否自洽，并讲清航程估算来自航点间距而非实测轨迹。",
        "toApplication": f"后续可用于飞控导入前的覆盖检查。{_DOWNSTREAM}本页只输出航线几何，不是可飞性批复。",
        "bounds": "当前只在测区外包矩形上铺直线往返航点，不处理 DEM、障碍、禁飞区或飞控格式。",
        "guard": "拦住把理论 GSD 或简化航时写成已经完成的飞行验收。",
    },
    "02_sync_timestamp": {
        "improveRun": "对照 n_hsi、n_rgb、n_pos、n_aligned 和 clock_offset_rgb_s，核匹配覆盖与钟差单位，讲清最近邻配对留下的时间残差。",
        "toApplication": f"后续可把对齐表交给定位插值或 RGB 辅助配准。{_DOWNSTREAM}本页只输出时间匹配记录。",
        "bounds": "固定中位钟差、无容差拒绝、无漂移模型，不代表 PPS/PTP 硬件同步。",
        "guard": "拦住把最近邻匹配写成严格同时曝光。",
    },
    "03_pos_solution": {
        "improveRun": "对照粗差点数、alpha、杠杆臂和输出轨迹点数，核本次平滑是否读的是已解算 POS CSV，而不是原始 IMU。",
        "toApplication": f"后续可用于粗定位或正射的位置姿态输入。{_DOWNSTREAM}本页只输出平滑后的 POS，不是紧组合导航解。",
        "bounds": "不读取 IMU 比力/角速度，固定 q/r 的一维 RTS 不是完整 EKF。",
        "guard": "拦住把本服务写成 GPS+IMU 紧组合或精度证书。",
    },
    "04_flight_qc": {
        "improveRun": "对照过曝/欠曝比例、是否通过和场景均值/标准差比，核本次门控只看饱和比例，不要把全图统计当成实验室 SNR。",
        "toApplication": f"后续只决定这包数据能不能进入辐射校正。{_DOWNSTREAM}本页不是飞行合格证，也不检测丢帧。",
        "bounds": "通过/复飞仅由过曝比例触发；全图 mean/std 不是 EMVA 传感器 SNR。",
        "guard": "拦住根据预览图或场景统计签发飞行验收结论。",
    },
    "05_cloud_shadow": {
        "improveRun": "对照云/暗区像元数和规则阈值，核本次是可见光亮、NDVI 低且低白度指标的简化光谱规则，阴影是候选暗区。",
        "toApplication": f"后续可作掩膜候选，挡住脏包进入指数。{_DOWNSTREAM}本页不是完整 Fmask，也不是已确认云高投影。",
        "bounds": "无热红外、云高和太阳几何；阈值是工程默认。",
        "guard": "拦住把候选暗区写成已确认云影，或把简化规则写成完整 Fmask。",
    },
    "06_dark_current": {
        "improveRun": "对照 method 是 dark_frame 还是 per_band_min，核有无匹配暗场；讲清列向 FPN 扣除后截零的含义。",
        "toApplication": f"后续把扣除暗电流的 DN 交给辐射定标。{_DOWNSTREAM}本页不是温度漂移模型或实验室暗电流证书。",
        "bounds": "无暗帧时用波段最小值替代，不是 EMVA 测量流程。",
        "guard": "拦住把 per_band_min 结果写成已经完成的实验室暗电流校正。",
    },
    "07_bad_pixel": {
        "improveRun": "对照检出掩膜和 method 名称，核填充是 3×3 邻域均值，不是双线性；讲清 6σ/4σ 只是工程默认。",
        "toApplication": f"后续把修复后的立方体交给条带或定标。{_DOWNSTREAM}本页不是沿轨插值产品。",
        "bounds": "MAD/列统计门限无直接标准规定；邻域均值会模糊点目标。",
        "guard": "拦住把邻域均值写成双线性或标准规定的缺陷像元流程。",
    },
    "08_destriping": {
        "improveRun": "对照矩匹配前后的列统计，核本次是按列均值/方差对齐到全图矩，讲清纹理可能被改变。",
        "toApplication": f"后续用于视觉匀化后的定标或镶嵌。{_DOWNSTREAM}本页不是辐射真值恢复。",
        "bounds": "统计相似假设不成立时会改掉真实条带状地物。",
        "guard": "拦住把看起来更匀写成辐射已经正确。",
    },
    "09_smile_keystone": {
        "improveRun": "对照估计偏移幅度，核本次是场景互相关而不是实验室 LUT；讲清三次样条/双线性重采样会损细节。",
        "toApplication": f"后续把几何校正后的立方体交给定标或指数。{_DOWNSTREAM}本页不是实验室光谱几何标定证书。",
        "bounds": "弱纹理和相关峰歧义会使偏移不稳定。",
        "guard": "拦住把场景估计偏移写成标定偏移。",
    },
    "10_radiance_calibration": {
        "improveRun": "对照本次 gain/offset 是否来自输入系数，核线性 L=gain×DN+offset；默认 0.01/0 只是演示缺省量级。",
        "toApplication": f"后续把辐亮度交给反射率定标或大气校正。{_DOWNSTREAM}本页不是实验室定标证书。",
        "bounds": "没有匹配的积分时间和暗场时，数字不可比。",
        "guard": "拦住在默认系数下声称已完成实验室线性辐射定标。",
    },
    "11_relative_radiometric": {
        "improveRun": "对照参考影像与左上角共同尺寸，核直方图匹配只作用于重叠最小矩形，其余保持原值。",
        "toApplication": f"后续用于多景相对可比的镶嵌准备。{_DOWNSTREAM}本页不是绝对反射率产品。",
        "bounds": "无几何配准；地物组成不同会引入偏差。",
        "guard": "拦住把直方图匹配写成物理辐射定标。",
    },
    "12_panel_reflectance": {
        "improveRun": "对照白板区域与暗端假设，核本次经验线性法用的是单板加暗端，不是完整多板 ELM。",
        "toApplication": f"后续把反射率立方体交给指数或分类。{_DOWNSTREAM}本页不是场地 BRDF 订正后的绝对反射率。",
        "bounds": "最亮百分位和截断是工程默认。",
        "guard": "拦住把单板结果写成标准反射率产品。",
    },
    "13_atmospheric_correction": {
        "improveRun": "对照 DOS/COST 假设与太阳天顶角，核本次是简化路径辐射扣除，不是完整辐射传输。",
        "toApplication": f"后续用于地表反射率近似后再算指数。{_DOWNSTREAM}本页不是 6S/MODTRAN 产品。",
        "bounds": "ESUN 插值和百分位是仓库简化。",
        "guard": "拦住把简化 DOS 写成已经完成的大气真实订正。",
    },
    "14_brdf_correction": {
        "improveRun": "对照核驱动权重和视角列，核本次是固定权重的简化 NBAR 近似，不是完整核反演。",
        "toApplication": f"后续用于减弱观测几何差异后再做镶嵌或指数。{_DOWNSTREAM}本页不是 MODIS NBAR 产品。",
        "bounds": "固定权重和逐列线性视角是实现默认。",
        "guard": "拦住把核改正写成各向异性已经消除。",
    },
    "15_geo_locate": {
        "improveRun": "对照 POS 中心、GSD 和仿射，核本次不使用姿态，只是北向上粗网格。",
        "toApplication": f"后续可作粗略叠图参考。{_DOWNSTREAM}本页不是精密直接地理定位。",
        "bounds": "单点中心加 GSD 仿射，无 DEM、无姿态投影。",
        "guard": "拦住把粗定位写成已完成的正射或厘米级 POS 投影。",
    },
    "16_orthorectify": {
        "improveRun": "对照 DEM 与输出网格，核本次正射缺少真实地图格网和控制点时只能当示意。",
        "toApplication": f"后续可作几何纠正后的镶嵌输入。{_DOWNSTREAM}本页不是带控制点的生产正射。",
        "bounds": "未使用 DEM CRS/transform 与控制点时几何不可当测图。",
        "guard": "拦住把正射写成测图级产品。",
    },
    "17_mosaic": {
        "improveRun": "对照两景 CRS 是否一致、羽化距离和输出范围，核不同 CRS 会被拒绝，而不是继续乱拼。",
        "toApplication": f"后续把镶嵌图交给匀色、指数或分类。{_DOWNSTREAM}本页不是同名点匹配或接缝线优化。",
        "bounds": "依赖预先配准；距离羽化不是接缝缓冲余弦权重。",
        "guard": "拦住把距离羽化写成已经完成的接缝线搜索。",
    },
    "18_color_balance": {
        "improveRun": "对照 Wallis 窗口的局部均值/方差，核本次只做局部匀色，没有接缝线。",
        "toApplication": f"后续用于镶嵌预览或视觉一致性。{_DOWNSTREAM}本页不是辐射真值或接缝线产品。",
        "bounds": "局部统计会改变纹理；不搜索接缝。",
        "guard": "拦住把匀色写成辐射校正或接缝线优化。",
    },
    "19_multi_source_register": {
        "improveRun": "对照估计的平移量和重采样，核本次是 HSI–RGB 全局平移，不是旋转、尺度或矢量配准。",
        "toApplication": f"后续用于多源叠图显示。{_DOWNSTREAM}本页不是矢量边界配准。",
        "bounds": "均波段灰度与三次重采样是仓库选择。",
        "guard": "拦住把全局平移写成仿射/单应或矢量配准已经完成。",
    },
    "20_bad_band_remove": {
        "improveRun": "对照剔除波段列表和场景均值/标准差比，核该比值不是传感器 SNR，实际只删除波段。",
        "toApplication": f"后续把保留波段交给平滑、降维或指数。{_DOWNSTREAM}本页不是光谱维去噪。",
        "bounds": "固定吸收窗口和 0.4 倍中位阈值是工程默认。",
        "guard": "拦住把场景比值写成实验室 SNR 或去噪产品。",
    },
    "21_savgol_smooth": {
        "improveRun": "对照窗口和多项式次数，核偶窗口被加一的仓库规则，讲清平滑会削峰。",
        "toApplication": f"后续把平滑光谱交给归一化、降维或反演。{_DOWNSTREAM}本页不是特征增强产品。",
        "bounds": "窗口过大或次数不当会失真吸收峰。",
        "guard": "拦住把平滑后的曲线写成更高信噪比的真光谱。",
    },
    "22_normalize": {
        "improveRun": "对照 preprocess 模式（SNV/zscore/minmax/L2），核本次统计口径是逐光谱还是全图。",
        "toApplication": f"后续把归一化光谱交给分类或回归。{_DOWNSTREAM}本页不改变物理单位含义之外的业务结论。",
        "bounds": "全图统计会把空间结构编进尺度。",
        "guard": "拦住把归一化后的数值写成已经定标的物理量。",
    },
    "23_pca": {
        "improveRun": "对照主成分数量和噪声估计方式，核 MNF 依赖的是空间差分噪声近似。",
        "toApplication": f"后续把主成分当作分类或检测的特征。{_DOWNSTREAM}本页不是物质识别结果。",
        "bounds": "空间差分噪声和正则化是实现选择。",
        "guard": "拦住把前几主成分写成已经对应的地物类别。",
    },
    "24_band_select": {
        "improveRun": "对照 ANOVA F 与 top-k，核有效标签门槛和方差回退是否触发。",
        "toApplication": f"后续用选出的波段训练分类或回归。{_DOWNSTREAM}本页不是已经训练好的模型。",
        "bounds": "无标签时的方差回退不代表信息波段。",
        "guard": "拦住把 top-k 写成最优物理波段集合。",
    },
    "25_superpixel": {
        "improveRun": "对照 convert2lab=False 和前三原始光谱波段，核各通道尺度可能主导距离，不是 CIELAB SLIC。",
        "toApplication": f"后续把超像素当作对象统计或样本单元。{_DOWNSTREAM}本页不是地物分类图。",
        "bounds": "输入空间偏离标准 SLIC 的 Lab+xy。",
        "guard": "拦住把前三光谱通道写成 RGB 颜色分割。",
    },
    "26_patch_build": {
        "improveRun": "对照 patch 尺寸、重叠和 NPZ 条目数，核这是中心邻域枚举，不是训练/验证划分。",
        "toApplication": f"后续可把 patch 作为网络训练输入。{_DOWNSTREAM}本页不是已训练模型或精度报告。",
        "bounds": "edge 填充、全量 label>0 枚举、未分区。",
        "guard": "拦住把导出的 NPZ 写成已经完成的深度学习训练。",
    },
    "27_ndvi": {
        "improveRun": "对照 data.red_band、data.nir_band、值域和全图统计，核红光/近红外是否按传感器光谱响应选择，并讲清每个返回字段。",
        "toApplication": f"后续可用于同一传感器与处理链下的绿度相对分区，或作为地块汇总的输入图层。{_DOWNSTREAM}本页只输出 NDVI GeoTIFF。",
        "bounds": "应优先用定标反射率；高叶面积时容易饱和，对生物量增量的敏感性下降。",
        "guard": "拦住把 NDVI 直接写成叶绿素含量或生物量定量产品；不能直接作为叶绿素含量或生物量定量产品。",
    },
    "28_ndre": {
        "improveRun": "对照 re_band、nir_band 是否落在真实红边和近红外平台，并说明全图统计只是相对格局。",
        "toApplication": f"后续可用于红边敏感的相对长势对照。{_DOWNSTREAM}本页不是叶绿素毫克数产品。",
        "bounds": "没有真实红边通道时本公式没有物理意义。",
        "guard": "拦住把 NDRE 写成叶绿素毫克数。",
    },
    "29_evi_savi": {
        "improveRun": "分别打开 evi.tif、savi.tif、msavi.tif，核 L 参数，避免把一个均值当成三个指数都已校正。",
        "toApplication": f"后续可用于土壤背景更强时的相对绿度对照。{_DOWNSTREAM}本页不是 LAI 或产量。",
        "bounds": "L 会改变 SAVI；三公式量纲与饱和行为不同。",
        "guard": "拦住把三个指数写成 LAI、氮或产量。",
    },
    "30_ndmi_ndwi": {
        "improveRun": "分别打开 ndmi.tif、ndwi.tif、mndwi.tif，以及本次有没有真实 SWIR。",
        "toApplication": f"后续可用于水分相关的相对分区。{_DOWNSTREAM}本页不是绝对含水量。",
        "bounds": "无 SWIR 时 NDMI/MNDWI 没有物理意义；同名 NDWI 不能混比。",
        "guard": "拦住给出绝对含水量，或把一层公式套到另一层。",
    },
    "31_red_edge_params": {
        "improveRun": "核对 Guyot 四点是否落在真实波长轴上，窗口按实现为 680–760 nm。",
        "toApplication": f"后续可用于红边位置的相对对照。{_DOWNSTREAM}本页不是叶绿素定量。",
        "bounds": "假等间隔波长或宽带采样会使位置不可信。",
        "guard": "拦住把 REP 纳米数写成叶绿素毫克数。",
    },
    "32_regression_inversion": {
        "improveRun": "对照 preprocess 实际是 snv 还是 none，以及训练/测试误差只对当前划分有效。",
        "toApplication": f"后续可把反演图层当作经验估计输入。{_DOWNSTREAM}本页不是化验值。",
        "bounds": "像元随机划分会泄漏；成分数过多会过拟合。",
        "guard": "拦住把一次测试 R² 写成业务验收。",
    },
    "33_physical_inversion": {
        "improveRun": "说明输出是 LUT 最优若干条的平均，不是全参数连续优化解；对照边界命中和固定参数。",
        "toApplication": f"后续可作 LAI/Cab 候选图层。{_DOWNSTREAM}本页不是实验室化验。",
        "bounds": "固定其余参数会把误差挤进 LAI/Cab；边界命中不是可靠极值。",
        "guard": "拦住把 LUT 命中值写成实验室化验。",
    },
    "34_svm_rf_classify": {
        "improveRun": "分开解释 OA、AA、Kappa；核 SVM 是否用训练集拟合的标准化器，RF 不强制标准化。",
        "toApplication": f"后续可作分类图制图输入。{_DOWNSTREAM}本页不是业务过关精度。",
        "bounds": "背景像元会被强制分类；像元随机划分使指标虚高。",
        "guard": "拦住把一次测试 OA 写成业务过关。",
    },
    "35_spectral_matching": {
        "improveRun": "把 pred_map_tif 与 angle_tif 分开读，核无拒绝阈值时每个像元都会被硬分类。",
        "toApplication": f"后续可作类别示意图层。{_DOWNSTREAM}本页不是概率图。",
        "bounds": "SID 与 SAM 分数不可互换。",
        "guard": "拦住把最小角写成概率或精度百分比。",
    },
    "36_cnn1d_classify": {
        "improveRun": "说明短训指标只说明本次划分；当前无空间邻域，碎斑是实现边界。",
        "toApplication": f"后续可作光谱分类示意。{_DOWNSTREAM}本页不是已达业务精度的网络。",
        "bounds": "RNN 未实现。",
        "guard": "拦住宣称本网络已达业务精度。",
    },
    "37_cnn3d_classify": {
        "improveRun": "对照 patch 尺寸与测试指标，提示重叠 patch 泄漏和演示短训。",
        "toApplication": f"后续可作空谱分类示意。{_DOWNSTREAM}本页不是论文复现精度。",
        "bounds": "演示短训不是 HybridSN 全文复现。",
        "guard": "拦住把演示 OA 写成论文级精度。",
    },
    "38_transformer_classify": {
        "improveRun": "把短训指标限制在本次划分协议内；核缩小网络已缩小。",
        "toApplication": f"后续可作 Transformer 分类示意。{_DOWNSTREAM}本页不是通用视觉大模型。",
        "bounds": "GCN 未实现。",
        "guard": "拦住把本实现写成通用视觉大模型。",
    },
    "39_few_shot_classify": {
        "improveRun": "说明支持数、query 缺失时指标不能读；这是均值原型匹配。",
        "toApplication": f"后续可作少样本示意分类。{_DOWNSTREAM}本页不是已解决小样本的迁移学习。",
        "bounds": "未知光谱仍会被硬分；无可学习嵌入。",
        "guard": "拦住把少量 shots 写成已经解决小样本。",
    },
    "40_detect_segment": {
        "improveRun": "把 ACE 分数、百分位与斑块像元数分开读；核低 NDVI 种子只是仓库启发式。",
        "toApplication": f"后续可把候选斑块交给人工复核。{_DOWNSTREAM}本页不是语义分割或已确认目标。",
        "bounds": "当前是 ACE 检测而不是深度学习分割。",
        "guard": "拦住把斑块写成已确认目标类别。",
    },
    "41_unmixing": {
        "improveRun": "把丰度、和约束与残差一起读，核线性混合在通道少时欠定。",
        "toApplication": f"后续可作组分相对丰度示意。{_DOWNSTREAM}本页不是质量分数或产量份额。",
        "bounds": "丰度不一定等于面积比例。",
        "guard": "拦住把丰度写成质量分数或产量份额。",
    },
    "42_anomaly_detect": {
        "improveRun": "把连续得分与相对阈值掩膜分开读，核高分只相对本景背景。",
        "toApplication": f"后续可作离群候选清单。{_DOWNSTREAM}本页不是已命名地物。",
        "bounds": "高分只是相对背景离群。",
        "guard": "拦住把 RX 高分写成特定地物名称。",
    },
    "43_change_detect": {
        "improveRun": "把 χ² 强度与相对百分位掩膜分开读，核错位会造假变化。",
        "toApplication": f"后续可作变化候选图。{_DOWNSTREAM}本页不是灾损等级或因果定性。",
        "bounds": "输出是统计变化不是原因。",
        "guard": "拦住把变化图写成灾损等级或因果定性。",
    },
    "44_postprocess_smooth": {
        "improveRun": "对照窗口、小斑阈值、变更像元数与类别列表，核众数/筛斑强度。",
        "toApplication": f"后续可作分类图整饰后的制图输入。{_DOWNSTREAM}本页不是更准确的分类。",
        "bounds": "会吞并小目标和边界；视觉整齐不等于更准确。",
        "guard": "拦住根据预览颜色编造类别或业务决策。",
    },
    "45_parcel_zonal_stats": {
        "improveRun": "区分连续统计与分类计数占比，核 NoData/NaN/空有效区如何改变分母。",
        "toApplication": f"后续可作报表或专题图的汇总表。{_DOWNSTREAM}本页不是原因或决策。",
        "bounds": "模式错配会把连续值整数化；空区不生成虚假 0。",
        "guard": "拦住把汇总统计写成原因、处方或业务决策。",
    },
    "46_reci": {
        "improveRun": "对照 data.re_band 与 data.nir_band 是否落在真实红边和近红外平台，并核 reci.tif 不是 −1～1 指数。",
        "toApplication": f"后续可用于密冠层叶绿素相关的相对分区。{_DOWNSTREAM}本页只输出 reci.tif。",
        "bounds": "没有真实红边通道时本公式没有物理意义；不能换算叶绿素毫克数。",
        "guard": "拦住把 RECI 写成叶绿素毫克数。",
    },
    "47_gndvi": {
        "improveRun": "对照 data.green_band、data.nir_band 是否按传感器绿光窗口选择，而不是死记演示数据默认。",
        "toApplication": f"后续可用于绿光通道的相对绿度对照。{_DOWNSTREAM}本页只输出 gndvi.tif。",
        "bounds": "高覆盖时仍可能饱和，不能直接当作叶绿素含量。",
        "guard": "拦住把 GNDVI 写成叶绿素毫克数。",
    },
    "48_osavi": {
        "improveRun": "对照 data.L 是否仍为 0.16，以及红光近红外是否为反射率。",
        "toApplication": f"后续可用于土壤背景更强时的相对绿度对照。{_DOWNSTREAM}本页只输出 osavi.tif。",
        "bounds": "L 改了就不能和未改的图横比；0.16 不是现场标定。",
        "guard": "拦住把 OSAVI 写成叶面积或产量。",
    },
    "49_arvi": {
        "improveRun": "对照 data.gamma 与蓝光索引，说明 RB = RED − γ(BLUE − RED) 用的是哪次参数。",
        "toApplication": f"后续可用于气溶胶残差更明显时的相对绿度对照。{_DOWNSTREAM}本页不是大气校正产品。",
        "bounds": "蓝光差或阴影重时 ARVI 会乱；不能替代大气校正。",
        "guard": "拦住把 ARVI 写成已经完成大气校正。",
    },
    "50_vari": {
        "improveRun": "对照蓝、绿、红三个可见光索引，并检查分母 GREEN+RED−BLUE 是否接近零。",
        "toApplication": f"后续可用于只有可见光相机时的相对覆盖示意。{_DOWNSTREAM}本页不是覆盖度百分数。",
        "bounds": "没有近红外不等于能替代 NDVI；土壤颜色会干扰。",
        "guard": "拦住把 VARI 写成植被覆盖百分比。",
    },
    "51_lai_index": {
        "improveRun": "打开 lai_index.tif，核这是 EVI 线性变换，文件名不要和 #33 的 lai.tif 混。",
        "toApplication": f"后续只能作经验叶面积示意。{_DOWNSTREAM}本页不是实验室叶面积，也不是 #33。",
        "bounds": "系数 3.618/−0.118 未经本景标定；负值被裁成 0。",
        "guard": "拦住把经验 LAI 写成实验室叶面积或 #33 PROSAIL。",
    },
    "52_nbr": {
        "improveRun": "对照 data.swir_band 是不是真实短波红外，并写清演示数据窗口约 1600 nm。",
        "toApplication": f"后续可用于过火前后的相对差异对照。{_DOWNSTREAM}本页不是过火面积。",
        "bounds": "与 NDMI 同型时数值接近；Landsat NBR 常用 SWIR2，不能混比。",
        "guard": "拦住把 NBR 写成过火面积或灾损金额。",
    },
    "53_sipi": {
        "improveRun": "对照蓝、红、近红外，并检查 NIR 与 RED 是否几乎相等导致分母接近零。",
        "toApplication": f"后续可用于色素比值相关的相对分区。{_DOWNSTREAM}本页不是色素含量。",
        "bounds": "值域不必落在 −1～1；不能换算类胡萝卜素。",
        "guard": "拦住把 SIPI 写成色素毫克数。",
    },
    "54_gci": {
        "improveRun": "对照 data.green_band 与 data.nir_band，并与 RECI 的红边分母区分开。",
        "toApplication": f"后续可用于绿光叶绿素相关的相对分区。{_DOWNSTREAM}本页只输出 gci.tif。",
        "bounds": "比值减 1 不是 −1～1 指数；绿光接近零时数值会很大。",
        "guard": "拦住把 GCI 写成叶绿素毫克数。",
    },
    "55_ndsi": {
        "improveRun": "对照绿光与真实 SWIR，并和 #30 的 mndwi.tif 用途拆开。",
        "toApplication": f"后续可用于积雪相对格局示意。{_DOWNSTREAM}本页不是积雪面积，也不是水体图。",
        "bounds": "与 MNDWI 同型；云、冰、盐壳可能混淆；不输出二值雪图。",
        "guard": "拦住把 NDSI 写成积雪面积或 MNDWI 水体。",
    },
}
