import type { PrincipleViz, ProcessStage } from "./types";

function flow(caption: string, stages: ProcessStage[]): PrincipleViz {
  return { kind: "process", caption, stages };
}

function input(title: string, kicker = "输入"): ProcessStage {
  return { kicker, title, tone: "input" };
}

function step(kicker: string, title: string, note?: string): ProcessStage {
  return { kicker, title, note, tone: "step" };
}

function branch(kicker: string, title: string, note?: string): ProcessStage {
  return { kicker, title, note, tone: "branch" };
}

function output(title: string, kicker = "输出"): ProcessStage {
  return { kicker, title, tone: "output" };
}

/** 55 项原理页「处理过程」图。各算法一张，共用同一套画法。 */
export const FORMULA_PROCESSES: Record<string, PrincipleViz> = {
  "01_flight_planning": flow("先由航高和相机算出地面有多细、一条带子有多宽，再按重叠把往返航点铺进测区。", [
    input("测区多边形"),
    input("航高、焦距、像元、重叠"),
    step("公式", "GSD = 航高 × 像元 / 焦距"),
    step("公式", "航带间距 = 幅宽 × (1 − 旁向重叠)"),
    step("铺航线", "外包矩形上往返航点，奇数带反向"),
    output("mission.json　GSD / 航点 / 时长"),
    output("waypoints.geojson　地图航点"),
  ]),
  "02_sync_timestamp": flow("以高光谱曝光时刻为尺子，把 POS 插到这一刻，再给 RGB 找时间最近的一帧。", [
    input("HSI 帧时刻"),
    input("POS 轨迹"),
    input("RGB 时间戳"),
    step("钟差", "用 RGB 最近邻时间差估计固定钟差"),
    step("内插", "位置线性、姿态最短弧，插到 HSI 时刻"),
    step("配对", "校正后时刻选最近 RGB 帧"),
    output("aligned.json　逐帧 POS + RGB"),
  ]),
  "03_pos_solution": flow("先丢掉乱跳的速度点，再把观测和预测揉在一起平滑，最后把天线位置扳到相机中心。", [
    input("GNSS/POS 轨迹"),
    step("粗差", "按速度阈值标记乱跳点"),
    step("互补滤波", "预测位置和观测位置按 α 混合"),
    step("RTS", "整段再平滑一遍"),
    step("杠杆臂", "天线位置旋到相机中心"),
    output("pos.csv　平滑后的相机轨迹"),
  ]),
  "04_flight_qc": flow("看有没有过曝，再看各波段亮不亮、稳不稳。过曝比例超了只提示，不改影像。", [
    input("DN 立方体"),
    step("饱和", "DN 接近满量程则记为过曝"),
    step("场景比", "逐波段 均值 / 标准差（不是实验室 SNR）"),
    step("判定", "过曝比例对照阈值，给出是否建议复飞"),
    output("report.json　passed / 过曝比例 / 各波段比"),
  ]),
  "05_cloud_shadow": flow("先用亮、不太绿、可见光差不多白来找云，再用近红外很暗来找影。", [
    input("反射率或辐亮度立方体"),
    step("特征", "算 NDVI 和可见光是否差不多亮"),
    step("判云", "亮 + NDVI 低 + 可见光差异小"),
    step("判影", "非云非水、近红外落在低分位"),
    step("去碎斑", "形态学清掉小点"),
    output("掩膜　0 晴空 / 1 影 / 2 云"),
  ]),
  "06_dark_current": flow("先减去暗帧（或波段最小值），再把各列多出来的固定竖纹扳平。", [
    input("原始 DN"),
    input("暗帧（可选）"),
    step("减暗", "有暗帧就减，没有就减波段最小"),
    step("列纹", "减去（列均值 − 全局均值）"),
    step("截断", "负数打成 0"),
    output("dn_dark_corrected.tif　去本底 DN"),
  ]),
  "07_bad_pixel": flow("跟邻域中值差太多的点和整列，标成坏的，再用周围 3×3 填上。", [
    input("DN 立方体"),
    step("坏点", "|值 − 中值| 超过阈值"),
    step("坏列", "整列也用更松的阈值扫一遍"),
    step("手工表", "可并上已知坏像元列表"),
    step("填充", "3×3 邻域补上"),
    output("dn_repaired.tif　修复后 DN"),
  ]),
  "08_destriping": flow("把每一列的明暗、反差拉到跟整幅一样，竖条纹就会淡下去。", [
    input("有条纹的立方体"),
    step("列统计", "逐列算均值和标准差"),
    step("矩匹配", "拉到全局均值、全局标准差"),
    output("destripe.tif　去条带立方体"),
  ]),
  "09_smile_keystone": flow("先估各列光谱相对中心列挪了多少，重采样；再估各波段空间错位，再重采样。", [
    input("推扫立方体"),
    step("Smile", "各列光谱对中心列求亚像元偏移"),
    step("光谱重采样", "三次样条拉回对齐"),
    step("Keystone", "各波段估空间错位"),
    step("空间重采样", "双线性拉回对齐"),
    output("smile_corrected.tif　几何校正立方体"),
  ]),
  "10_radiance_calibration": flow("每个数字乘增益再加偏置，DN 就变成辐亮度。", [
    input("DN 立方体"),
    input("gain / offset"),
    step("公式", "L = gain × DN + offset"),
    output("radiance.tif　L1 辐亮度"),
  ]),
  "11_relative_radiometric": flow("把本景每个波段的直方图，拉去贴参考景。相对变齐，不是绝对定标。", [
    input("待校正景"),
    input("参考景"),
    step("重叠", "裁到两景都能对上的窗口"),
    step("匹配", "逐波段直方图匹配"),
    output("radiometric_aligned.tif　相对拉齐"),
  ]),
  "12_panel_reflectance": flow("用板上的亮和暗，按比例把辐亮度换成反射率。", [
    input("辐亮度立方体"),
    input("板反射率"),
    step("板光谱", "ROI 或最亮百分位取出板"),
    step("暗点", "取出暗端光谱"),
    step("公式", "ρ = ρ板 × (L − L暗) / (L板 − L暗)"),
    step("截断", "限制在约 0～1.5"),
    output("reflectance.tif　地表反射率"),
  ]),
  "13_atmospheric_correction": flow("用图里最暗的地方估一层雾一样的路径辐射，减掉后再除以透过率。", [
    input("辐亮度立方体"),
    input("太阳天顶角 / 波长"),
    step("暗目标", "用暗像元估 haze"),
    step("公式", "ρ ≈ π(L − Lhaze) / (ESUN · cosθs · τ²)"),
    step("截断", "限制在约 0～1.5"),
    output("reflectance_dos.tif　DOS2 反射率"),
  ]),
  "14_brdf_correction": flow("边缘看得更斜，用核函数估这个斜造成的明暗，再折回天底。", [
    input("反射率立方体"),
    input("太阳角 / 观测角"),
    step("几何", "按列赋观测天顶角"),
    step("核", "Ross-Thick + Li-Sparse 得到 k"),
    step("公式", "ρ天底 = ρ × k(天底) / k(实际角)"),
    output("brdf_corrected.tif　折回天底"),
  ]),
  "15_geo_locate": flow("拿这一张中心的经纬度当锚，用 GSD 写出北向上的格子。不管姿态旋转。", [
    input("影像"),
    input("中心 lon / lat / 航高"),
    step("GSD", "由航高和相机估地面分辨率"),
    step("仿射", "写成 EPSG:4326、北向上"),
    output("geolocated.tif　粗地理参考"),
    output("geo_meta.json　假设参数"),
  ]),
  "16_orthorectify": flow("地面一点经姿态转到相机，再投影到像平面；用 DEM 把斜视扳成正射。", [
    input("倾斜影像"),
    input("DEM"),
    input("姿态 / 内参"),
    step("旋转", "姿态变成旋转矩阵"),
    step("反投影", "DEM 格网点投回像平面"),
    step("分块重采样", "按行块多线程双线性取出正射格子"),
    output("ortho.tif　正射影像"),
  ]),
  "17_mosaic": flow("多景叠到同一网格，重叠处离边缘越近权越轻；磁盘分块并行写出。", [
    input("第一景或 zip 多航带"),
    input("第二景（非 zip 时必填）"),
    step("并集", "范围取并，重投影到统一网格"),
    step("羽化", "重叠区按到边缘的距离加权"),
    step("分块写出", "按 tile_size 并行算窗、串行写 GeoTIFF"),
    output("mosaic.tif　镶嵌图"),
  ]),
  "18_color_balance": flow("看局部一块有多亮、反差多大，把它轻轻拉向整幅的样子。", [
    input("镶嵌或单景"),
    step("局部统计", "盒式滤波估局部均值和方差"),
    step("Wallis", "contrast / brightness 控制拉的程度"),
    output("color_balanced.tif　匀色图"),
  ]),
  "19_multi_source_register": flow("两张灰度做相位相关，求出整体平移，再把 RGB 挪过去。", [
    input("HSI 参考"),
    input("RGB 待配准"),
    step("对齐网格", "RGB 先降到 HSI 行列"),
    step("分块相位相关", "各块估 (dy, dx)，取中位数"),
    step("分块写出", "按窗 cubic 平移 RGB，不整幅进内存"),
    output("hsi_ref.tif　参考未动"),
    output("rgb_aligned.tif　平移后的 RGB"),
  ]),
  "20_bad_band_remove": flow("场景很暗又很吵的波段丢掉，吸收窗和手工名单一并去掉，至少留 2 个。", [
    input("立方体"),
    input("波长（推荐）"),
    step("场景比", "逐波段 均值 / 标准差"),
    step("规则", "低于中位数 0.4 倍，并上吸收窗和 drop_bands"),
    step("保底", "至少留下比值最高的 2 个波段"),
    output("cube_clean.tif　压缩后的立方体"),
  ]),
  "21_savgol_smooth": flow("沿光谱取一小窗，拟合低阶多项式，用拟合值替换中心点。", [
    input("光谱立方体"),
    step("窗口", "奇数窗长，多项式阶数小于窗长"),
    step("SG", "沿波段维逐点拟合"),
    output("cube_smooth.tif　平滑后立方体"),
  ]),
  "22_normalize": flow("默认把每个像元自己的光谱减去均值再除以标准差，让形状可比。", [
    input("反射率立方体"),
    step("选方法", "默认 SNV；还可 zscore / minmax / L2"),
    step("变换", "按全图或逐像元做完写出"),
    output("cube_norm.tif　归一化立方体"),
  ]),
  "23_pca": flow("默认先估噪声再白化，再做主成分；前几维是组合轴，不是真实波长。", [
    input("立方体"),
    step("噪声", "MNF 用空间差分估噪声协方差"),
    step("分解", "特征分解，取前 k 个分量"),
    output("mnf_cube.tif 或 pca_cube.tif　降维立方体"),
  ]),
  "24_band_select": flow("每个波段打一个分，留下分数最高的 k 个。无标签看方差，有标签看类间差异。", [
    input("立方体"),
    input("标签（可选）"),
    step("打分", "无标签用方差；有标签用 ANOVA F"),
    step("截断", "排序后取 top-k"),
    output("selected_bands.tif　子集立方体"),
    output("band_scores.json　得分和原索引"),
  ]),
  "25_superpixel": flow("用前三个波段当颜色，在影像上切成一块块紧凑小斑。", [
    input("立方体"),
    step("三通道", "取前三个原始波段当特征"),
    step("SLIC", "局部紧凑聚类，得到对象"),
    output("superpixel_labels.tif　从 1 编号的小斑"),
  ]),
  "26_patch_build": flow("只在有标签的像元上切奇数边长的小立方体，打包给网络用。", [
    input("立方体"),
    input("标签图"),
    step("选点", "label > 0 的像元"),
    step("切片", "奇数边长 P，边缘填充后再切"),
    output("patches.npz　patches / labels / coords"),
  ]),
  "27_ndvi": flow("红光低、近红外高，相减再除以相加，用来看相对更绿的地方。", [
    input("反射率立方体"),
    step("取波段", "红光 RED + 近红外 NIR"),
    step("公式", "NDVI = (NIR − RED) / (NIR + RED)"),
    output("ndvi.tif　绿度相对差异"),
  ]),
  "28_ndre": flow("和 NDVI 同一写法，只是红光换成红边，封垄以后还比较分得动。", [
    input("反射率立方体（须有真红边）"),
    step("取波段", "红边 RE + 近红外 NIR"),
    step("公式", "NDRE = (NIR − RE) / (NIR + RE)"),
    output("ndre.tif　红边绿度"),
  ]),
  "29_evi_savi": flow("同一套蓝、红、近红外，一次写出三张图。三条公式并排，不合成一张。", [
    input("反射率立方体"),
    step("取波段", "蓝、红、近红外"),
    branch("EVI", "加蓝光，减轻大气和土壤"),
    branch("SAVI", "分母加 L，减轻土壤"),
    branch("MSAVI", "L 随影像自己变"),
    output("evi.tif"),
    output("savi.tif"),
    output("msavi.tif"),
  ]),
  "30_ndmi_ndwi": flow("绿光、近红外、短波红外组合出三张水/湿度图。没有真 SWIR，NDMI 和 MNDWI 不要读。", [
    input("反射率立方体"),
    step("取波段", "绿光、近红外、短波红外"),
    branch("NDMI", "NIR 与 SWIR　看冠层水分"),
    branch("NDWI", "绿光与 NIR　看开放水面"),
    branch("MNDWI", "绿光与 SWIR　压制建成区"),
    output("ndmi.tif"),
    output("ndwi.tif"),
    output("mndwi.tif"),
  ]),
  "31_red_edge_params": flow("先插到四个固定波长，再并排算「陡坡在哪」「有多高」「最陡在哪」，写成三层，不合成一个数。", [
    input("反射率立方体"),
    input("真实波长"),
    step("内插", "670 / 700 / 740 / 780 nm"),
    branch("Guyot REP", "陡坡在哪"),
    branch("振幅", "陡坡有多高"),
    branch("导数 REP", "最陡处在哪"),
    output("params.tif　三波段（预览只渲 Guyot）"),
  ]),
  "32_regression_inversion": flow("有化验图时：光谱先标准化，用部分样本学 PLS，再预测整张图。", [
    input("反射率立方体"),
    input("化验真值图"),
    step("SNV", "逐像元标准化光谱"),
    step("划分", "抽出有真值的像元，随机留出测试"),
    step("PLS", "学光谱到化验值的线性关系"),
    step("预测", "整图写出，并报 R² / RMSE"),
    output("inversion.tif　经验反演图"),
  ]),
  "33_physical_inversion": flow("先造 400 条假光谱对照表，再给每个格子算差，最后把最像的那一批叶面积和叶绿素一起平均。", [
    input("反射率立方体"),
    input("波长 + 太阳/观测角"),
    step("公式 1", "PROSAIL：LAI 25 档 × Cab 16 档 = 400 条假光谱", "土壤、叶倾角写死"),
    step("公式 2", "每个像元 vs 表里每一行 → RMSE（可改 SAM）", "越小越像"),
    step("公式 3", "约 20 条的 LAI 与 Cab 一对一起写出", "可离开格点"),
    output("lai.tif　看密不密"),
    output("cab.tif　看绿不绿"),
  ]),
  "34_svm_rf_classify": flow("用有标签的像元教会分类器，再给整张图每个格子贴类别。", [
    input("立方体"),
    input("标签图（0 为背景忽略）"),
    step("抽样本", "只拿 gt > 0 的像元"),
    step("划分", "训练 / 测试随机拆开"),
    step("拟合", "SVM 最大间隔，或随机森林投票"),
    step("预测", "整图分类，报 OA / AA / Kappa"),
    output("pred_map.tif　类别图"),
  ]),
  "35_spectral_matching": flow("每个格子跟光谱库比夹角，谁夹角最小就归谁。没有拒绝，个个都会分到一类。", [
    input("立方体"),
    input("端元 CSV"),
    step("对齐", "波段数、顺序、尺度必须一致"),
    step("公式", "θ = arccos( x·e / (‖x‖‖e‖) )"),
    step("分类", "取夹角（或 SID）最小的端元"),
    output("pred_map.tif　类别"),
    output("angle.tif　最小角（不是概率）"),
  ]),
  "36_cnn1d_classify": flow("把一条光谱当成一维信号，短训一个小卷积网，再滑过整图。", [
    input("立方体"),
    input("标签"),
    step("标准化", "标注像元 Z-score"),
    step("序列", "每个像元变成 1 通道光谱"),
    step("短训", "Conv1d → 池化 → 全连接"),
    step("推理", "整图逐像元分类"),
    output("pred_map.tif　光谱分类图"),
  ]),
  "37_cnn3d_classify": flow("先降维，再切邻域小块，三维卷积同时看空间和光谱。", [
    input("立方体"),
    input("标签"),
    step("PCA", "整图先压波段"),
    step("切块", "奇数边长的空谱 patch"),
    step("短训", "Conv3d 再 Conv2d"),
    step("滑窗", "整图预测"),
    output("pred_map.tif　空谱分类图"),
  ]),
  "38_transformer_classify": flow("光谱切成一小段一小段 token，用两层注意力看长程依赖，再分类。", [
    input("立方体"),
    input("标签"),
    step("分词", "group=3 滑窗变成 token"),
    step("编码", "两层 Transformer + 残差"),
    step("分类", "均值池化后输出类别"),
    output("pred_map.tif　Transformer 分类图"),
  ]),
  "39_few_shot_classify": flow("每类只抽几个样，平均成一条原型光谱，谁跟原型夹角小就归谁。", [
    input("立方体"),
    input("标签"),
    step("支持集", "每类抽 shots 个像元"),
    step("原型", "同类光谱取平均"),
    step("匹配", "全图按 SAM 夹角归类"),
    output("pred_map.tif　少样本分类图"),
  ]),
  "40_detect_segment": flow("用低 NDVI 估一条目标光谱，算 ACE 得分，再按百分位抠斑、转成多边形。", [
    input("立方体"),
    step("种子", "低 NDVI 像元估目标方向"),
    step("ACE", "去掉背景相关后，看目标方向还剩多少"),
    step("阈值", "本景百分位，不是固定分数"),
    step("斑块", "连通域滤小斑，可转 GeoJSON"),
    output("score / mask　检测得分和斑块"),
  ]),
  "41_unmixing": flow("假设像元是几条端元按比例加起来的，求出各占多少，比例和为 1 且不为负。", [
    input("立方体"),
    input("端元矩阵 E"),
    step("模型", "x ≈ E a，a ≥ 0，各分量加起来为 1"),
    step("求解", "逐像元非负最小二乘"),
    output("abundance.tif　每层一种端元丰度"),
  ]),
  "42_anomaly_detect": flow("看这个格子离背景云有多远。远的记高分，再按本景百分位画掩膜。", [
    input("立方体"),
    step("背景", "全局或滑窗外窗估均值和协方差"),
    step("公式", "RX = 马氏距离²"),
    step("阈值", "高百分位，只相对本景"),
    output("score.tif　异常得分"),
    output("mask.tif　相对离群掩膜"),
  ]),
  "43_change_detect": flow("两期影像先标准化，再迭代找出相关结构，剩下的 χ² 大就标成变化。", [
    input("时相 1"),
    input("时相 2"),
    step("对齐尺度", "两期 z-score"),
    step("IR-MAD", "迭代加权典型相关"),
    step("χ²", "变化强度图"),
    step("阈值", "本景百分位掩膜"),
    output("magnitude / mask　变化强度和变化区"),
  ]),
  "44_postprocess_smooth": flow("窗口里谁票多听谁的，再把太小的碎斑填成邻居。图更整齐，不等于更准。", [
    input("分类标签图"),
    step("众数", "窗口内出现最多的类替换中心"),
    step("筛斑", "连通域面积小于阈值则填邻域众数"),
    output("labels.tif　平滑后的分类图"),
  ]),
  "45_parcel_zonal_stats": flow("用多边形把格子圈起来。连续量算分位数，分类则算各类占地。", [
    input("单波段图"),
    input("地块 GeoJSON（可选）"),
    step("栅格化", "多边形套到影像格子上"),
    step("统计", "连续量：分位数；分类：面积占比"),
    output("report.json　整景 + 逐地块"),
  ]),
  "46_reci": flow("近红外除以红边再减 1。要有真红边，读的是相对差异，不是叶绿素毫克数。", [
    input("反射率立方体（须有真红边）"),
    step("取波段", "红边 RE + 近红外 NIR"),
    step("公式", "RECI = NIR / RE − 1"),
    output("reci.tif　红边叶绿素相关相对差异"),
  ]),
  "47_gndvi": flow("和 NDVI 同一写法，红光换成绿光，对叶绿素相关的绿反射更敏感一些。", [
    input("反射率立方体"),
    step("取波段", "绿光 GREEN + 近红外 NIR"),
    step("公式", "GNDVI = (NIR − GREEN) / (NIR + GREEN)"),
    output("gndvi.tif　绿色归一化植被指数"),
  ]),
  "48_osavi": flow("NDVI 的分母再加一个固定 L，减轻土壤发亮带来的抬升。", [
    input("反射率立方体"),
    step("取波段", "红光 RED + 近红外 NIR"),
    step("公式", "OSAVI = (NIR − RED) / (NIR + RED + L)"),
    output("osavi.tif　土壤调节后的绿度"),
  ]),
  "49_arvi": flow("先用蓝光改一下红光，再做归一化差，用来减轻一点气溶胶残差。", [
    input("反射率立方体"),
    step("取波段", "蓝、红、近红外"),
    step("改红光", "RB = RED − γ(BLUE − RED)"),
    step("公式", "ARVI = (NIR − RB) / (NIR + RB)"),
    output("arvi.tif　耐大气植被指数"),
  ]),
  "50_vari": flow("只用蓝绿红三个可见光通道，近红外没有时也能看相对绿度。", [
    input("可见光反射率"),
    step("取波段", "蓝、绿、红"),
    step("公式", "VARI = (GREEN − RED) / (GREEN + RED − BLUE)"),
    output("vari.tif　可见光绿度"),
  ]),
  "51_lai_index": flow("先算 EVI，再套一条经验直线。这是示意叶面积，不是 #33 的物理反演。", [
    input("反射率立方体"),
    step("EVI", "用蓝、红、近红外先算 EVI"),
    step("公式", "LAI = max(3.618 × EVI − 0.118, 0)"),
    output("lai_index.tif　经验叶面积示意"),
  ]),
  "52_nbr": flow("近红外减短波红外再归一化。过火后短波红外相对升高，NBR 会下降。", [
    input("反射率立方体（须有真 SWIR）"),
    step("取波段", "近红外 NIR + 短波红外 SWIR"),
    step("公式", "NBR = (NIR − SWIR) / (NIR + SWIR)"),
    output("nbr.tif　燃烧/过火相对差异"),
  ]),
  "53_sipi": flow("近红外减蓝，再除以近红外减红，用来减弱结构影响、突出色素对比。", [
    input("反射率立方体"),
    step("取波段", "蓝、红、近红外"),
    step("公式", "SIPI = (NIR − BLUE) / (NIR − RED)"),
    output("sipi.tif　结构不敏感色素指数"),
  ]),
  "54_gci": flow("近红外除以绿光再减 1，绿光反射越低、相对叶绿素相关信号越大。", [
    input("反射率立方体"),
    step("取波段", "绿光 GREEN + 近红外 NIR"),
    step("公式", "GCI = NIR / GREEN − 1"),
    output("gci.tif　绿色叶绿素相关相对差异"),
  ]),
  "55_ndsi": flow("绿光减短波红外再归一化。雪在绿光亮、在短波红外暗，比值会高。", [
    input("反射率立方体（须有真 SWIR）"),
    step("取波段", "绿光 GREEN + 短波红外 SWIR"),
    step("公式", "NDSI = (GREEN − SWIR) / (GREEN + SWIR)"),
    output("ndsi.tif　雪/冰相对差异"),
  ]),
};
