import type { PrincipleDoc } from "./types";

const VIS = { b: "#5b8def", g: "#3d5648", r: "#c45c4a", re: "#b0893a", n: "#8c2f2f", s: "#6b4f8c" };

export const L3_PRINCIPLES: PrincipleDoc[] = [
  {
    id: "27_ndvi",
    purpose: "用红光吸收与近红外强反射的反差，快速看植被长势与覆盖。",
    why: "叶绿素在红光被吸收、叶肉在近红外高反射。健康植被 NDVI 高，裸土低。",
    formula: "NDVI = (NIR − RED) / (NIR + RED)",
    formulaNote: "必须用反射率。高生物量时易饱和，可改看 NDRE/EVI。",
    steps: ["按索引取红光与近红外", "归一化差", "输出指数图"],
    viz: {
      kind: "index_spectrum",
      caption: "拖动「长势」：红光更低、近红外更高，NDVI 上升。",
      bands: [
        { id: "red", label: "红 RED", nm: 660, color: VIS.r },
        { id: "nir", label: "近红外 NIR", nm: 800, color: VIS.n },
      ],
    },
    inputs: [
      { name: "file", meaning: "反射率立方体" },
      { name: "red_band / nir_band", meaning: "默认 2 / 3（从 0 起）" },
    ],
    outputs: [{ name: "ndvi.tif", meaning: "约 −1～1 的指数图" }],
    industryGap: "无云影掩膜；波段索引须按真实波长改，不能死记默认。",
    checks: ["把红边误当成 NIR，NDVI 会偏高还是偏低？", "为何 DN 不能直接算 NDVI？"],
    summary: {
      definition: "以近红外与红光反射率的归一化差衡量绿色植被活力。",
      value: "快速生成长势、覆盖度和异常区的相对空间分布。",
      keyInput: "完成辐射定标的反射率立方体，以及对应真实波长的红光与近红外索引。",
      keyOutput: "单波段 NDVI GeoTIFF，理论范围 −1～1。",
      keyLimit: "密冠层易饱和，且云影、裸土背景和错误波段会改变数值。",
    },
    background: ["红光约 630–690 nm 受叶绿素吸收，近红外约 760–900 nm 受叶片结构强反射。", "归一化差可削弱整体照度尺度变化，但不能替代反射率定标。"],
    prerequisites: ["输入须为可比反射率，并处理云、阴影、饱和值与 NoData。", "按元数据波长选择 RED/NIR；默认 2/3 仅适用于随附教学数据且索引从 0 起。"],
    parameterNotes: [
      { name: "red_band", role: "指定红光通道", guidance: "选传感器中心波长最接近约 660 nm 的有效波段", effect: "决定叶绿素吸收端的基线", risk: "误选红边会系统性抬高或改变 NDVI" },
      { name: "nir_band", role: "指定近红外通道", guidance: "选约 800 nm 且避开水汽吸收和低信噪波段", effect: "决定叶片结构反射端", risk: "越界、低信噪或伪近红外会产生无意义结果" },
    ],
    resultInterpretation: ["健康密植被通常为较高正值，裸土接近零，水体常为零或负值；阈值须在本景校准。", "比较地块或时相时应保持传感器、波段、定标和掩膜流程一致。"],
    applicable: ["同一传感器、同一处理链下的作物长势分区与巡田。", "具备红光和近红外反射率波段的植被覆盖快速筛查。"],
    notApplicable: ["只有 DN/辐亮度而无可靠定标，或没有真实近红外波段。", "需要在高 LAI 条件下定量反演叶绿素或生物量。"],
    risks: ["分母接近零、NoData 未掩膜会产生极值并污染统计。", "将固定阈值跨地区、季节或传感器复用会造成误判。"],
    upstream: ["反射率定标、坏波段剔除与云影/NoData 掩膜。"],
    downstream: ["地块分区统计、长势分级和时序异常分析。"],
    demoFocus: ["现场展示波长元数据如何映射为 0 起波段索引。", "对比同一像元 RED/NIR 变化对 NDVI 的方向与饱和现象。"],
  },
  {
    id: "28_ndre",
    purpose: "用红边代替红光，对叶绿素更敏感，密冠层比 NDVI 晚饱和。",
    why: "红边（约 700–740 nm）随叶绿素移动。氮营养、生育后期常用 NDRE。",
    formula: "NDRE = (NIR − RE) / (NIR + RE)",
    steps: ["取红边与近红外", "归一化差", "输出 NDRE 图"],
    viz: {
      kind: "index_spectrum",
      caption: "红边位于「红谷爬向近红外高原」的陡坡上。",
      bands: [
        { id: "re", label: "红边 RE", nm: 720, color: VIS.re },
        { id: "nir", label: "近红外 NIR", nm: 800, color: VIS.n },
      ],
    },
    inputs: [
      { name: "file", meaning: "反射率立方体（须有红边波段）" },
      { name: "re_band / nir_band", meaning: "默认 4 / 3" },
    ],
    outputs: [{ name: "ndre.tif", meaning: "红边植被指数图" }],
    industryGap: "没有真红边波段时不要套默认索引。",
    checks: ["为何密冠层更爱 NDRE 而不是 NDVI？"],
    summary: {
      definition: "以近红外与红边反射率的归一化差描述叶绿素和冠层状态。",
      value: "在中高覆盖植被中比 NDVI 更晚饱和，适合营养与生育后期差异识别。",
      keyInput: "含真实红边波段的反射率立方体及红边、近红外波段索引。",
      keyOutput: "单波段 NDRE GeoTIFF。",
      keyLimit: "对红边中心波长、物候和品种敏感，不能直接套统一阈值。",
    },
    background: ["红边是红光吸收谷向近红外高反射平台过渡的陡坡，约位于 700–740 nm。", "叶绿素变化会改变红边斜率和位置，因此 NDRE 对密冠层仍保有响应。"],
    prerequisites: ["输入须为反射率，并完成云影、NoData 与低信噪波段掩膜。", "确认传感器确有红边通道；默认 re_band=4、nir_band=3 只对应教学数据。"],
    parameterNotes: [
      { name: "re_band", role: "指定红边通道", guidance: "依据波长表选择约 705–740 nm 的目标红边中心", effect: "不同中心波长对应不同叶绿素敏感度", risk: "把红光或近红外误作红边会改变指数含义" },
      { name: "nir_band", role: "指定近红外参考", guidance: "选择稳定高信噪的近红外平台波段", effect: "提供冠层结构参照", risk: "与红边过近会压缩指数动态范围" },
    ],
    resultInterpretation: ["较高值通常对应更强冠层和较高叶绿素，但需用本地样本建立营养或胁迫解释。", "跨期比较应固定波段中心和预处理，并排除裸土比例变化。"],
    applicable: ["具有窄红边波段的高光谱或红边多光谱作物监测。", "NDVI 已接近饱和的中高覆盖冠层差异分析。"],
    notApplicable: ["没有红边波段却用相邻可见光或近红外通道代替。", "稀疏植被且土壤背景主导、需要直接定量氮含量的场景。"],
    risks: ["传感器红边中心差异会让同名 NDRE 数值不可直接横比。", "NoData、阴影和波段错位会在归一化分母中放大异常。"],
    upstream: ["反射率校正、波长核验与有效像元掩膜。"],
    downstream: ["叶绿素相对分区、施肥巡查与地块统计。"],
    demoFocus: ["在光谱曲线上指出红边斜坡与近红外平台。", "并排显示 NDVI 与 NDRE 在密冠层区域的动态范围。"],
  },
  {
    id: "29_evi_savi",
    purpose: "一次给出 EVI（抑大气/饱和）、SAVI 与 MSAVI（抑土壤）。",
    why: "稀疏植被土壤亮、密植被 NDVI 饱和，需要调节指数。",
    formula: "EVI=2.5(N−R)/(N+6R−7.5B+1)；SAVI=(1+L)(N−R)/(N+R+L)；MSAVI 自洽土壤调节",
    formulaNote: "默认 L=0.5。输出三波段栈：EVI、SAVI、MSAVI。",
    steps: ["取蓝/红/近红外", "分别套三公式", "堆成三波段产品"],
    viz: {
      kind: "index_spectrum",
      caption: "EVI 多用一个蓝光通道来压大气残差。",
      bands: [
        { id: "blue", label: "蓝", nm: 480, color: VIS.b },
        { id: "red", label: "红", nm: 660, color: VIS.r },
        { id: "nir", label: "近红外", nm: 800, color: VIS.n },
      ],
    },
    inputs: [
      { name: "file", meaning: "反射率" },
      { name: "L", meaning: "SAVI 土壤系数，默认 0.5" },
    ],
    outputs: [{ name: "evi_savi_msavi.tif", meaning: "三指数栈" }],
    industryGap: "EVI 系数来自 MODIS 习惯；低空白板数据上蓝光项增益较小。",
    checks: ["L=0 时 SAVI 与 NDVI 是什么关系？"],
    summary: {
      definition: "同时计算 EVI、SAVI、MSAVI，分别抑制大气残差、NDVI 饱和或土壤背景。",
      value: "按冠层稀密和数据条件选择更合适的植被响应，而非只依赖 NDVI。",
      keyInput: "蓝、红、近红外反射率波段，以及 SAVI 土壤调节系数 L。",
      keyOutput: "按 EVI、SAVI、MSAVI 顺序组成的三波段 GeoTIFF。",
      keyLimit: "EVI 经验系数和 L 并非对所有传感器、土壤与低空场景最优。",
    },
    background: ["EVI 用蓝光估计红光中的气溶胶残差，并降低高生物量饱和。", "SAVI 用显式 L 抑制土壤线影响，MSAVI 则由观测值自适应调节土壤项。"],
    prerequisites: ["三个索引均应使用同尺度反射率，波段索引必须按中心波长核验。", "先掩膜 NoData、云影和饱和像元；蓝光低信噪时重点检查 EVI。"],
    parameterNotes: [
      { name: "L", role: "控制 SAVI 的土壤背景修正", guidance: "默认 0.5；高覆盖可趋近 0，稀疏冠层可结合样地调整", effect: "L 越大通常越强调土壤校正", risk: "脱离覆盖度固定套用会引入偏差" },
      { name: "blue/red/nir_band", role: "定位 EVI 与土壤调节指数通道", guidance: "分别匹配约 480、660、800 nm 的有效波段", effect: "决定三个指数的光谱响应", risk: "蓝光受阴影或噪声污染时 EVI 分母可能不稳定" },
    ],
    resultInterpretation: ["输出三波段必须按 EVI、SAVI、MSAVI 分别读取，不能把波段号当类别。", "指数高低仅表示本景相对植被响应，跨景阈值需经样地或稳定地物校准。"],
    applicable: ["稀疏冠层土壤背景明显时比较 SAVI/MSAVI。", "具备可靠蓝光校正且高生物量 NDVI 易饱和时评估 EVI。"],
    notApplicable: ["输入为 DN、经过 SNV 的光谱或缺少所需真实波段。", "希望从三个指数直接获得无标定的绝对 LAI、氮或产量。"],
    risks: ["分母接近零会产生异常值，NoData 必须显式掩膜。", "将 MODIS EVI 系数无验证地迁移到近地窄带传感器可能失真。"],
    upstream: ["反射率校正、波段映射及云影/NoData 掩膜。"],
    downstream: ["指数对照选型、地块统计和经验模型特征构建。"],
    demoFocus: ["用稀疏与密冠层样例说明三指数分别解决什么问题。", "调节 L 展示 SAVI 向 NDVI 靠近及土壤背景响应变化。"],
  },
  {
    id: "30_ndmi_ndwi",
    purpose: "水分与水体：NDMI 看植被水分，NDWI/MNDWI 看水体。",
    why: "近红外、短波红外对水和叶片含水敏感。",
    formula: "NDMI=(NIR−SWIR)/(NIR+SWIR)；NDWI=(G−NIR)/(G+NIR)；MNDWI=(G−SWIR)/(G+SWIR)",
    formulaNote: "本仓库 NDWI 是 McFeeters，不是 Gao 的 (NIR−SWIR) 版本。",
    steps: ["取绿/近红外/SWIR", "三条归一化差", "输出三波段栈"],
    viz: {
      kind: "index_spectrum",
      caption: "水体：绿光相对高、近红外极低。植被水分：SWIR 随含水下降。",
      bands: [
        { id: "green", label: "绿", nm: 560, color: VIS.g },
        { id: "nir", label: "近红外", nm: 800, color: VIS.n },
        { id: "swir", label: "SWIR", nm: 1600, color: VIS.s },
      ],
    },
    inputs: [
      { name: "file", meaning: "反射率；无真 SWIR 时 NDMI/MNDWI 无物理意义" },
      { name: "green/nir/swir_band", meaning: "默认 1 / 3 / 5" },
    ],
    outputs: [{ name: "ndmi_ndwi_mndwi.tif", meaning: "水分/水体三指数" }],
    industryGap: "教学立方体常无 SWIR。专家必须说清「哪一个 NDWI」。",
    checks: ["Gao NDWI 与 McFeeters NDWI 差在哪两个波段？"],
    summary: {
      definition: "组合 NDMI、McFeeters NDWI 与 MNDWI，分别观察植被含水和开放水体。",
      value: "在一个产品中区分冠层水分响应与水体增强，避免同名 NDWI 概念混用。",
      keyInput: "绿光、近红外和真实短波红外反射率波段。",
      keyOutput: "按 NDMI、NDWI、MNDWI 顺序组成的三波段 GeoTIFF。",
      keyLimit: "缺少 SWIR 时 NDMI/MNDWI 无物理意义；本实现 NDWI 不是 Gao 版本。",
    },
    background: ["McFeeters NDWI=(G−NIR)/(G+NIR) 强调水体对近红外的低反射。", "Gao 常称 NDWI 的 (NIR−SWIR)/(NIR+SWIR) 在此按植被水分用途命名为 NDMI。"],
    prerequisites: ["核验传感器波长范围；green/nir/swir 默认 1/3/5 仅为 0 起教学索引。", "使用反射率并掩膜 NoData、云影、镜面反射和低信噪 SWIR。"],
    parameterNotes: [
      { name: "green_band", role: "提供水体可见光参考", guidance: "选择约 560 nm 的有效绿光波段", effect: "参与 McFeeters NDWI 与 MNDWI", risk: "藻华、浑水和阴影会改变绿光基线" },
      { name: "nir_band / swir_band", role: "区分水体与冠层含水响应", guidance: "NIR 取约 800 nm，SWIR 通常取约 1.6 μm 且避开强吸收低信噪区", effect: "决定 NDMI、NDWI 和 MNDWI 的对比", risk: "可见近红外传感器不能用末波段冒充 SWIR" },
    ],
    resultInterpretation: ["NDMI 高低反映相对冠层含水响应；McFeeters NDWI/MNDWI 较高区域可能是水体，但阈值依场景而变。", "城市阴影、湿土、塑料膜和浅水浑浊都可能与水体指数混淆。"],
    applicable: ["同时覆盖绿光、近红外、SWIR 的植被水分与水体快速制图。", "明确记录 NDWI 公式后开展同传感器时序比较。"],
    notApplicable: ["只有 VNIR 数据却要求输出 NDMI 或 MNDWI。", "需要直接反演叶片绝对含水量或在无验证下使用固定水体阈值。"],
    risks: ["同名 NDWI 版本混用会导致指标方向和业务结论完全不同。", "NoData 或分母近零会制造高绝对值伪异常。"],
    upstream: ["反射率校正、SWIR 质量检查与水汽坏波段剔除。"],
    downstream: ["水体候选掩膜、旱情相对分区和地块统计。"],
    demoFocus: ["明确逐条展示三公式和输出波段顺序。", "用无 SWIR 数据演示为何不能仅按波段索引强行计算。"],
  },
  {
    id: "31_red_edge_params",
    purpose: "提取红边位置 REP 与红边振幅，刻画物候和叶绿素。",
    why: "这是高光谱相对多光谱的核心优势：红边会随叶绿素移动。",
    formula: "Guyot：REP = 700 + 40 × ((R670+R780)/2 − R700) / (R740 − R700)",
    formulaNote: "另输出振幅 R780−R670，以及 SG 一阶导数峰值波长。",
    steps: ["内插到 670/700/740/780 nm", "Guyot 直线交会", "SG 导数求峰", "三波段产品"],
    viz: { kind: "red_edge", caption: "四点直线交会：红边位置随叶绿素向长波移动。" },
    inputs: [
      { name: "file", meaning: "≥3 波段反射率" },
      { name: "wl_start_nm / wl_end_nm", meaning: "无波长头时默认 450–850" },
    ],
    outputs: [{ name: "red_edge_params.tif", meaning: "Guyot REP、振幅、导数 REP" }],
    industryGap: "假等间隔波长会让纳米数值对不上真实传感器。",
    checks: ["叶绿素升高时 REP 应向哪一侧移动？"],
    summary: {
      definition: "通过四点 Guyot 交会和 SG 一阶导数峰提取红边位置，并计算红边振幅。",
      value: "把完整高光谱红边形状压缩为可制图的物候与叶绿素敏感参数。",
      keyInput: "带可靠波长轴、覆盖 670–780 nm 的反射率立方体。",
      keyOutput: "Guyot REP、R780−R670 振幅和导数 REP 三波段 GeoTIFF。",
      keyLimit: "波长元数据、光谱分辨率和噪声会直接决定纳米级位置是否可信。",
    },
    background: ["Guyot 方法以 670、700、740、780 nm 内插反射率构造半高位置。", "导数法在红边区寻找最大斜率波长，对连续窄波段更有意义。"],
    prerequisites: ["输入须为反射率并覆盖所需波长；至少 3 波段只是代码下限，不等于科学上足够。", "优先提供真实波长数组；450–850 nm 等间隔仅是无元数据时的近似。"],
    parameterNotes: [
      { name: "wavelengths_nm 或 wl_start_nm/wl_end_nm", role: "建立波段索引到纳米的映射", guidance: "优先使用传感器逐波段中心波长", effect: "决定四点内插和导数峰的位置", risk: "假等间隔波长会产生看似精确但错误的 REP" },
      { name: "SG 窗口条件", role: "稳定一阶导数峰", guidance: "窗口应小于红边主要宽度且与波段数匹配", effect: "平衡噪声与峰位保持", risk: "过大抹平峰位，过小让噪声成为最大导数" },
    ],
    resultInterpretation: ["REP 向长波移动常与叶绿素增加相关，但品种、冠层结构和物候也会影响。", "振幅描述红光谷至近红外平台的反差，须结合 REP 与原始光谱检查。"],
    applicable: ["具有连续窄带红边覆盖的高光谱作物物候和叶绿素相对分析。"],
    notApplicable: ["只有宽带多光谱且无法可靠内插 670/700/740/780 nm。", "波长标定未知或红边区存在严重坏波段。"],
    risks: ["低信噪导数会造成像素级跳变，应在结果图上识别条带和离散波长格。", "将 REP 单独解释为绝对叶绿素含量会忽略结构与背景混杂。"],
    upstream: ["波长标定、坏波段剔除与适度 SG 平滑。"],
    downstream: ["物候分区、叶绿素经验建模和地块统计。"],
    demoFocus: ["在单条光谱上同时标出四个 Guyot 波长和导数峰。", "展示真实波长与假等间隔波长导致的 REP 偏移。"],
  },
  {
    id: "32_regression_inversion",
    purpose: "用同步实测把光谱回归成连续生化量（叶绿素、氮等）。",
    why: "不靠辐射传输，靠「光谱 + 化验」学一个映射。",
    formula: "SNV 后 PLS：潜变量最大化 X 与 Y 的协方差，再预测整图",
    steps: ["立方体与真值图对齐", "SNV", "划分训练/测试", "PLS 拟合", "全图预测并报 R²/RMSE"],
    viz: { kind: "regression", caption: "拖动样本「线性程度」：PLS 适合近线性关系，弯了就会残差变大。" },
    inputs: [
      { name: "file", meaning: "光谱立方体" },
      { name: "file2", meaning: "必填真值图，同尺寸" },
      { name: "n_components", meaning: "PLS 成分数，默认 3" },
    ],
    outputs: [{ name: "inversion.tif", meaning: "预测的连续量图" }],
    industryGap: "像元随机划分会空间泄漏，R² 虚高。",
    checks: ["成分数过多时训练误差和测试误差如何走？"],
    summary: {
      definition: "用 SNV 预处理后的光谱和同步真值训练 PLS 连续变量回归。",
      value: "将叶绿素、氮或含水量样本关系推广为整幅定量预测图。",
      keyInput: "同尺寸光谱立方体、连续真值图和 PLS 成分数。",
      keyOutput: "连续量 inversion.tif，以及随机测试集 R²、RMSE 和样本数。",
      keyLimit: "当前按像元随机切分，空间自相关会造成泄漏和过于乐观的指标。",
    },
    background: ["PLS 用少量潜变量提取与真值协方差较大的光谱方向，适合高共线波段。", "本实现对每个像元做 SNV，随后随机划分训练/测试并对全图预测。"],
    prerequisites: ["真值必须与影像严格同尺寸、同像元对齐，并具有明确单位和有效值范围。", "建模前应按地块、样方或空间块设计独立验证，而不是把相邻像元拆到两侧。"],
    parameterNotes: [
      { name: "n_components", role: "控制 PLS 潜变量数量", guidance: "在空间独立验证上选取；默认 3 并受波段数和样本数约束", effect: "增加可拟合的光谱变化维度", risk: "过多会拟合噪声并降低跨地块泛化" },
      { name: "test_size", role: "设置随机测试像元比例", guidance: "默认 0.3 仅作教学运行，正式评估改用地块级留出", effect: "改变训练量与测试指标方差", risk: "无论比例多少，像元随机划分都不能消除空间泄漏" },
    ],
    resultInterpretation: ["R² 表示测试真值方差的解释比例，RMSE 与目标同单位；两者必须连同真值范围和独立性报告。", "预测超出训练真值范围属于外推，应结合残差、散点图与空间分布审查。"],
    applicable: ["有同步、同尺度化验或地面测量的连续生化量经验反演。", "光谱—目标关系近似线性且目标域与训练域一致的场景。"],
    notApplicable: ["无可靠真值却希望获得绝对定量结果。", "跨品种、季节或传感器直接迁移且未做外部验证。"],
    risks: ["真值图中背景值若未掩膜会被当作有效回归样本。", "SNV 会移除绝对亮度信息，目标若主要依赖幅值可能降低性能。"],
    upstream: ["反射率预处理、真值质控、精确配准与空间分组设计。"],
    downstream: ["独立地块验证、不确定性分析和地块均值/分位数汇总。"],
    demoFocus: ["对比像元随机划分与地块留出时 R²/RMSE 的差异。", "调节成分数并观察训练拟合、测试误差和整图伪影。"],
  },
  {
    id: "33_physical_inversion",
    purpose: "用 PROSAIL 查找表，按光谱角匹配反演 LAI 与叶绿素 Cab。",
    why: "有物理意义、少依赖化验，但对反射率和几何角敏感。",
    formula: "构建 (LAI, Cab) LUT → 像元与表行余弦相似度 argmax",
    steps: ["按太阳/观测角建 96 条 LUT", "光谱归一化", "最近邻匹配", "写出 LAI、Cab 图"],
    viz: { kind: "lut", caption: "像元光谱在库里找「角度最近」的一条，读出 LAI/Cab。" },
    inputs: [
      { name: "file", meaning: "地表反射率（不能是 DN）" },
      { name: "solar_zenith 等", meaning: "几何角，默认 30/0/0" },
    ],
    outputs: [
      { name: "lai.tif", meaning: "叶面积指数" },
      { name: "cab.tif", meaning: "叶绿素 μg/cm²" },
    ],
    industryGap: "粗网格阶梯伪影；土壤和叶倾角写死。业界用连续优化或更密 LUT。",
    checks: ["输入若是辐亮度而不是反射率，LUT 为什么会全错？"],
    summary: {
      definition: "用 PROSPECT-5+4SAIL 生成 LAI×Cab 查找表，再按最小光谱角逐像元匹配。",
      value: "在少量化验条件下给出具有物理参数含义的 LAI 与叶绿素候选解。",
      keyInput: "地表反射率、真实波长数组及太阳/观测几何角。",
      keyOutput: "lai.tif、cab.tif，以及 96 条 LUT 和波长元数据。",
      keyLimit: "仅搜索 LAI 0.2–6.0 与 Cab 10–70 的离散网格，其他 PROSAIL 参数固定。",
    },
    background: ["LUT 由 12 个 LAI 与 8 个 Cab 组合构成 96 条模拟光谱。", "光谱角强调形状而弱化幅值，不能自动解决参数等效性和模型—实景差距。"],
    prerequisites: ["输入必须是与 PROSAIL 定义一致的反射率，不能是 DN 或辐亮度。", "提供逐波段中心波长并核验太阳天顶角、观测天顶角和相对方位角的定义与单位。"],
    parameterNotes: [
      { name: "wavelengths_nm", role: "将传感器波段与 PROSAIL 400–2500 nm 光谱对齐", guidance: "传入与立方体波段数一致的真实中心波长", effect: "控制模拟光谱的内插采样位置", risk: "缺省假波长可让匹配得到错误但表面平滑的参数图" },
      { name: "solar_zenith/view_zenith/relative_azimuth", role: "定义冠层双向反射几何", guidance: "使用采集时刻与姿态计算值，角度单位为度", effect: "改变模拟冠层反射形状和幅值", risk: "角度定义或符号错误会形成系统偏差" },
    ],
    resultInterpretation: ["LAI 与 Cab 只会落在 LUT 离散节点；大片等值台阶是网格量化而非真实突变。", "命中 0.2/6.0 或 10/70 边界表示参数可能超出 LUT，不能当作可靠极值。"],
    applicable: ["有可靠反射率、波长和观测几何的冠层参数初步物理反演。", "用于教学说明前向模型、LUT 与最近邻反演关系。"],
    notApplicable: ["输入未经反射率校正，或场景不符合均匀冠层和平面叶片模型假设。", "要求高精度连续参数、联合反演土壤/含水等变量或不确定性后验。"],
    risks: ["土壤、叶倾角、水分等固定参数与现场不符会将误差转移到 LAI/Cab。", "LAI 与 Cab 光谱效应可互相补偿，单个最近邻解不代表唯一真值。"],
    upstream: ["反射率和波长标定、观测几何整理及坏波段剔除。"],
    downstream: ["边界命中检查、样地验证和地块级参数统计。"],
    demoFocus: ["展示 12×8 LUT 网格及某像元的最小光谱角匹配。", "指出离散台阶、边界命中和固定参数造成的限制。"],
  },
  {
    id: "34_svm_rf_classify",
    purpose: "用标注像素训练 SVM 或随机森林，得到整幅分类图。",
    why: "有足够标注时，这是产线最稳的传统分类器。",
    formula: "SVM：核空间最大间隔；RF：多棵树投票。gt=0 为背景忽略",
    steps: ["抽出 gt>0 的像元", "划分训练/测试", "拟合 SVM 或 RF", "预测整图，报 OA/AA/Kappa"],
    viz: { kind: "feature_space", caption: "二维示意：SVM 找间隔最大的界，RF 用一连串矩形把空间切开。" },
    inputs: [
      { name: "file", meaning: "立方体" },
      { name: "file2", meaning: "必填标签" },
      { name: "model", meaning: "svm（默认）或 rf" },
    ],
    outputs: [{ name: "pred_map.tif", meaning: "分类图；背景也会被分成某类" }],
    industryGap: "随机划分空间泄漏；无网格搜索。RF 对尺度不敏感，SVM 常需先标准化。",
    checks: ["OA 和 AA 在类别极不均衡时为何会分道？"],
    summary: {
      definition: "用标签像元训练 SVM 或随机森林，并将分类器应用到整幅光谱立方体。",
      value: "提供稳健传统监督分类基线及 OA、AA、Kappa 三类测试指标。",
      keyInput: "同尺寸立方体、0 为忽略的标签图，以及模型与测试比例参数。",
      keyOutput: "整图 pred_map.tif、类别列表、训练/测试样本数和 OA/AA/Kappa。",
      keyLimit: "当前像元随机划分存在空间泄漏，且 SVM 未在实现内标准化或调参。",
    },
    background: ["SVM 在核空间寻找最大间隔边界，RF 通过多棵随机树投票。", "OA 是总体正确率，AA 是各真实类别召回率均值，Kappa 扣除随机一致部分。"],
    prerequisites: ["标签编码须为正整数类别、0 为背景忽略，并与影像逐像元对齐。", "正式评估应按地块/空间块留出；SVM 输入需在训练统计下完成尺度处理。"],
    parameterNotes: [
      { name: "model / kernel", role: "选择 RF 或 SVM 及其核", guidance: "默认 SVM-RBF；高维小样本需通过空间验证比较 RF", effect: "改变决策边界复杂度和尺度敏感性", risk: "当前无 C、gamma 网格搜索，默认值不保证最优" },
      { name: "test_size / n_estimators", role: "控制测试比例或 RF 树数", guidance: "测试比例默认 0.3；RF 默认 200 棵", effect: "影响指标方差、训练量和 RF 稳定性", risk: "增加树数不能修复标签偏差或空间泄漏" },
    ],
    resultInterpretation: ["类别不均衡时 OA 可能被大类主导，应同时查看 AA、Kappa 和混淆矩阵。", "整图包括原标签背景区域也会被强制分为某个已知类别，不能把它视为有效性掩膜。"],
    applicable: ["具有代表性多类别标注的地物或作物类型像素分类。", "需要可重复传统基线并比较 SVM 与 RF 的任务。"],
    notApplicable: ["标注只来自单一小地块却要求跨区域泛化。", "需要未知类拒绝、概率校准或对象级边界质量评估。"],
    risks: ["相邻像元分到训练和测试会显著高估 OA/AA/Kappa。", "类别编号与名称映射错误会让指标正确但业务语义错误。"],
    upstream: ["反射率/特征预处理、标签质控与空间独立划分。"],
    downstream: ["混淆矩阵复核、分类后处理和地块类别面积占比统计。"],
    demoFocus: ["用不均衡样本解释 OA、AA、Kappa 各自回答的问题。", "对比像元随机与地块留出的指标，并提醒背景会被强制分类。"],
  },
  {
    id: "35_spectral_matching",
    purpose: "把每个像元光谱与端元库比角度（SAM）或信息散度（SID）。",
    why: "有光谱库、标注很少时，不必训练分类器。",
    formula: "θ = arccos( x·e / (‖x‖‖e‖) )；分类 = 最小角端元",
    formulaNote: "SAM 对亮度缩放不敏感，对形状敏感。",
    steps: ["读端元 CSV", "逐像元算角/SID", "argmin 得类别", "同时输出最小角图"],
    viz: { kind: "sam", caption: "拖动夹角：角度越小越像该端元。亮度变长不改变夹角。" },
    inputs: [
      { name: "file", meaning: "立方体" },
      { name: "file2", meaning: "必填端元 CSV" },
      { name: "method", meaning: "sam 或 sid" },
    ],
    outputs: [
      { name: "sam_class.tif", meaning: "硬分类（每像素必归一类）" },
      { name: "angle.tif", meaning: "最小光谱角" },
    ],
    industryGap: "无拒绝阈值。与解混的差别：这里给类别，#41 给比例。",
    checks: ["同一形状光谱整体×2，SAM 角变不变？"],
    summary: {
      definition: "将像元与端元库逐一计算 SAM 光谱角或 SID 对称信息散度并取最小值。",
      value: "无需训练标签即可依据已知端元形状完成整图硬分类和匹配质量制图。",
      keyInput: "与影像波段数、顺序和尺度一致的端元 CSV。",
      keyOutput: "1 起类别图和最小 SAM 角或 SID 距离图。",
      keyLimit: "当前没有拒绝阈值，每个像元都会被归入某个端元类别。",
    },
    background: ["SAM 比较向量夹角，对正比例亮度缩放不敏感。", "SID 把非负光谱归一化为概率分布，计算双向 KL 散度，对形状比例差异敏感。"],
    prerequisites: ["端元与影像必须具有相同波段数、波长顺序和预处理链。", "SID 输入应为非负物理光谱；端元需代表场景中的纯净类别。"],
    parameterNotes: [
      { name: "method", role: "选择 sam 或 sid 距离", guidance: "亮度尺度变化明显时先试 SAM；关注细微相对谱形时对照 SID", effect: "改变距离定义与分数尺度", risk: "SAM 角和 SID 数值不可共用同一阈值" },
      { name: "file2 端元 CSV", role: "定义候选类别及其光谱", guidance: "逐列一个端元，逐行对应影像波段", effect: "端元数量决定输出类别范围", risk: "波长错序或域差异会使全图系统性误配" },
    ],
    resultInterpretation: ["最小角/散度越小仅表示在给定端元集合中更相似，不代表绝对可信。", "高距离区域应视为低置信或未知候选，但当前类别图仍会强制赋类。"],
    applicable: ["有质量受控光谱库、标注很少且端元较纯的材料或地物匹配。", "需要比较 SAM 与 SID 光谱形状判别差异。"],
    notApplicable: ["混合像元需要端元比例而不是唯一类别。", "端元与影像波长、分辨率或反射率尺度无法对齐。"],
    risks: ["阴影或噪声虽可能保留方向，却会让类别图产生假稳定。", "SID 对负值/近零值依赖数值截断，经过中心化或 SNV 的光谱不合适。"],
    upstream: ["端元采集与重采样、反射率一致化及坏波段同步剔除。"],
    downstream: ["基于距离的人工拒绝审查、类别制图或转入 FCLS 解混。"],
    demoFocus: ["演示光谱整体乘 2 时 SAM 不变，以及 SID 与 SAM 分数不可互换。", "显示高最小距离像元仍被硬分类这一限制。"],
  },
  {
    id: "36_cnn1d_classify",
    purpose: "一维卷积沿着光谱提取局部吸收特征，再全连接分类。",
    why: "光谱相邻波段有结构（红边、吸收谷），卷积能学到，不必手写指数。",
    formula: "Hu 2015：Conv1d → ReLU → Pool → FC → Softmax",
    formulaNote: "标题含 RNN，当前实现只有 1D-CNN。默认仅 8 个 epoch。",
    steps: ["标注像元 Z-score", "切光谱为 1 通道序列", "短训 CNN", "整图推理"],
    viz: {
      kind: "cnn_arch",
      caption: "卷积核在光谱上滑动，捕捉局部峰谷。",
      layers: [
        { name: "光谱向量", note: "B 个波段" },
        { name: "Conv1d ×20", note: "局部吸收" },
        { name: "MaxPool", note: "降采样" },
        { name: "FC → 类别", note: "Hu 2015" },
      ],
    },
    inputs: [
      { name: "file / file2", meaning: "立方体 + 标签" },
      { name: "epochs", meaning: "默认 8，教学用" },
    ],
    outputs: [{ name: "pred_map.tif", meaning: "分类图与 OA/AA/Kappa" }],
    industryGap: "轮数很少；无 RNN。真正上线需要早停、增强和空间划分验证。",
    checks: ["1D-CNN 相对 SAM 多学到了什么？"],
    summary: {
      definition: "采用 Hu 2015 风格 1D-CNN 沿光谱维学习局部峰谷特征并监督分类。",
      value: "不手工设计指数即可从标注样本学习吸收形状与相邻波段组合。",
      keyInput: "同尺寸立方体和正整数标签图，以及训练轮数与测试比例。",
      keyOutput: "整图 pred_map.tif 和测试集 OA、AA、Kappa 等训练结果。",
      keyLimit: "当前只有 1D-CNN、没有 RNN，默认 8 轮且按像元随机划分。",
    },
    background: ["卷积核沿连续波段滑动，学习红边、吸收谷等局部谱形；池化后由全连接层分类。", "模型使用标注像元训练并对整图逐像元推理，不利用空间邻域。"],
    prerequisites: ["所有样本必须共享稳定波长顺序，标签与影像对齐且每类有足够样本。", "评估前按地块或空间块拆分；跨景推理需固定训练时的标准化统计和波段配置。"],
    parameterNotes: [
      { name: "epochs", role: "控制训练遍数", guidance: "默认 8 仅用于演示；正式训练用独立验证监控而非盲目增加", effect: "影响拟合程度和运行时间", risk: "轮数过多会过拟合，过少则指标不稳定" },
      { name: "test_size", role: "设置随机测试像元比例", guidance: "默认 0.3 仅作运行反馈，正式报告改用空间留出", effect: "改变训练样本量和指标方差", risk: "随机像元切分会高估泛化能力" },
    ],
    resultInterpretation: ["OA/AA/Kappa 仅描述当前随机测试像元，不能代表跨地块或跨时相性能。", "分类图空间碎片是逐像元模型的预期表现，可后处理但不能用平滑掩盖模型错误。"],
    applicable: ["有较多标签、波长密集且局部吸收结构有判别力的光谱分类。", "作为传统模型与空谱模型之间的深度光谱基线。"],
    notApplicable: ["标注极少、类别跨景漂移明显或需要显式空间纹理。", "把标题中的 RNN 当作已实现分支。"],
    risks: ["相邻像元泄漏会使深度模型指标虚高。", "波段顺序、数量或标准化改变会使已训练权重不可直接复用。"],
    upstream: ["标签质控、空间划分、波段一致化和训练集标准化。"],
    downstream: ["独立场景验证、误差分析、分类平滑与地块面积统计。"],
    demoFocus: ["展示 1D 卷积核如何响应局部吸收峰谷。", "明确当前无 RNN，并对比随机像元与空间留出指标。"],
  },
  {
    id: "37_cnn3d_classify",
    purpose: "同时用邻域空间和光谱：HybridSN（3D 卷积 + 2D 卷积）。",
    why: "同类地物空间成片，只看单像素光谱会碎。",
    formula: "PCA→P×P×C patch → Conv3d 空谱 → Conv2d → 分类",
    steps: ["整图 PCA", "切奇数 patch", "短训 HybridSN", "整图滑窗预测"],
    viz: {
      kind: "cnn_arch",
      caption: "每个像素带上周围立方体，3D 核同时看空间和光谱。",
      layers: [
        { name: "Cube", note: "H×W×B" },
        { name: "PCA", note: "默认 8 维" },
        { name: "P×P×C patch", note: "默认 P=5" },
        { name: "Conv3d + Conv2d", note: "HybridSN" },
      ],
    },
    inputs: [
      { name: "file / file2", meaning: "立方体 + 标签" },
      { name: "patch_size / pca_components", meaning: "默认 5 / 8" },
    ],
    outputs: [{ name: "pred_map.tif", meaning: "空谱分类图" }],
    industryGap: "相邻 patch 强相关，OA 虚高。这是论文常用骨架的缩小版。",
    checks: ["为何先 PCA 再 3D 卷积？"],
    summary: {
      definition: "以 PCA 降维后的邻域立方体训练缩小版 HybridSN，融合 3D 空谱卷积与 2D 空间卷积。",
      value: "利用地物成片与光谱结构减少单像元分类的椒盐现象。",
      keyInput: "同尺寸立方体和标签图，以及奇数 patch_size、PCA 维数和训练参数。",
      keyOutput: "空谱分类 pred_map.tif 及 OA、AA、Kappa、设备和降维信息。",
      keyLimit: "重叠 patch 高度相关，当前随机样本划分会产生严重空间泄漏。",
    },
    background: ["3D 卷积同时沿空间和光谱维提特征，后续 2D 卷积聚合空间模式。", "PCA 先压缩波段以控制 3D 卷积计算量；本实现是 HybridSN 教学缩小版。"],
    prerequisites: ["patch_size 必须为不小于 3 的奇数，标签与影像严格对齐。", "按互不相邻的地块或空间块划分训练与测试，避免重叠邻域跨集合。"],
    parameterNotes: [
      { name: "patch_size", role: "定义中心像元的空间上下文", guidance: "默认 5；结合 GSD 与目标斑块尺度选奇数", effect: "越大使用更广空间纹理", risk: "过大混入边界和邻类，并扩大泄漏范围" },
      { name: "pca_components", role: "控制进入网络的光谱维数", guidance: "默认 8，须小于有效波段和样本约束", effect: "平衡信息保留、显存和模型规模", risk: "过少丢判别谱形，过多增加噪声与计算" },
      { name: "epochs / batch_size", role: "控制训练量与批处理", guidance: "默认 8/64 仅供教学，按独立验证和设备资源调整", effect: "影响收敛、速度和显存", risk: "短训结果波动，长训可能过拟合" },
    ],
    resultInterpretation: ["OA/AA/Kappa 若来自重叠随机 patch，只能视为内部演示指标。", "边界更平滑不等于类别更正确，应按对象边界和独立地块检查。"],
    applicable: ["类别具有稳定空间纹理且有足够标注的高光谱空谱分类。", "需要演示 HybridSN 中 PCA、3D 卷积和 2D 卷积的连接。"],
    notApplicable: ["目标小于 patch 或类别边界极细，邻域会混合多个类别。", "标签稀少且无法进行空间独立验证。"],
    risks: ["先对整图 PCA 拟合再拆分也可能把测试分布信息带入特征变换。", "边缘填充和滑窗推理可能形成边界伪影。"],
    upstream: ["波段清洗、标签质控、空间分块与训练侧 PCA 设计。"],
    downstream: ["独立区域复核、对象级评价、后处理和地块统计。"],
    demoFocus: ["可视化 P×P×C patch 穿过 3D/2D 卷积的尺寸变化。", "用重叠 patch 示意空间泄漏为何使 OA 虚高。"],
  },
  {
    id: "38_transformer_classify",
    purpose: "把相邻波段编成 token，用注意力建模长程光谱依赖。",
    why: "红边和近红外相隔较远，卷积局部窗口未必够。",
    formula: "SpectralFormer：group=3 滑窗 token → 两层 Transformer + 残差",
    formulaNote: "标题含 GCN，当前没有图卷积分支。",
    steps: ["光谱滑窗成 token", "两层 Encoder", "均值池化分类"],
    viz: {
      kind: "cnn_arch",
      caption: "每个 token 是一小段相邻波段；注意力让远处波段互相看见。",
      layers: [
        { name: "光谱", note: "B 波段" },
        { name: "滑窗 token", note: "group=3" },
        { name: "Transformer ×2", note: "d=64" },
        { name: "分类头", note: "均值池化" },
      ],
    },
    inputs: [{ name: "file / file2", meaning: "立方体 + 标签" }, { name: "epochs", meaning: "默认 6" }],
    outputs: [{ name: "pred_map.tif", meaning: "分类图" }],
    industryGap: "无 GCN、无预训练。产线仍以指数+RF 更常见。",
    checks: ["注意力相对 1D 卷积的优势在长距离依赖，如何用红边—近红外理解？"],
    summary: {
      definition: "用 group=3 的相邻波段 token 和两层 Transformer 编码器实现 SpectralFormer 风格分类。",
      value: "让远距离波段通过注意力直接交互，学习跨吸收区的长程光谱关系。",
      keyInput: "波长顺序一致的立方体、标签图及训练轮数和测试比例。",
      keyOutput: "整图 pred_map.tif 和测试集分类指标。",
      keyLimit: "当前没有 GCN、空间分支或预训练，默认仅训练 6 轮。",
    },
    background: ["每个 token 表示连续 3 个波段的局部片段，注意力再建立 token 间全局依赖。", "本实现用两层、d=64 的编码器和均值池化分类，属于小型 SpectralFormer 骨架。"],
    prerequisites: ["波段数量、顺序和预处理必须稳定，标签与影像同像元对齐。", "应按空间块/地块留出评估，并确保每类样本足以训练注意力模型。"],
    parameterNotes: [
      { name: "epochs", role: "控制 Transformer 训练轮数", guidance: "默认 6 只验证流程；根据独立验证曲线选择", effect: "影响收敛和过拟合", risk: "少轮可能欠拟合，多轮在小样本上迅速记忆" },
      { name: "test_size", role: "控制随机测试像元比例", guidance: "默认 0.3 不用于正式泛化结论", effect: "改变训练量与指标方差", risk: "像元随机划分保留空间泄漏" },
    ],
    resultInterpretation: ["注意力建模长程依赖并不保证优于 CNN，需在相同空间独立划分上比较。", "输出是逐像元已知类硬分类；没有 GCN 产生的图结构或未知类拒绝。"],
    applicable: ["波段较密、远距离谱段组合具有判别力且标注较充足的光谱分类。", "教学对比 1D 局部卷积与全局注意力。"],
    notApplicable: ["声称使用图卷积、空间邻域或预训练迁移。", "极少样本且无正则化/外部验证，却要求稳定生产性能。"],
    risks: ["模型参数相对样本过多会过拟合，随机划分进一步掩盖问题。", "跨传感器波段变化会破坏 token 位置语义。"],
    upstream: ["波段对齐、标签质控、空间独立划分和训练集标准化。"],
    downstream: ["与 RF/1D-CNN 同划分对照、独立场景验证和地块统计。"],
    demoFocus: ["用红边 token 与近红外 token 的注意力联系解释长程依赖。", "明确标题中的 GCN 未实现，展示短训指标的适用边界。"],
  },
  {
    id: "39_few_shot_classify",
    purpose: "每类只取几个支持样本当原型，其余像元按 SAM 最近原型分类。",
    why: "田间标注极贵。少样本比硬训 CNN 更稳。",
    formula: "proto_k = mean(支持集_k)；ŷ = argmin SAM(x, proto)",
    steps: ["每类抽 shots 个支持样本", "求均值原型", "全图按 SAM 归类", "在 query 上算 OA"],
    viz: { kind: "fewshot", caption: "每类 5 个点收成一个原型中心，查询点找最近中心。" },
    inputs: [
      { name: "file / file2", meaning: "立方体 + 标签" },
      { name: "shots", meaning: "每类支持数，默认 5" },
    ],
    outputs: [{ name: "pred_map.tif", meaning: "少样本分类图" }],
    industryGap: "不是可学习嵌入，也不是源域预训练迁移。",
    checks: ["某类像素少于 shots 时代码会怎样？"],
    summary: {
      definition: "每类随机抽取最多 shots 个支持像元求均值原型，再按 SAM 最近原型分类。",
      value: "在标注昂贵时提供无需梯度训练的可解释少样本光谱基线。",
      keyInput: "立方体、正整数标签图和每类支持样本数 shots。",
      keyOutput: "整图分类图，以及有查询样本时的 OA、AA、Kappa 和支持/查询数量。",
      keyLimit: "这不是可学习原型网络或迁移学习；原型只是原始光谱均值。",
    },
    background: ["支持集决定每类均值光谱，查询像元与各原型按 SAM 夹角比较。", "随机种子固定为 42；某类少于 shots 时使用该类全部像元。"],
    prerequisites: ["每类至少有一个有效标签像元，标签 0 被忽略且图像需严格对齐。", "支持点应覆盖类内变异并与独立查询区空间分离。"],
    parameterNotes: [
      { name: "shots", role: "限定每类用于原型的支持样本数", guidance: "默认 5；结合最小类别样本量和类内异质性设置正整数", effect: "增大通常让均值原型更稳定", risk: "小类会取尽全部样本，导致没有该类独立 query 可评估" },
    ],
    resultInterpretation: ["指标仅在未被选为支持集的已标注 query 像元上计算；无 query 时不会返回该组指标。", "整图所有像元都被分到已有原型，远离全部原型的未知地物不会被拒绝。"],
    applicable: ["每类只有少量可信标注、光谱形状较稳定的快速基线。", "需要展示支持集、原型和查询集概念。"],
    notApplicable: ["宣称进行了源域预训练、微调或可学习嵌入。", "类内多模态明显，仅用一个均值原型无法代表。"],
    risks: ["支持样本随机选择会造成结果方差，单次固定随机种子不能代表稳健性。", "相邻支持与查询像元仍会造成空间泄漏和指标虚高。"],
    upstream: ["标签质控、光谱一致化和空间独立支持/查询设计。"],
    downstream: ["重复抽样稳定性评估、端元库完善或转入监督模型。"],
    demoFocus: ["展示某类样本少于 shots 时实际支持数及 query 缺失。", "明确原始光谱均值原型与可学习原型网络的区别。"],
  },
  {
    id: "40_detect_segment",
    purpose: "用 ACE 探测「像目标光谱」的像元，再矢量化成斑块。",
    why: "病斑、胁迫区往往是稀疏目标，不是整幅分类问题。",
    formula: "ACE = [(x−μ)ᵀΣ⁻¹d] / sqrt(…)，d = 目标 − 背景均值",
    formulaNote: "目标光谱由低 NDVI 百分位种子估计（教学假设：胁迫更绿不茂）。",
    steps: ["低 NDVI 估目标光谱", "算 ACE 得分", "百分位阈值", "连通域滤小斑并转多边形"],
    viz: { kind: "ace", caption: "背景成一团椭圆，目标方向上的投影越大越像目标。" },
    inputs: [
      { name: "file", meaning: "反射率立方体" },
      { name: "percentile / ace_percentile", meaning: "种子 20%、检测 90%" },
    ],
    outputs: [
      { name: "score.tif / mask.tif", meaning: "探测得分与二值掩膜" },
      { name: "polygons.geojson", meaning: "斑块矢量" },
    ],
    industryGap: "不是 U-Net/YOLO。已知实验室目标光谱时应替换自动种子。",
    checks: ["ACE 与 SAM 都用光谱方向，背景协方差多带来了什么？"],
    summary: {
      definition: "以低 NDVI 像元均值自动构造目标光谱，用 ACE 打分并按百分位阈值矢量化斑块。",
      value: "把稀疏胁迫候选从连续光谱得分转为栅格掩膜和可交付多边形。",
      keyInput: "反射率立方体、红/近红外索引、种子与 ACE 百分位及最小斑块像元数。",
      keyOutput: "ACE 得分、二值掩膜、候选斑块 GeoJSON 和对象数量。",
      keyLimit: "目标光谱来自“低 NDVI≈胁迫”的教学假设，不是语义分割或目标检测网络。",
    },
    background: ["ACE 在背景协方差白化空间中衡量像元沿目标方向的相似度，比 SAM 多利用背景统计。", "本实现先取低 NDVI 百分位像元均值，再将 ACE 高分百分位作为检测结果。"],
    prerequisites: ["输入应为反射率，并正确映射 RED/NIR 波段；先排除 NoData、阴影和非植被背景。", "目标必须符合低 NDVI 种子假设，否则应使用已知目标光谱而非当前自动种子。"],
    parameterNotes: [
      { name: "percentile", role: "选择低 NDVI 目标种子", guidance: "默认 20；按场景植被掩膜后的 NDVI 分布校准", effect: "决定自动目标光谱的组成", risk: "过低样本不足，过高会混入正常植被和背景" },
      { name: "ace_percentile / min_pixels", role: "把相对 ACE 得分转为斑块", guidance: "默认 90/4；结合验证点、GSD 与最小目标面积调整", effect: "百分位越高候选越少，min_pixels 越大保留斑块越大", risk: "阈值是本景相对排名，不能跨景当固定物理标准" },
      { name: "red_band / nir_band", role: "构造低 NDVI 种子", guidance: "按实际波长选择约 660/800 nm 通道", effect: "改变目标端元估计", risk: "索引错误会让 ACE 探测错误目标" },
    ],
    resultInterpretation: ["score.tif 是相对目标相似度，mask 仅为本景高百分位候选；高分不等于已确认病害。", "GeoJSON 的 area_pixels 是像元数，不是平方米；需依据投影和 GSD 换算。"],
    applicable: ["目标稀疏、光谱与背景不同且低 NDVI 可作为合理先验的候选筛查。", "已知反射率目标光谱并可据此替换教学种子的 ACE 应用。"],
    notApplicable: ["需要 U-Net/YOLO 语义类别、实例边界或训练检测精度报告。", "目标并不表现为低 NDVI，或背景高度非平稳且无区域化建模。"],
    risks: ["阴影、裸土、NoData 会污染自动目标和背景协方差。", "百分位阈值固定候选比例，场景无目标时仍可能产生假警。"],
    upstream: ["反射率处理、植被/有效像元掩膜、波段核验与目标先验确认。"],
    downstream: ["现场核查、阈值校准、斑块面积换算和地块告警汇总。"],
    demoFocus: ["展示低 NDVI 种子如何形成目标光谱并影响 ACE 得分。", "调节相对百分位说明候选数量变化及“无目标也会出高分”的风险。"],
  },
  {
    id: "41_unmixing",
    purpose: "把混合像元拆成各端元的面积比例（丰度），和为 1、非负。",
    why: "一个 1 m 像元里可能既有作物又有土壤。硬分类太武断。",
    formula: "x ≈ E a，a≥0，1ᵀa=1（FCLS 增广 NNLS）",
    steps: ["读端元矩阵 E", "逐像元非负最小二乘 + 和约束", "输出 K 张丰度图"],
    viz: { kind: "unmix", caption: "拖动混合比例：像元光谱是两端元的加权平均。" },
    inputs: [
      { name: "file", meaning: "混合立方体" },
      { name: "file2", meaning: "必填端元 CSV" },
      { name: "delta", meaning: "和约束强度，默认 10" },
    ],
    outputs: [{ name: "abundance.tif", meaning: "K 波段丰度，每像素和应≈1" }],
    industryGap: "端元需已知，无 VCA/N-FINDR。线性混合忽略多次散射。",
    checks: ["SAM 给类别、FCLS 给比例：GSD 变粗时哪个更诚实？"],
    summary: {
      definition: "用增广非负最小二乘近似 FCLS，将像元表示为非负且和约束的端元线性组合。",
      value: "对混合像元输出每个端元的连续丰度，而非强制唯一类别。",
      keyInput: "反射率立方体、同波段顺序端元 CSV 和和约束强度 delta。",
      keyOutput: "K 波段 abundance.tif，每波段对应一个端元丰度。",
      keyLimit: "端元必须预先给定，当前不做 VCA/N-FINDR，线性模型不表示多次散射。",
    },
    background: ["线性混合模型假设像元光谱是端元反射率按面积比例加权。", "实现通过增广 NNLS 强制非负并以 delta 近似丰度和为 1。"],
    prerequisites: ["端元与影像必须具有相同波段数、顺序、反射率尺度和坏波段掩膜。", "端元集合应覆盖主要材料且彼此可分，NoData 像元需预先排除。"],
    parameterNotes: [
      { name: "delta", role: "控制丰度和为 1 的增广约束强度", guidance: "默认 10；结合重构误差与丰度和偏差共同检查", effect: "越大通常越强调和约束", risk: "过大可能牺牲光谱拟合，过小使丰度和明显偏离 1" },
      { name: "file2 端元 CSV", role: "定义解混基底与输出波段语义", guidance: "逐列端元、逐行波段，并保存列名到业务映射", effect: "端元数决定丰度图波段数", risk: "遗漏端元会把其贡献错误分配给已有端元" },
    ],
    resultInterpretation: ["每个像元 K 个丰度应非负且总和约为 1；同时还应检查光谱重构残差。", "丰度表示线性模型下的相对贡献，不自动等于真实面积比例或质量分数。"],
    applicable: ["空间分辨率较粗、像元由少量已知材料近似线性混合的场景。", "需要作物/土壤等连续覆盖比例而非硬分类。"],
    notApplicable: ["端元未知却要求自动发现，或存在明显冠层多次散射和强非线性混合。", "端元波长无法与影像严格对齐。"],
    risks: ["高度相似端元导致丰度不稳定，即使总和满足约束也可能不可辨识。", "当前输出不含重构误差图，不能只凭丰度和判断拟合质量。"],
    upstream: ["端元采集/重采样、反射率一致化和有效波段筛选。"],
    downstream: ["丰度和及重构误差质控、覆盖比例统计和地块汇总。"],
    demoFocus: ["对比 SAM 的唯一类别与 FCLS 的连续比例。", "调节 delta 同时观察丰度和偏差与光谱拟合权衡。"],
  },
  {
    id: "42_anomaly_detect",
    purpose: "在无标签情况下找出「不像周围」的像元（RX / 局部 RX）。",
    why: "未知目标、污染点、设备异常都可能表现为光谱离群。",
    formula: "D_RX = (x−μ)ᵀ Σ⁻¹ (x−μ)（马氏距离²）；LRX 用外窗估背景、挖内窗",
    steps: ["全局或滑窗估 μ、Σ", "算 RX 得分", "高百分位阈值", "滤小斑"],
    viz: { kind: "rx", caption: "椭圆内是背景，椭圆外的点被判为异常。拖动阈值看虚警变化。" },
    inputs: [
      { name: "file", meaning: "≥2 波段立方体" },
      { name: "method", meaning: "默认 lrx；可 rx" },
    ],
    outputs: [{ name: "score.tif / mask.tif", meaning: "异常得分与掩膜" }],
    industryGap: "背景非高斯（大田纹理）会虚警。无 CFAR 虚警率控制。",
    checks: ["为何要挖去内窗？目标污染背景协方差会怎样？"],
    summary: {
      definition: "用全局 RX 或挖空内窗的局部 RX 马氏距离识别偏离背景统计的光谱像元。",
      value: "在无标签、目标类别未知时生成异常得分与候选掩膜。",
      keyInput: "至少两波段的有效立方体，以及方法、窗口、百分位和最小斑块参数。",
      keyOutput: "连续 anomaly_score.tif、二值 anomaly_mask.tif 和异常像元数。",
      keyLimit: "百分位阈值只表示本景相对异常，且背景非高斯或非平稳时虚警会增加。",
    },
    background: ["RX 是相对背景均值和协方差的马氏距离平方，考虑波段相关性。", "LRX 对每个像元用外窗估局部背景，并挖去内窗减少目标污染。"],
    prerequisites: ["先掩膜 NoData、边界填充值、云影和已知无效区域，至少保留 2 个有效波段。", "局部窗口应包含足够背景样本，且尺度大于目标、又小于背景变化尺度。"],
    parameterNotes: [
      { name: "method", role: "选择全局 RX 或局部 LRX", guidance: "默认 lrx；背景较均匀可用 rx，缓慢变化背景优先 lrx", effect: "改变背景统计范围与计算量", risk: "局部样本不足会使协方差不稳定" },
      { name: "win / inner", role: "定义 LRX 外窗和目标保护内窗", guidance: "默认 7/3；外窗大于内窗并结合目标像素尺寸设置", effect: "控制背景局部性与目标污染", risk: "内窗过小污染背景，过大又减少有效背景样本" },
      { name: "percentile / min_pixels", role: "将得分转为候选斑块", guidance: "默认 95/2，使用验证样本校准", effect: "高百分位减少候选，小斑阈值抑制孤点", risk: "相对阈值不提供恒虚警率，场景无异常仍会选出高分尾部" },
    ],
    resultInterpretation: ["得分越高表示相对所估背景越离群，不说明异常属于何种材料或故障。", "mask 是按本景得分分位数截断后的候选，跨景比较应使用分布校准而非同一数值阈值。"],
    applicable: ["未知稀疏目标、污染点或传感器异常的无监督初筛。", "背景可由全局或局部高斯协方差近似的场景。"],
    notApplicable: ["需要已知目标类别识别时，应使用 ACE/匹配或监督模型。", "背景极度多模态、异常占比高或窗口内样本不足。"],
    risks: ["高维小窗口协方差病态会导致不稳定高分。", "纹理边界、阴影和 NoData 常成为统计离群而非业务异常。"],
    upstream: ["有效像元掩膜、坏波段剔除和必要的降维/背景分区。"],
    downstream: ["候选复核、目标匹配、现场取样和斑块统计。"],
    demoFocus: ["对比全局 RX 与 LRX 在缓变背景上的得分差异。", "改变 inner/percentile 展示目标污染与相对阈值的虚警权衡。"],
  },
  {
    id: "43_change_detect",
    purpose: "比较已配准的两期立方体，找出统计意义上的变化像元。",
    why: "物候、收割、建设都会改光谱。IR-MAD 对线性辐射差异较稳健。",
    formula: "IR-MAD：迭代加权典型相关，χ² 大者为变化",
    steps: ["两期 z-score", "迭代 CCA/MAD", "χ² 图", "百分位阈值掩膜"],
    viz: { kind: "change", caption: "两期相同则点落在 1:1 线附近；变化点偏离。" },
    inputs: [
      { name: "file", meaning: "T1 立方体" },
      { name: "file2", meaning: "必填 T2 立方体" },
    ],
    outputs: [{ name: "chi2.tif / mask.tif", meaning: "变化强度与掩膜" }],
    industryGap: "未配准会把几何误差当变化。作物长大也是「真变化」。",
    checks: ["为何变化检测前常要先配准甚至 BRDF 归一？"],
    summary: {
      definition: "用 IR-MAD 迭代加权典型相关提取两期影像间的 MAD 差异并形成 χ² 变化强度。",
      value: "对线性辐射差异较稳健地定位多波段统计变化，而无需变化标签。",
      keyInput: "同尺寸、同波段语义且精确配准的 T1/T2 立方体。",
      keyOutput: "变化幅度、χ² 强度、百分位二值掩膜及迭代元数据。",
      keyLimit: "检测的是统计差异而非变化原因；配准、物候和 BRDF 差异都会产生响应。",
    },
    background: ["MAD 通过典型相关寻找两期最相似线性组合，再以差分构成变化分量。", "IR-MAD 迭代降低疑似变化像元权重，使不变背景统计逐步稳定。"],
    prerequisites: ["两期影像必须同网格、同尺寸、同波段顺序与可比反射率处理。", "先做亚像元配准、云影/NoData 联合掩膜，并尽量归一化观测几何和物候差异。"],
    parameterNotes: [
      { name: "max_iter", role: "限制 IR-MAD 重加权迭代次数", guidance: "默认 15；结合收敛元数据与运行时间检查", effect: "影响不变背景统计的稳定程度", risk: "过少未收敛，增加次数也不能修复错配或波段不一致" },
      { name: "percentile", role: "将 χ² 相对强度转为变化掩膜", guidance: "默认 90；依据稳定区和验证样本校准", effect: "越高标出的变化越少", risk: "每景相对阈值会固定尾部比例，不能解释为统一显著性标准" },
    ],
    resultInterpretation: ["χ² 越高表示两期统计差异越强；mask 只是本对影像的高分位候选。", "真实作物生长、收割与灾害都会被视为变化，需叠加业务信息区分原因。"],
    applicable: ["同传感器或已严格归一化的多时相土地覆盖、收割和灾害变化筛查。", "希望降低简单波段相减对线性亮度差异敏感性的任务。"],
    notApplicable: ["两期未配准、波段定义不同或有效像元范围不一致。", "需要直接输出变化类别、方向或因果解释。"],
    risks: ["亚像元错位会在道路、田埂和冠层边缘形成大量假变化。", "NoData 和云影若未做交集掩膜会支配 χ² 尾部。"],
    upstream: ["反射率一致化、精配准、BRDF/光照归一和联合有效掩膜。"],
    downstream: ["变化对象化、类别判读、现场核查和地块变化面积统计。"],
    demoFocus: ["用错位半个像元的边缘示例展示几何假变化。", "对比连续 χ² 图与相对百分位 mask，明确它不输出变化原因。"],
  },
  {
    id: "44_postprocess_smooth",
    purpose: "众数滤波 + 小斑剔除，让分类图可制图。",
    why: "像素分类常有椒盐噪声，领导看图受不了。",
    formula: "窗口内众数替换中心；连通域面积 < min_pixels 则填邻域众数",
    steps: ["众数滤波", "逐类连通域", "小斑替换", "输出平滑标签"],
    viz: { kind: "majority", caption: "孤立杂点被周围类别吞掉。真实小病斑也可能被抹掉。" },
    inputs: [
      { name: "file", meaning: "单波段分类图" },
      { name: "min_pixels / window", meaning: "默认 4 / 3" },
    ],
    outputs: [{ name: "labels_smooth.tif", meaning: "后处理分类图" }],
    industryGap: "探测产品慎用。更完整的是 MRF/CRF。",
    checks: ["min_pixels 过大时会丢掉什么真实地物？"],
    summary: {
      definition: "先做窗口众数滤波，再逐类删除小连通斑并以邻域众数填充。",
      value: "降低像素分类的椒盐噪声，生成更连续的制图标签。",
      keyInput: "单波段离散分类图，以及窗口和最小斑块像元阈值。",
      keyOutput: "labels_smooth.tif、变化像元数和处理后类别列表。",
      keyLimit: "平滑会改动预测并可能抹掉真实小目标，不提升原始分类证据。",
    },
    background: ["众数滤波用邻域最常见类别替换中心像元，偏好空间连续区域。", "小斑剔除对每类连通域计数，再用膨胀边界的众数填充。"],
    prerequisites: ["输入必须是单波段整数标签图，保留并明确背景/NoData 类别编码。", "根据 GSD 将业务最小制图面积换算为像元数，并保留原图用于对照。"],
    parameterNotes: [
      { name: "window", role: "设置众数滤波窗口边长", guidance: "默认 3；实现会把小于 3 的值提升为 3", effect: "窗口越大平滑越强、边界越圆钝", risk: "实现未强制奇数，偶数窗口的中心语义不直观" },
      { name: "min_pixels", role: "定义保留连通斑的最小像元数", guidance: "默认 4；按最小真实目标面积/GSD²换算", effect: "越大删除的小斑越多", risk: "会删除真实病斑、窄田埂或稀有类别" },
    ],
    resultInterpretation: ["n_changed 应连同原始图、平滑图和各类面积变化一起审查。", "视觉更整齐不等于精度更高；必须在独立标签上重新计算指标。"],
    applicable: ["面状类别为主、椒盐噪声明显且已知最小制图单元的分类产品。"],
    notApplicable: ["ACE/RX 等稀疏探测结果，或业务目标本身就是小点、小斑和细线。", "希望通过后处理弥补系统性错分类或错误标签。"],
    risks: ["背景或 NoData 参与众数会向有效区域侵蚀。", "逐类小斑替换顺序可能改变邻域类别分配，需检查边界。"],
    upstream: ["分类图生成、标签编码核验与 NoData 掩膜固定。"],
    downstream: ["后处理前后独立精度复算、制图和地块类别面积统计。"],
    demoFocus: ["并排显示原图/平滑图及 n_changed，圈出被删除的真实小目标。", "把 min_pixels 从 GSD 与最小业务面积换算出来。"],
  },
  {
    id: "45_parcel_zonal_stats",
    purpose: "按地块多边形汇总指数或分类，变成报表。",
    why: "L4 交付：客户要的是「3 号田平均 NDVI」，不是一张立方体。",
    formula: "多边形栅格化后：连续量分位数；分类则面积占比",
    steps: ["读单波段图", "可选 GeoJSON 栅格化", "逐地块统计", "写 JSON 报告"],
    viz: { kind: "zonal", caption: "同一张指数图，按田块边界切开求平均。" },
    inputs: [
      { name: "file", meaning: "指数图或分类图（单波段）" },
      { name: "file2", meaning: "可选地块 GeoJSON" },
      { name: "mode", meaning: "continuous 或 categorical" },
    ],
    outputs: [{ name: "zonal_report.json", meaning: "scene + parcels 统计" }],
    industryGap: "testdata 的 roi 字段代码不读。不要喂原始立方体。",
    checks: ["分类图该用 continuous 还是 categorical？"],
    summary: {
      definition: "将 GeoJSON 地块栅格化后，对单波段连续量或分类标签执行整景与分区统计。",
      value: "把指数/分类图转换为可按田块读取的均值、离散类别占比和像元数报告。",
      keyInput: "单波段 GeoTIFF、可选地块 GeoJSON，以及 continuous/categorical 模式。",
      keyOutput: "包含 scene、parcels、有效地块数和模式信息的 zonal_report.json。",
      keyLimit: "当前整景统计直接使用全部像元，未显式过滤 NoData；不读取 testdata 的 roi 参数。",
    },
    background: ["连续模式对整景输出 mean/std/min/max，地块函数按多边形覆盖像元汇总。", "分类模式输出各类别像元数和面积比例；比例本质上基于像元计数。"],
    prerequisites: ["输入必须是二维单波段产品，不能直接传原始多波段立方体。", "GeoJSON 与栅格须处于可正确栅格化的坐标关系，并预先处理 NoData 和无效像元。"],
    parameterNotes: [
      { name: "mode", role: "选择连续值或离散标签统计", guidance: "指数/反演量用 continuous，分类图用 categorical", effect: "决定输出均值方差还是类别面积占比", risk: "模式选错会把类别编号求均值或把连续值强转整数类别" },
      { name: "file2 GeoJSON", role: "定义地块分区边界", guidance: "推荐提供含稳定地块标识的有效 GeoJSON", effect: "有矢量时生成 parcels；无矢量时仅有整景统计", risk: "错 CRS、越界或极小多边形会产生零像元地块" },
    ],
    resultInterpretation: ["n_parcels_with_pixels 小于 n_parcels 时，应检查 CRS、范围和小地块栅格化。", "categorical 的 class_area_ratio 是像元比例；只有投影像元等面积时才可直接解释为面积比例。"],
    applicable: ["NDVI、LAI 等单波段连续产品的地块统计。", "单波段分类图的类别像元数与地块占比汇总。"],
    notApplicable: ["原始高光谱立方体、多波段指数栈或未经选择的丰度栈。", "要求亚像元边界精确面积、面积加权或自动读取 roi 参数。"],
    risks: ["NoData 未掩膜会污染均值、极值、类别计数和分母。", "经纬度栅格或不同纬度下像元面积不恒定，像元比例不等于严格面积比例。"],
    upstream: ["单波段产品选择、NoData 掩膜、投影/边界校验与地块标识整理。"],
    downstream: ["地块报表、分级告警和时序经营分析。"],
    demoFocus: ["用同一输入切换 continuous/categorical，展示错误模式造成的荒谬统计。", "检查零像元地块、NoData 污染及像元比例与真实面积的差别。"],
  },
];
