"""参数短中文名：写入 param_definitions.label，供界面备注。"""

PARAM_LABELS: dict[str, str] = {
    "input_dir": "输入测区目录",
    "output_dir": "输出目录",
    "cache_dir": "特征缓存目录",
    "log_dir": "日志目录",
    "process_dir": "中间过程目录",
    "products_dir_name": "成果子目录名",
    "run_mode": "运行模式",
    "start_stage": "起始阶段",
    "stop_after_stage": "停止阶段",
    "preset": "快捷预设",
    "benchmark_dir": "调试对照目录",
    "match_reference_color": "调试套色",
    "max_index": "最大影像编号",
    "max_frames": "最大曝光数",
    "min_agl_m": "最低航高（米）",
    "max_tilt_deg": "最大倾角（度）",
    "drop_white_panel": "丢弃白板帧",
    "require_pos": "必须有 POS",
    "primary_band": "主波段",
    "workers_at": "空三并行度",
    "memory_gb": "任务内存（GB）",
    "cpus": "任务 CPU（核）",
    "sigma_xy_m": "GNSS 平面先验（米）",
    "sigma_z_m": "GNSS 高程先验（米）",
    "sigma_attitude_deg": "IMU 姿态先验（度）",
    "outlier_threshold_px": "外点阈值（像素）",
    "calibrate_intrinsics": "内参自标定",
    "dsm_gsd": "DSM 分辨率（米）",
    "reuse_dsm": "复用已有 DSM",
    "n_layers": "高程扫描层数",
    "z_margin_m": "高程搜索半宽（米）",
    "workers_dense": "密集匹配进程数",
    "spike_tolerance_m": "尖刺剔除阈值（米）",
    "max_fill_gap_m": "空洞填充跨度（米）",
    "bands": "正射波段",
    "color_correction": "颜色校正",
    "seamline_enabled": "计算拼接线",
    "workers_ortho": "正射并行度",
    "write_pdf_report": "生成 PDF 报告",
    "write_json_report": "生成 JSON 报告",
    "grid_reference": "锁定交付格网",
    "radiometric_normalize": "辐射归一化到参考",
    "terrain_margin_lo_m": "地形带下余量（米）",
    "terrain_margin_hi_m": "地形带上余量（米）",
    "terrain_min_half_span_m": "无空三半宽下限（米）",
    "edge_trim_m": "边缘收边（米）",
    "flatten_edge_win_m": "贴边纠正窗口（米）",
    "flatten_edge_band_m": "贴边纠正带宽（米）",
}
