import type { AlgoWayhoDoc, ProductFit } from "./types";

function fit(productId: string, level: ProductFit["level"], why: string): ProductFit {
  return { productId, level, why };
}

export const L2_WAYHO: AlgoWayhoDoc[] = [
  {
    id: "17_mosaic",
    verdict: "机载多航带拼整景。对方已有自动拼接，我们做可嵌入业务系统的镶嵌服务。",
    product: "SKY、MAX 多航带必须镶嵌。SKY 推扫条带长、MAX 是帧拼图，参数不同。VIX 单次内置推扫通常已是一幅，不必镶嵌。SHIS 凝视是单视场立方体。SVC 是视频不是航带。",
    business: "机载软件把拼接当作卖点。合作不要做另一个桌面拼接器，而要：标准 GeoTIFF 输出、可调用、能把结果直接给指数和地块。承认对方现场软件更快出预览，我们负责「进 GIS / 进报表」的那一版。",
    application: "大田、流域、林场整景监测。实验室视场、工业单次扫描不是镶嵌业务。",
    hook: "约定镶嵌成果坐标系与命名，作为双方 L2 数据交换格式。",
    fits: [
      fit("sky-w417", "direct", "多航带推扫必须镶嵌"),
      fit("max-s810", "direct", "多光谱帧拼成测区"),
      fit("cloud", "adapt", "云端拼图任务"),
      fit("vix-w330", "no", "单次推扫已是整幅"),
      fit("shis-n220", "no", "单视场凝视"),
    ],
  },
  {
    id: "18_color_balance",
    verdict: "镶嵌接缝观感。只在多航带机载产品上推销。",
    product: "SKY/MAX 镶嵌后航带间曝光差会造成假长势边界。匀色让领导能看图。实验室单立方体没有接缝线。",
    business: "演示给领导看的第一眼。对方若拼接有色差，客户会怀疑硬件。本模块是「专题图能上台面」的化妆品，适合和 17 绑定，不要单独报价成高深算法。",
    application: "农业整景图、生态巡查图册。工业灰度分选不追求匀色美学。",
    hook: "与镶嵌打包，作为 SKY/MAX 交付图的默认后处理。",
    fits: [
      fit("sky-w417", "direct", "航带接缝必须匀色"),
      fit("max-s810", "direct", "多帧拼图曝光差"),
      fit("shis-n220", "no", "无航带接缝"),
      fit("vix-s230", "no", "产线单次扫描"),
    ],
  },
  {
    id: "19_multi_source_register",
    verdict: "把光谱、真彩色、地块矢量叠在一起。SKY 自带 2000 万 RGB，是最强理由。",
    product: "SKY-W417 高光谱+可见光双相机是设计上的配准对象。MAX 7+RGB 同样。VIX-W330 同轴共焦，出厂已共光路，配准需求弱，只需校验。SHIS 若另拍一张 RGB 可改编。地块 GeoJSON 是 45 的上游。",
    business: "农服/水务要「人看得到的图 + 算法吃的谱 + 承包地边界」。这是方案销售语言。合作把配准做成固定管道：HSI 正射、RGB 正射、矢量，三者误差作为验收指标。",
    application: "处方图落到地块、病斑落到可见光照片、岸线矢量裁光谱。工业可用「光谱图与 RGB 工位相机」配准，需改输入。",
    hook: "用 SKY 自带双相机做配准误差验收，作为机载套装的系统指标。",
    fits: [
      fit("sky-w417", "direct", "HSI + 2000 万 RGB + 地块矢量"),
      fit("max-s810", "direct", "7 通道与 RGB 必须套合"),
      fit("vix-w330", "adapt", "同轴设计，做校验而非从零配准"),
      fit("svc-2p4m30", "adapt", "光谱视频与彩色视频双路"),
      fit("shis-n220", "adapt", "另有 RGB 照片时才需要"),
    ],
  },
  {
    id: "20_bad_band_remove",
    verdict: "百波段高光谱才有坏波段；MAX 7 通道改成通道质量检查。",
    product: "SKY 1200 通道、VIX/SHIS 连续谱，水汽吸收、低响应波段必须剔除，否则 PCA 和分类被噪声主导。MAX/SVC/HSC 通道是工厂选好的，只需标记异常通道，不是「删掉几十个坏带」。",
    business: "科研客户会问「哪些波段别用」。给出坏波段列表是专业感。对多光谱客户不要讲坏波段，改口「通道健康度」，避免显得生搬卫星流程。",
    application: "全谱定量、SAM、深度学习分类。实时 8 通道视频几乎不删波段。",
    hook: "为 SKY/VIX 提供默认坏波段配置文件，按型号出厂写入云档案。",
    fits: [
      fit("sky-w417", "direct", "1200 通道必有水汽与低响应带"),
      fit("vix-w330", "direct", "400–1700 连续谱"),
      fit("shis-n220", "direct", "LCTF 密采样同样有差带"),
      fit("vix-s230", "direct", "SWIR 吸收带"),
      fit("max-s810", "adapt", "7 通道改为健康度，不批量删除"),
      fit("hsc-sc035", "adapt", "8 通道质量检查"),
    ],
  },
  {
    id: "21_savgol_smooth",
    verdict: "连续密光谱的平滑与包络。高光谱直接；7–8 通道多光谱不要做 SG。",
    product: "SKY、VIX、SHIS 的谱线需要降噪才能找红边、做吸收特征。MAX 只有 7 个点，SG 窗口没有意义，硬做会毁指数。HSC 同理。IrisCube 的曲线分析可背后调用平滑。",
    business: "这是实验室科研套装的标配，不是机载多光谱的卖点。合作按产品线拆 SKU：高光谱分析包含 SG，多光谱包不含。避免在 MAX 方案里堆「光谱平滑」被对方看穿。",
    application: "植物胁迫吸收谷、物证染料特征、材料谱峰。实时监控指数不依赖 SG。",
    hook: "绑定 SHIS/VIX/SKY 的科研分析包，与 IrisCube 曲线模块对接。",
    fits: [
      fit("sky-w417", "direct", "连续 1200 点可平滑"),
      fit("vix-n320", "direct", "2.5 nm VNIR 谱"),
      fit("vix-w330", "direct", "全波段特征提取前处理"),
      fit("shis-n220", "direct", "实验室曲线"),
      fit("iriscube", "adapt", "曲线分析可调用"),
      fit("max-s810", "no", "7 点不能做 SG"),
      fit("svc-2p4m30", "no", "5 个分立波段"),
    ],
  },
  {
    id: "22_normalize",
    verdict: "模型前处理，成像产品通吃。芯片与云平台训练也需要。",
    product: "无论 SKY 立方体还是 MAX 7 通道，进分类/反演前都要统一量纲。HSC 嵌入式推理同样。这是最无争议的公共库。",
    business: "不要单独卖。作为所有识别类算法的默认前置，写进云平台训练流水线。体现「我们懂光谱建模」而不是一个新软件。",
    application: "分类、反演、异常、少样本，全行业。",
    hook: "作为光谱云训练/推理流水线的标准节点，不单独报价。",
    fits: [
      fit("sky-w417", "direct", "高维立方体进模型前必须归一"),
      fit("max-s810", "direct", "指数与分类前处理"),
      fit("shis-n220", "direct", "实验室建模"),
      fit("hsc-sc035", "direct", "嵌入式推理前处理"),
      fit("cloud", "direct", "训练流水线节点"),
    ],
  },
  {
    id: "23_pca",
    verdict: "IrisCube 已有 PCA。我们提供 MNF/ICA 与可批处理，定位成引擎而非抢 UI。",
    product: "高光谱（SKY/VIX/SHIS）降维收益最大。MAX 7 维 PCA 信息有限，可做演示不宜当核心。对方 IrisCube 明确有按光谱差异性生成成分图——这是最大重叠点，必须在合作材料里写「可替换或增强其后端」。",
    business: "实验室软件的招牌功能之一。正确姿势是：IrisCube 继续给人点按钮，本接口给云平台和机载批量出成分图。再把 MNF（更适合高光谱噪声结构）作为差异化，IrisCube 宣传里只写了 PCA。",
    application: "物证墨迹（公开论文用过 SHIS-N220+化学计量学）、材料、植被变异可视化、去噪。",
    hook: "承认 PCA 重叠，主推 MNF 批处理 + 云端 API，给 IrisCube 当计算后端。",
    fits: [
      fit("sky-w417", "direct", "1200 维必须降维"),
      fit("vix-w330", "direct", "全谱科研"),
      fit("shis-n220", "direct", "实验室化学计量学主路径"),
      fit("iriscube", "adapt", "已有 PCA，做后端或 MNF 增强"),
      fit("max-s810", "adapt", "7 维收益有限"),
      fit("cloud", "adapt", "预处理/可视化服务"),
    ],
  },
  {
    id: "24_band_select",
    verdict: "给高光谱选波段；MAX 出厂已选好，不要再推销选择算法。",
    product: "SKY 1200 通道、SHIS 可任意步长扫描，有真实选择问题（算得动、避开坏带、对准红边）。MAX/SVC/HSC 通道是硬件决定的。VIX 高速机有时只下发部分通道，可选。",
    business: "可帮对方做「行业波段包」：农业红边包、水质包、塑料包，固化成相机扫描配方。这对 LCTF（SHIS 可任意波段）特别有商业价值——告诉客户扫哪些波段而不是全扫浪费时间。",
    application: "SHIS 凝视缩短扫描时间、机载降数据量、工业只留鉴别波段。",
    hook: "为 SHIS 做行业扫描配方（起止波长与步长），直接缩短客户采集时间。",
    fits: [
      fit("sky-w417", "direct", "从 1200 通道选出任务波段"),
      fit("shis-n220", "direct", "LCTF 可按配方扫描，商业价值高"),
      fit("shis-v220", "direct", "可见光配方"),
      fit("vix-n320", "direct", "可降采样通道"),
      fit("max-s810", "no", "7 通道出厂已选"),
      fit("hsc-sc035", "no", "8 通道硬件固定"),
    ],
  },
  {
    id: "25_superpixel",
    verdict: "从像素改到斑块，图像类产品都可用，机载专题图更干净。",
    product: "正射后的 SKY/MAX 用地物斑块比单像素稳。实验室 SHIS 高空间分辨率（2048）很适合超像素。SVC 视频要降帧再做。HSC 分辨率 640×480 可用但斑块粗。",
    business: "领导看图受不了椒盐噪声。超像素是分类/检测的前端，适合和 34/40/44 打包成「图斑产品」。对方目标智能提取（IrisCube）有相似叙事，强调我们输出可进 GIS 的对象。",
    application: "病斑、杂草、藻华斑块、工业瑕疵轮廓。",
    hook: "作为识别类算法的统一前端，写入云平台「对象层」。",
    fits: [
      fit("sky-w417", "direct", "正射后按冠层/地物成斑"),
      fit("max-s810", "direct", "农田图斑"),
      fit("shis-n220", "direct", "高空间分辨率实验室图"),
      fit("vix-w330", "direct", "近距对象分割"),
      fit("svc-2p4m30", "adapt", "抽帧后做斑块"),
    ],
  },
  {
    id: "26_patch_build",
    verdict: "给深度学习准备样本。高光谱分类/检测的训练基础设施。",
    product: "SKY/VIX/SHIS 立方体切 patch 才能训 36–40。MAX 通道少，patch 仍有空间上下文，但谱维很浅。云平台宣称数据标注+模型训练，本算法是缺的那块「怎么切光谱立方体」。",
    business: "对方云平台有标注和训练叙事，但高光谱切块策略（避开坏带、保留光谱连续）是专业细节。合作切入云平台数据层，比一上来推 Transformer 更容易被接受。",
    application: "作物分类、病斑检测、工业缺陷深度学习。芯片端侧训练也需要离线切块。",
    hook: "作为光谱云「数据集构建」模块，先于深度学习模型交付。",
    fits: [
      fit("sky-w417", "direct", "空谱样本主来源"),
      fit("vix-w330", "direct", "近距全谱样本"),
      fit("shis-n220", "direct", "实验室可控标注"),
      fit("cloud", "direct", "训练流水线的切块节点"),
      fit("max-s810", "adapt", "空间块可用，谱维浅"),
      fit("hsc-sc035", "adapt", "8 通道视频抽帧切块"),
    ],
  },
];
