import type { AlgoWayhoDoc, ProductFit } from "./types";

function fit(productId: string, level: ProductFit["level"], why: string): ProductFit {
  return { productId, level, why };
}

export const L3_WAYHO: AlgoWayhoDoc[] = [
  {
    id: "27_ndvi",
    verdict: "MAX/SVC 已经内置。SKY 也能算。合作重点不是「会不会 NDVI」，而是统一口径并接到地块。",
    product: "MAX-S800 官方内置 NDVI；SVC 内置长势。SKY 全谱可精确取红/近红外。SHIS-N220、VIX-N320/W330 有 NIR。SHIS-V220 只到 750 nm，NIR 不足，指数会偏。SHIS-S260、VIX-S230 纯 SWIR，算不了 NDVI。HSC 450–900 可以。",
    business: "这是对方卖农业/林业的入门功能，不要包装成独家算法。我们的增量是：同一套 NDVI 定义贯穿 MAX 实时、SKY 事后、地块汇总（45），避免现场图传一个值、报告另一个值。重叠要写进合作备忘录，定位「口径引擎 + L4」。",
    application: "官网精准农业长势、智慧林业覆盖、SVC 视频叠加长势。工业塑料/烟叶分选一般不用 NDVI。",
    hook: "承诺与 MAX 机载 NDVI 波段定义对齐，再把结果送进地块报表，补上他们实时能力后面的业务闭环。",
    fits: [
      fit("max-s810", "direct", "机载已内置，对齐口径后接报表"),
      fit("svc-2p4m30", "direct", "视频长势，边缘已算"),
      fit("sky-w417", "direct", "全谱取红/NIR 更准"),
      fit("vix-n320", "direct", "便携 VNIR"),
      fit("shis-n220", "direct", "实验室 VNIR"),
      fit("hsc-sc035", "direct", "8 通道含红/NIR"),
      fit("shis-v220", "adapt", "截止 750 nm，NIR 偏弱"),
      fit("vix-s230", "no", "纯 SWIR，无红光波段"),
      fit("shis-s260", "no", "920–1700 nm，不能做 NDVI"),
    ],
  },
  {
    id: "28_ndre",
    verdict: "MAX 标配 720/750 nm 窄带，这是他们多光谱相对竞品的卖点，要对齐而不是另起炉灶。",
    product: "MAX 标配红边窄带，NDRE 是出厂能力。SKY/SHIS-N/VIX-N 连续谱可算更稳的红边指数。SVC 有 720 nm。SWIR 机没有红边。",
    business: "密冠层、施氮是高客单价农业项目。对方已经用 NDRE 打松材线虫等模型。合作应把 NDRE 纳入同一指数家族，并提供「何时用 NDVI、何时用 NDRE」的业务说明，帮销售讲清 7 通道为什么比 RGB 贵。",
    application: "密植作物氮素、果园冠层、林业早期胁迫。实验室表型同样。工业 SWIR 分选无关。",
    hook: "写进 MAX 农业方案的指数菜单，与机载内置 NDRE 对照验证。",
    fits: [
      fit("max-s810", "direct", "720/750 窄带就是为红边指数准备的"),
      fit("sky-w417", "direct", "连续红边更稳"),
      fit("svc-2p4m30", "direct", "含 720 nm"),
      fit("shis-n220", "direct", "实验室红边"),
      fit("vix-w330", "direct", "全谱含红边"),
      fit("vix-s230", "no", "无红边波段"),
    ],
  },
  {
    id: "29_evi_savi",
    verdict: "MAX 宣传内置 EVI。土壤背景重的耕地调查要用 SAVI/MSAVI，这是方案升级话术。",
    product: "与 NDVI 相同的 VNIR 产品可用。MAX 已打 EVI。SKY 可按标准系数算。裸土多的新垦地 SAVI 比 NDVI 诚实。",
    business: "帮助对方销售从「只会 NDVI」升级到「按物候选指数」。耕地调查、出苗期是刚需。不要对工业客户讲 EVI。",
    application: "耕地调查、种植状况评估、稀疏植被、干旱区。官网农业场景直接对应。",
    hook: "做成指数套件（NDVI/NDRE/EVI/SAVI），作为 MAX/SKY 农业包的标准输出。",
    fits: [
      fit("max-s810", "direct", "官方已提 EVI"),
      fit("sky-w417", "direct", "标准波段可复现"),
      fit("vix-n320", "direct", "便携农田样地"),
      fit("shis-n220", "direct", "盆栽/表型土壤背景"),
      fit("svc-2p4m30", "direct", "定点农田"),
    ],
  },
  {
    id: "30_ndmi_ndwi",
    verdict: "水质与水分是官网生态场景的核心。NDWI 多光谱就能做；NDMI 必须有 SWIR，只有 SKY/VIX-S/SHIS-S/W330。",
    product: "NDWI（绿+NIR）MAX、SVC、VNIR 高光谱都可以。NDMI（NIR+SWIR）要求 1600 nm 附近，MAX 到 1000 nm 不够，必须上 SKY-W417 或 SWIR 机。这是推 SKY 全波段相对 MAX 溢价的技术论据。",
    business: "对方有坪山河 MAX + SpecMetis 水质案例。MAX 做水体提取（NDWI/MNDWI）成立；若客户要植被水分、土壤湿度，应引导 SKY/VIX-W330。合作材料里把「测水体」和「测叶片水分」拆开，避免用错相机。",
    application: "藻华、黑臭、岸线、溢油外围水体；农业干旱；SWIR 工业水分（烟叶、食品）是另一套，不一定用 NDMI 公式。",
    hook: "生态项目：MAX 做 NDWI 水体；要水分胁迫就升级 SKY 上 NDMI。两条报价单。",
    fits: [
      fit("sky-w417", "direct", "400–1700，NDWI 与 NDMI 都能做"),
      fit("vix-w330", "direct", "便携全波段水分"),
      fit("shis-s260", "direct", "实验室 SWIR 水分"),
      fit("vix-s230", "direct", "SWIR 水分/材料，NDWI 则缺绿光"),
      fit("max-s810", "adapt", "只能 NDWI/MNDWI，不能 NDMI"),
      fit("svc-2p4m30", "adapt", "有绿/NIR，水体可以；无 SWIR"),
    ],
  },
  {
    id: "31_red_edge_params",
    verdict: "高光谱特色，MAX 7 点估不准红边位置。这是 SKY/SHIS/VIX 相对多光谱的差异化。",
    product: "红边位置需要 680–750 nm 连续采样。SKY、SHIS-N、VIX-N/W 直接。MAX 只有 720 与 750 两个窄带，插值位置不可信。SVC 更少。SWIR 机没有红边。",
    business: "销售上用来回答「为什么不买多光谱买高光谱」。物候、氮素、早期胁迫是科研和高端农服。不要写进 MAX 宣传页，否则会降低高光谱溢价。",
    application: "植物表型、育种、密冠层氮、物候观测。工业与水质不是红边位置的主场。",
    hook: "作为 SKY/SHIS 科研套装的招牌指数，和 MAX 的 NDRE 刻意区分。",
    fits: [
      fit("sky-w417", "direct", "连续红边可定位"),
      fit("shis-n220", "direct", "实验室表型"),
      fit("vix-n320", "direct", "2.5 nm 足够"),
      fit("vix-w330", "direct", "全谱"),
      fit("max-s810", "no", "两个红边通道估不准位置"),
      fit("svc-2p4m30", "no", "单点 720 nm"),
    ],
  },
  {
    id: "32_regression_inversion",
    verdict: "叶绿素、氮、水分等连续量。高光谱主场；多光谱能做弱模型。需要样本，是项目制合作。",
    product: "SKY/VIX/SHIS 谱维够 PLS/RF。MAX 7 通道可做粗回归，精度取决于样本。工业 SWIR（烟叶、食品水分）是 VIX-S230 的强场景，比农业更肯付费。",
    business: "这是从卖相机到卖「含量图」的升级。必须有地面化验样本，合同要写建模服务而不是标准软件。对方云平台有模型训练叙事，本算法是回归引擎。适合联合投标科研院所与龙头农场。",
    application: "农业氮/叶绿素、烟叶分选、果蔬品质、实验室表型。不要承诺无样本的通用模型。",
    hook: "选一个对方已有客户（如葡萄园或川农大 VIX-W330），用其化验数据做 PLS 试点。",
    fits: [
      fit("sky-w417", "direct", "大田含量图"),
      fit("vix-w330", "direct", "高校表型+化验"),
      fit("shis-n220", "direct", "实验室可控样本"),
      fit("vix-s230", "direct", "SWIR 工业定量"),
      fit("max-s810", "adapt", "通道少，模型偏弱"),
      fit("cloud", "adapt", "训练与部署载体"),
    ],
  },
  {
    id: "33_physical_inversion",
    verdict: "PROSAIL 一类机理反演。只适合冠层连续谱，且要改混合像元假设。不要对 MAX 承诺。",
    product: "SKY、SHIS-N、VIX-N/W 有连续 VNIR 才能对 LUT。MAX 7 点严重欠定。近距叶片（实验室）与冠层 RT 假设不同，需改编。工业材料不是植被辐射传输。",
    business: "论文与重大项目好看，落地难。可作为科研套装的加分项，不要写进农业交付验收的硬指标。对方若对接高校（川农大等），可以联合发文，但商务上单独成科研包。",
    application: "LAI、叶绿素科研。官网「科学研究 / 植物表型」对应。量产农服先走 32。",
    hook: "科研包可选模块，验收用趋势合理性，不用绝对 LAI 误差。",
    fits: [
      fit("sky-w417", "adapt", "冠层混合像元，需改假设"),
      fit("shis-n220", "adapt", "近距叶片 ≠ 冠层 RT"),
      fit("vix-w330", "adapt", "样地尺度可试"),
      fit("max-s810", "no", "通道不足以支撑 PROSAIL"),
      fit("vix-s230", "no", "SWIR 工业，不是植被 RT"),
    ],
  },
  {
    id: "34_svm_rf_classify",
    verdict: "全系都能用的识别基本盘。工业分选、物证、作物类型都靠它。IrisCube 已有分类，定位成可部署引擎。",
    product: "任何有光谱维的相机都能做像素/对象分类。SKY 地物分类、MAX 作物/水体、SHIS 物证墨迹、VIX-S 塑料/烟叶、SVC 林木识别官方已在边缘做。HSC 8 通道也能做浅层分类。",
    business: "对方 IrisCube「图像分类计算」和 SVC「林木识别」已占入口。我们的价值是同一套模型从实验室打到机载批量，并输出 GeoTIFF 分类图给 44/45。工业分选是高付费、低地理需求的另一条线，应用 VIX-S230，别用农业话术。",
    application: "作物类型、树种、塑料、烟叶除杂、墨迹品牌、藻华类别。官网工业检测与公安刑侦、农业类型识别都对得上。",
    hook: "实验室 SHIS 分类模型 → 同一标签体系部署到 SKY 航飞，打「空地一致」。",
    fits: [
      fit("sky-w417", "direct", "地物/作物分类主路径"),
      fit("max-s810", "direct", "水体/植被/裸土等粗类"),
      fit("shis-n220", "direct", "物证与材料"),
      fit("vix-s230", "direct", "工业高速分类"),
      fit("svc-2p4m30", "direct", "边缘已有林木等模型"),
      fit("iriscube", "adapt", "已有分类 UI，做后端"),
      fit("hsc-sc035", "adapt", "8 通道浅层类别"),
    ],
  },
  {
    id: "35_spectral_matching",
    verdict: "光谱库比对。高光谱强；多光谱弱。物证、材料、特定目标检索是合作故事。",
    product: "SAM 吃连续谱。SKY/VIX/SHIS 直接。MAX 7 维角度不稳定。对方物证文保、材料种类识别、宝石等场景就是光谱库逻辑。IrisCube 目标提取有相近叙事。",
    business: "适合「已知目标、缺标注」的项目：某污染物、某涂料、某墨水。比深度学习更易向公安/海关解释。合作可共建行业光谱库，存在光谱云，模型和硬件绑定。",
    application: "官网公安刑侦、文物笔墨、工业材料、污染源。农业大类分类不如 34。",
    hook: "从 SHIS 物证光谱库起步，库格式与 SAM 接口标准化后复用到 VIX/SKY。",
    fits: [
      fit("shis-n220", "direct", "实验室光谱库主场"),
      fit("sky-w417", "direct", "野外已知地物检索"),
      fit("vix-w330", "direct", "便携比对"),
      fit("vix-s230", "direct", "SWIR 材料指纹"),
      fit("iriscube", "adapt", "目标提取可对接 SAM"),
      fit("max-s810", "adapt", "7 维可做，可分性差"),
    ],
  },
  {
    id: "36_cnn1d_classify",
    verdict: "沿光谱的深度学习。只给高光谱。MAX/SVC 谱长不够，不要写进方案。",
    product: "SKY 1200 点、VIX/SHIS 连续谱才有「谱形」。7–8 通道 1D-CNN 是过拟合玩具。训练依赖 26 的样本和云平台 GPU。",
    business: "用来对标国际论文、打动科研客户。量产农服仍以 34 为主。合作放在光谱云「高光谱模型」层，明确输入是立方体不是多光谱 TIFF。",
    application: "细类识别：品种、病害早期谱形、精细材料。需要标注。",
    hook: "科研云套餐，与 26/39 一起，不进 MAX 报价单。",
    fits: [
      fit("sky-w417", "direct", "谱形信息充足"),
      fit("vix-w330", "direct", "全谱近距"),
      fit("shis-n220", "direct", "实验室标注质量高"),
      fit("cloud", "adapt", "训练载体"),
      fit("max-s810", "no", "7 点无谱形"),
      fit("hsc-sc035", "no", "8 通道不够 1D-CNN"),
    ],
  },
  {
    id: "37_cnn3d_classify",
    verdict: "空谱三维卷积，业界论文主流。高光谱正射后最合适。",
    product: "SKY 正射立方体是理想输入。实验室 SHIS 高空间分辨率也适合。MAX 可退化成 2D+浅谱，效果接近普通语义分割。边缘 SVC/HSC 算力与通道都不适合 3D-CNN。",
    business: "高端方案的技术招牌。部署成本高，适合示范田、科研、工业视觉工位，不适合 SVC 24h 视频。云平台 GPU 推理是对方「算法引擎」宣传的实例化。",
    application: "复杂农田地物、病斑纹理+光谱、工业表面缺陷。",
    hook: "选一块 SKY 示范田做 HybridSN 类模型，作为光谱云行业模型样板。",
    fits: [
      fit("sky-w417", "direct", "空谱立方体主场"),
      fit("shis-n220", "direct", "高空间×光谱"),
      fit("vix-w330", "direct", "近距空谱"),
      fit("max-s810", "adapt", "退化为浅谱 2D"),
      fit("cloud", "adapt", "GPU 推理"),
      fit("svc-2p4m30", "no", "边缘视频不宜 3D-CNN"),
    ],
  },
  {
    id: "38_transformer_classify",
    verdict: "高精度复杂场景。只要高光谱和标注预算，不要对多光谱和边缘相机承诺。",
    product: "与 37 类似，更吃数据和算力。SKY 科研与大项目。实验室样本可控。MAX/SVC 不值得上 Transformer。",
    business: "品牌和技术壁垒，不是标准交付。写在「联合实验室」而不是产品彩页的标配列表。避免对方销售对外乱承诺精度。",
    application: "细碎地物、高混杂种植结构、科研竞赛级分类。",
    hook: "联合实验室课题，不进标准 SKU。",
    fits: [
      fit("sky-w417", "direct", "复杂场景高精度"),
      fit("shis-n220", "direct", "实验室可复现"),
      fit("vix-w330", "direct", "全谱"),
      fit("cloud", "adapt", "训练"),
      fit("max-s810", "no", "通道与数据规模不匹配"),
    ],
  },
  {
    id: "39_few_shot_classify",
    verdict: "标注少也能上线。这是工业换线、农业新作物的真实痛点，适合项目制。",
    product: "所有成像产品都缺标注。实验室 SHIS 最容易拍少量样本。机载 SKY 新作物季也需要。MAX 类别粗，少样本收益一般。云平台「降低开发难度」的话术正好对上。",
    business: "对方客户不可能每换一种塑料、一种病害就标一万张。少样本是从 PoC 到产线的桥梁。合同按「新类 1 天适应」卖服务，而不是卖一个模型文件。",
    application: "工业新料号、新病害、新树种。官网定制化服务客户画像。",
    hook: "用 VIX 工业换料或 SHIS 新墨水做「10 张样本上线」演示。",
    fits: [
      fit("shis-n220", "direct", "实验室少量样本可控"),
      fit("vix-s230", "direct", "产线换料"),
      fit("sky-w417", "adapt", "新作物季，需现场标"),
      fit("max-s810", "adapt", "粗类少样本收益一般"),
      fit("cloud", "adapt", "模型快速部署叙事"),
    ],
  },
  {
    id: "40_detect_segment",
    verdict: "病斑、杂草、缺陷、漏油。对方 SVC 已有漏油等边缘算法，机载和实验室是增量。",
    product: "MAX/SKY 做田间病斑与倒伏区域；SHIS/VIX 做近距病斑与工业瑕疵；SVC 官方漏油、林木。HSC 高帧率适合运动缺陷。输出应是掩膜/框，不是整幅一个类。",
    business: "比整图分类更好报价：按「检出事件」给水务、农服、产线。注意与 SVC 边缘算法分工：边缘实时告警用他们的，事后复核与面积统计用我们的，避免抢固件。",
    application: "官网病虫害、倒伏、溢油、包装品控、LED/晶圆外观（需确认波段）。",
    hook: "机载出病斑面积，SVC 出实时告警，两套接口同一套标签。",
    fits: [
      fit("sky-w417", "direct", "田间斑块检测"),
      fit("max-s810", "direct", "病害/倒伏区域"),
      fit("svc-2p4m30", "direct", "漏油等边缘检测，需分工"),
      fit("vix-s230", "direct", "产线缺陷"),
      fit("shis-n220", "direct", "近距病斑/痕迹"),
      fit("hsc-sc035", "adapt", "高速快照缺陷"),
    ],
  },
  {
    id: "41_unmixing",
    verdict: "亚像元占比。只有密光谱成立。MAX 7 通道欠定，不要承诺。",
    product: "SKY 航飞混合像元（土+苗+枯叶）是真问题。实验室高光谱也可做端元。多光谱解混在数学上不稳。工业若纯物质分选，分类往往够，解混用于混合物。",
    business: "高端遥感话术，适合科研与精细农业（出苗覆盖度）。不要对 MAX 客户讲解混。可与 45 结合：地块内端元比例比平均 NDVI 更有解释力。",
    application: "稀疏植被覆盖度、矿物/材料混合、藻华与水体混合。",
    hook: "SKY 出苗期覆盖度试点，用解混比例代替 NDVI 阈值。",
    fits: [
      fit("sky-w417", "direct", "航飞混合像元"),
      fit("vix-w330", "direct", "近距混合物"),
      fit("shis-n220", "direct", "实验室端元"),
      fit("max-s810", "no", "7 通道欠定"),
      fit("svc-2p4m30", "no", "5 通道不能解混"),
    ],
  },
  {
    id: "42_anomaly_detect",
    verdict: "找不像周围的点。工业除杂、漏油、农田胁迫都能讲，且常无需标注。",
    product: "RX 一类方法通吃高光谱。VIX-S230 高速除杂是付费场景。SVC 漏油是官方场景。SKY 找田间异常斑。MAX 通道少仍可做空间异常。无标注是 IrisCube「无需确定目标变量」话术的对应算法。",
    business: "最好卖的非监督模块之一。产线、安防、应急都听得懂「找异常」。和对方目标智能提取互补：他们偏交互选目标，我们偏全图扫描告警。",
    application: "烟叶除杂、塑料异物、溢油、未知病害苗头、物证痕迹。",
    hook: "工业 VIX-S230 除杂 + 生态 SVC 漏油，两条行业 Demo 并行。",
    fits: [
      fit("vix-s230", "direct", "高速工业除杂"),
      fit("sky-w417", "direct", "田间光谱异常"),
      fit("svc-2p4m30", "direct", "漏油监测"),
      fit("shis-n220", "direct", "痕迹/污染点"),
      fit("max-s810", "direct", "空间+浅谱异常"),
      fit("iriscube", "adapt", "无标注叙事可对接"),
    ],
  },
  {
    id: "43_change_detect",
    verdict: "多时相是监测订阅的核心。机载复飞直接用；SVC 是视频时序，要改编。",
    product: "SKY/MAX 隔周复飞，IR-MAD 等吃两景反射率。必须先有 11 相对辐射。SVC 24h 是帧间变化，不是两景影像对，算法要换。实验室重复实验可改编。",
    business: "把一次性卖相机变成按年监测。水务、农服、林业火险都靠变化。对方云平台存储多期数据后，本算法是「为什么要续费存储」的理由。",
    application: "病虫害扩散、水体变化、砍伐、倒伏前后、应急溢油扩散。",
    hook: "套餐：MAX 定期复飞 + 变化图 + 告警 API，按测区订阅。",
    fits: [
      fit("sky-w417", "direct", "高光谱复飞变化"),
      fit("max-s810", "direct", "农情/水质周报"),
      fit("cloud", "adapt", "多期数据调度"),
      fit("svc-2p4m30", "adapt", "视频时序，需换模型"),
      fit("shis-n220", "adapt", "重复实验前后"),
    ],
  },
  {
    id: "44_postprocess_smooth",
    verdict: "分类图要能上台面。所有出图斑的产品都该接这一步。",
    product: "机载分类图小斑剔除后才能进报告。实验室分类图同样。SVC 叠加结果也可做空间平滑，但实时性要求不同。",
    business: "低成本、高观感。应设为 34/37/40 的默认后处理，不单独卖。对方演示图若椒盐严重，会被认为模型不行。",
    application: "所有专题制图。工业像素级分选有时不能平滑（会吞小异物），要可关闭。",
    hook: "分类接口默认打开，工业模式提供关闭开关。",
    fits: [
      fit("sky-w417", "direct", "专题图整理"),
      fit("max-s810", "direct", "处方图前清理"),
      fit("shis-n220", "direct", "实验室分类图"),
      fit("vix-s230", "adapt", "小异物场景需可关"),
      fit("svc-2p4m30", "adapt", "叠加层平滑"),
    ],
  },
  {
    id: "45_parcel_zonal_stats",
    verdict: "给领导的那张表。机载农业/林业/水务的闭环。对方处方图叙事的最后一公里。",
    product: "MAX 官方讲处方图植入植保无人机；SKY 更能按地块出均值/分位。输入是指数或分类图 + 地块 GeoJSON。实验室改成 ROI 统计。SVC 改成站点时间序列，不是地块。工业改成批次/工单统计。",
    business: "这是合作最应该盯住的交付物：相机厂商缺「一块地一个数」的业务对象。对方有指数和拼接，缺承包地、告警阈值、API 给农服系统。本算法让硬件方案能进政府耕地项目和农企 SaaS。",
    application: "官网产量预估、耕地调查、草地森林覆盖统计、处方图。实验室课题用 ROI 即可。",
    hook: "用对方一次 MAX/SKY 飞行 + 一份地块界线，出可验收的地块 CSV/GeoJSON，作为联合方案封面。",
    fits: [
      fit("max-s810", "direct", "处方图/地块报表闭环"),
      fit("sky-w417", "direct", "高光谱地块统计更细"),
      fit("cloud", "adapt", "报表 API 部署"),
      fit("shis-n220", "adapt", "改为 ROI 而非承包地"),
      fit("svc-2p4m30", "adapt", "站点统计，不是地块多边形"),
      fit("vix-s230", "adapt", "批次/工单汇总"),
    ],
  },
];
