import type { AlgoWayhoDoc, ProductFit } from "./types";

function fit(productId: string, level: ProductFit["level"], why: string): ProductFit {
  return { productId, level, why };
}

export const L3_WAYHO: AlgoWayhoDoc[] = [
  {
    id: "27_ndvi",
    verdict: "MAX/SVC 已经内置。SKY 也能算。合作重点不是「会不会 NDVI」，而是统一口径并接到地块。",
    product: "MAX-S810 官方页明确列出内置 NDVI；SKY-W417 的 400–1700 nm 覆盖红光与近红外；HSC-SC035 官方页列出 450–900 nm。其他型号是否覆盖所需波段，需以项目所用型号官方规格为准。",
    business: "适配只表示具备所需红光、近红外输入并能接收反射率数据，不承诺指数效果。",
    application: "官网精准农业长势、智慧林业覆盖、SVC 视频叠加长势。工业塑料/烟叶分选一般不用 NDVI。",
    hook: "承诺与 MAX 机载 NDVI 波段定义对齐，再把结果送进地块报表，补上他们实时能力后面的业务闭环。",
    fits: [
      fit("max-s810", "direct", "机载已内置，对齐口径后接报表"),
      fit("svc-2p4m30", "adapt", "需以项目所用型号官方规格为准"),
      fit("sky-w417", "direct", "全谱可选取红/NIR 通道"),
      fit("vix-n320", "direct", "便携 VNIR"),
      fit("shis-n220", "direct", "实验室 VNIR"),
      fit("hsc-sc035", "direct", "8 通道含红/NIR"),
      fit("shis-v220", "adapt", "截止 750 nm，NIR 偏弱"),
      fit("vix-s230", "no", "纯 SWIR，无红光波段"),
      fit("shis-s260", "no", "920–1700 nm，不能做 NDVI"),
    ],
  },
  {
    id: "28_ndre",
    verdict: "MAX-S810 官方页列出 720/750 nm 窄带及内置 NDRE；这里只判断波段与接口适配。",
    product: "MAX-S810 官方标配波段含 720/750 nm；SKY-W417 官方覆盖 400–1700 nm。其他型号红边覆盖需以项目所用型号官方规格为准。",
    business: "适配只表示存在红边与近红外输入，不据此推荐业务场景或承诺科学效果。",
    application: "当冠层接近饱和、需要红边相对差异时，可作为叶绿素或氮相关指数的条件性参考，不绑定固定作物或施肥场景。实验室表型同样。工业 SWIR 分选无关。",
    hook: "写进 MAX 农业方案的指数菜单，与机载内置 NDRE 对照验证。",
    fits: [
      fit("max-s810", "direct", "720/750 窄带就是为红边指数准备的"),
      fit("sky-w417", "direct", "官方波段范围覆盖红边与近红外"),
      fit("svc-2p4m30", "adapt", "具体红边波段需以项目所用型号官方规格为准"),
      fit("shis-n220", "direct", "实验室红边"),
      fit("vix-w330", "direct", "全谱含红边"),
      fit("vix-s230", "no", "无红边波段"),
    ],
  },
  {
    id: "29_evi_savi",
    verdict: "MAX 宣传内置 EVI。土壤背景重的耕地调查要用 SAVI/MSAVI，这是按背景选择指数的工程条件。",
    product: "与 NDVI 相同的 VNIR 产品可用。MAX 已打 EVI。SKY 可按标准系数算。裸土多的新垦地 SAVI 比 NDVI 诚实。",
    business: "帮助对方销售从「只会 NDVI」升级到「按物候选指数」。耕地调查、出苗期是刚需。不要对工业客户讲 EVI。",
    application: "耕地调查、种植状况评估、稀疏植被、干旱区。官网农业场景直接对应。",
    hook: "接入前核对各公式所需波段、反射率输入和输出字段。",
    fits: [
      fit("max-s810", "direct", "官方已提 EVI"),
      fit("sky-w417", "direct", "标准波段可复现"),
      fit("vix-n320", "direct", "便携农田样地"),
      fit("shis-n220", "direct", "盆栽/表型土壤背景"),
      fit("svc-2p4m30", "direct", "定点农田"),
    ],
  },
  {
    id: "30_ndmi_ndwi",
    verdict: "水质与水分是官网生态场景的核心。NDWI 多光谱就能做；NDMI 必须有 SWIR，只有 SKY/VIX-S/SHIS-S/W330。",
    product: "NDWI 需要绿光与近红外，NDMI 需要近红外与短波红外。SKY-W417 官方 400–1700 nm 覆盖这些区域；MAX-S810 官方波段不含短波红外。其他型号需以项目所用型号官方规格为准。",
    business: "对方有坪山河 MAX + SpecMetis 水质案例。MAX 做水体提取（NDWI/MNDWI）成立；若客户要植被水分、土壤湿度，应引导 SKY/VIX-W330。合作材料里把「测水体」和「测叶片水分」拆开，避免用错相机。",
    application: "藻华、黑臭、岸线、溢油外围水体；农业干旱；SWIR 工业水分（烟叶、食品）是另一套，不一定用 NDMI 公式。",
    hook: "生态项目：MAX 做 NDWI 水体；要水分胁迫就升级 SKY 上 NDMI。两条报价单。",
    fits: [
      fit("sky-w417", "direct", "400–1700，NDWI 与 NDMI 都能做"),
      fit("vix-w330", "direct", "便携全波段水分"),
      fit("shis-s260", "direct", "实验室 SWIR 水分"),
      fit("vix-s230", "direct", "SWIR 水分/材料，NDWI 则缺绿光"),
      fit("max-s810", "adapt", "只能 NDWI/MNDWI，不能 NDMI"),
      fit("svc-2p4m30", "adapt", "有绿/NIR，水体可以；无 SWIR"),
    ],
  },
  {
    id: "31_red_edge_params",
    verdict: "高光谱特色，MAX 7 点估不准红边位置。这是连续光谱相对离散多光谱在红边位置估计上的方法边界。",
    product: "红边位置需要红边区连续采样。SKY-W417 官方为连续光谱；MAX-S810 官方仅列出离散波段，不满足当前连续谱实现。其他型号需以项目所用型号官方规格为准。",
    business: "适配判断只基于连续采样与输入波长表，不用于价格、销售或效果比较。",
    application: "植物表型、育种、密冠层氮、物候观测。工业与水质不是红边位置的主场。",
    hook: "接入前核对红边区采样连续性、波长表与算法输入格式。",
    fits: [
      fit("sky-w417", "direct", "连续红边可定位"),
      fit("shis-n220", "direct", "实验室表型"),
      fit("vix-n320", "direct", "2.5 nm 足够"),
      fit("vix-w330", "direct", "全谱"),
      fit("max-s810", "no", "两个红边通道估不准位置"),
      fit("svc-2p4m30", "adapt", "需以项目所用型号官方规格为准"),
    ],
  },
  {
    id: "32_regression_inversion",
    verdict: "叶绿素、氮、水分等连续量。高光谱主场；多光谱能做弱模型。需要样本，是项目制合作。",
    product: "连续光谱设备可提供 PLS 输入；MAX-S810 官方页列出 7 个光谱通道，可接入低维回归，但误差取决于独立样本验证。其他型号波段需以项目所用型号官方规格为准。",
    business: "适配需要参考值样本、训练/验证划分和明确误差指标；不能把模型当成无样本通用产品。",
    application: "农业氮/叶绿素、烟叶分选、果蔬品质、实验室表型。不要承诺无样本的通用模型。",
    hook: "选一个对方已有客户（如葡萄园或川农大 VIX-W330），用其化验数据做 PLS 试点。",
    fits: [
      fit("sky-w417", "direct", "大田含量图"),
      fit("vix-w330", "direct", "高校表型+化验"),
      fit("shis-n220", "direct", "实验室可控样本"),
      fit("vix-s230", "direct", "SWIR 工业定量"),
      fit("max-s810", "adapt", "通道少，模型偏弱"),
      fit("cloud", "adapt", "训练与部署载体"),
    ],
  },
  {
    id: "33_physical_inversion",
    verdict: "不用化验图，一次给出叶面积和叶绿素两张图。只适合冠层连续谱，混合像元要改假设。不要对 MAX 承诺。",
    product: "SKY、SHIS-N、VIX-N/W 有连续 VNIR 才能对 LUT。MAX 7 点严重欠定。近距叶片（实验室）与冠层 RT 假设不同，需改编。工业材料不是植被辐射传输。",
    business: "论文与重大项目好看，落地难。可作为科研套装的加分项，不要写进农业交付验收的硬指标。对方若对接高校（川农大等），可以联合发文，但商务上单独成科研包。",
    application: "叶面积和叶绿素科研图。官网「科学研究 / 植物表型」对应。量产农服先走 32。",
    hook: "科研包可选模块，验收用趋势合理性，不用绝对 LAI 误差。",
    fits: [
      fit("sky-w417", "adapt", "冠层混合像元，需改假设"),
      fit("shis-n220", "adapt", "近距叶片 ≠ 冠层 RT"),
      fit("vix-w330", "adapt", "样地尺度可试"),
      fit("max-s810", "no", "通道不足以支撑 PROSAIL"),
      fit("vix-s230", "no", "SWIR 工业，不是植被 RT"),
    ],
  },
  {
    id: "34_svm_rf_classify",
    verdict: "全系都能用的识别基本盘。工业分选、物证、作物类型都靠它。IrisCube 已有分类，定位成可部署引擎。",
    product: "分类输入需有稳定波段、标签与空间对应关系。HSC-SC035 官方页列出 8 通道；IrisCube 官方页列出图像分类功能。其他型号能力需以项目所用型号官方规格为准。",
    business: "适配取决于标签、输入波段、部署算力和输出格式，不承诺跨设备迁移效果。",
    application: "作物类型、树种、塑料、烟叶除杂、墨迹品牌、藻华类别。官网工业检测与公安刑侦、农业类型识别都对得上。",
    hook: "实验室 SHIS 分类模型 → 同一标签体系部署到 SKY 航飞，打「空地一致」。",
    fits: [
      fit("sky-w417", "direct", "地物/作物分类主路径"),
      fit("max-s810", "direct", "水体/植被/裸土等粗类"),
      fit("shis-n220", "direct", "物证与材料"),
      fit("vix-s230", "direct", "工业高速分类"),
      fit("svc-2p4m30", "adapt", "需以项目所用型号官方规格为准"),
      fit("iriscube", "adapt", "已有分类 UI，做后端"),
      fit("hsc-sc035", "adapt", "8 通道浅层类别"),
    ],
  },
  {
    id: "35_spectral_matching",
    verdict: "光谱库比对。高光谱适用，多光谱不稳定。物证、材料与特定目标检索是主要应用。",
    product: "SAM 吃连续谱。SKY/VIX/SHIS 直接。MAX 7 维角度不稳定。对方物证文保、材料种类识别、宝石等场景就是光谱库逻辑。IrisCube 目标提取有相近叙事。",
    business: "适合「已知目标、缺标注」的项目：某污染物、某涂料、某墨水。比深度学习更易向公安/海关解释。合作可共建行业光谱库，存在光谱云，模型和硬件绑定。",
    application: "官网公安刑侦、文物笔墨、工业材料、污染源。农业大类分类不如 34。",
    hook: "从 SHIS 物证光谱库起步，库格式与 SAM 接口标准化后复用到 VIX/SKY。",
    fits: [
      fit("shis-n220", "direct", "实验室光谱库主场"),
      fit("sky-w417", "direct", "野外已知地物检索"),
      fit("vix-w330", "direct", "便携比对"),
      fit("vix-s230", "direct", "SWIR 材料指纹"),
      fit("iriscube", "adapt", "目标提取可对接 SAM"),
      fit("max-s810", "adapt", "7 维可做，可分性差"),
    ],
  },
  {
    id: "36_cnn1d_classify",
    verdict: "沿光谱的深度学习。只给高光谱。MAX/SVC 谱长不够，不要写进方案。",
    product: "SKY 1200 点、VIX/SHIS 连续谱才有「谱形」。7–8 通道 1D-CNN 是过拟合玩具。训练依赖 26 的样本和云平台 GPU。",
    business: "用来对标国际论文、打动科研客户。量产农服仍以 34 为主。合作放在光谱云「高光谱模型」层，明确输入是立方体不是多光谱 TIFF。",
    application: "细类识别：品种、病害早期谱形、精细材料。需要标注。",
    hook: "科研云套餐，与 26/39 一起，不进 MAX 报价单。",
    fits: [
      fit("sky-w417", "direct", "谱形信息充足"),
      fit("vix-w330", "direct", "全谱近距"),
      fit("shis-n220", "direct", "实验室标注质量高"),
      fit("cloud", "adapt", "训练载体"),
      fit("max-s810", "no", "7 点无谱形"),
      fit("hsc-sc035", "no", "8 通道不够 1D-CNN"),
    ],
  },
  {
    id: "37_cnn3d_classify",
    verdict: "空谱三维卷积，业界论文主流。高光谱正射后最合适。",
    product: "SKY 正射立方体是理想输入。实验室 SHIS 高空间分辨率也适合。MAX 可退化成 2D+浅谱，效果接近普通语义分割。边缘 SVC/HSC 算力与通道都不适合 3D-CNN。",
    business: "适配取决于空谱立方体、标注量、显存和推理时延，不承诺效果。",
    application: "复杂农田地物、病斑纹理+光谱、工业表面缺陷。",
    hook: "选一块 SKY 示范田做 HybridSN 类模型，作为光谱云行业模型样板。",
    fits: [
      fit("sky-w417", "direct", "空谱立方体主场"),
      fit("shis-n220", "direct", "高空间×光谱"),
      fit("vix-w330", "direct", "近距空谱"),
      fit("max-s810", "adapt", "退化为浅谱 2D"),
      fit("cloud", "adapt", "GPU 推理"),
      fit("svc-2p4m30", "no", "边缘视频不宜 3D-CNN"),
    ],
  },
  {
    id: "38_transformer_classify",
    verdict: "高精度复杂场景。只要高光谱和标注预算，不要对多光谱和边缘相机承诺。",
    product: "与 37 类似，更吃数据和算力。SKY 科研与大项目。实验室样本可控。MAX/SVC 不值得上 Transformer。",
    business: "适配取决于连续光谱、标注规模和训练算力；未完成项目验证前不得承诺精度。",
    application: "细碎地物、高混杂种植结构、科研竞赛级分类。",
    hook: "联合实验室课题，不进标准 SKU。",
    fits: [
      fit("sky-w417", "direct", "复杂场景高精度"),
      fit("shis-n220", "direct", "实验室可复现"),
      fit("vix-w330", "direct", "全谱"),
      fit("cloud", "adapt", "训练"),
      fit("max-s810", "no", "通道与数据规模不匹配"),
    ],
  },
  {
    id: "39_few_shot_classify",
    verdict: "标注少也能上线。这是工业换线、农业新作物的真实痛点，适合项目制。",
    product: "所有成像产品都缺标注。实验室 SHIS 最容易拍少量样本。机载 SKY 新作物季也需要。MAX 类别粗，少样本收益一般。云平台「降低开发难度」的话术正好对上。",
    business: "对方客户不可能每换一种塑料、一种病害就标一万张。少样本是从 PoC 到产线的桥梁。合同按「新类 1 天适应」卖服务，而不是卖一个模型文件。",
    application: "工业新料号、新病害、新树种。官网定制化服务客户画像。",
    hook: "用 VIX 工业换料或 SHIS 新墨水做「10 张样本上线」演示。",
    fits: [
      fit("shis-n220", "direct", "实验室少量样本可控"),
      fit("vix-s230", "direct", "产线换料"),
      fit("sky-w417", "adapt", "新作物季，需现场标"),
      fit("max-s810", "adapt", "粗类少样本收益一般"),
      fit("cloud", "adapt", "模型快速部署叙事"),
    ],
  },
  {
    id: "40_detect_segment",
    verdict: "病斑、杂草、缺陷等空间目标。机载和实验室做事后复核与面积统计。",
    product: "MAX/SKY 做田间病斑与倒伏区域；SHIS/VIX 做近距病斑与工业瑕疵；SVC 能力需以项目所用型号官方规格为准。HSC 高帧率适合运动缺陷。输出应是掩膜/框，不是整幅一个类。",
    business: "比整图分类更好报价：按「检出事件」给水务、农服、产线。注意与 SVC 边缘算法分工：边缘实时告警用他们的，事后复核与面积统计用我们的，避免抢固件。",
    application: "官网病虫害、倒伏、溢油、包装品控、LED/晶圆外观（需确认波段）。",
    hook: "机载出病斑面积，SVC 出实时告警，两套接口同一套标签。",
    fits: [
      fit("sky-w417", "direct", "田间斑块检测"),
      fit("max-s810", "direct", "病害/倒伏区域"),
      fit("svc-2p4m30", "adapt", "需以项目所用型号官方规格为准"),
      fit("vix-s230", "direct", "产线缺陷"),
      fit("shis-n220", "direct", "近距病斑/痕迹"),
      fit("hsc-sc035", "adapt", "高速快照缺陷"),
    ],
  },
  {
    id: "41_unmixing",
    verdict: "亚像元占比。只有密光谱成立。MAX 7 通道欠定，不要承诺。",
    product: "SKY 航飞混合像元（土+苗+枯叶）是真问题。实验室高光谱也可做端元。多光谱解混在数学上不稳。工业若纯物质分选，分类往往够，解混用于混合物。",
    business: "适配取决于波段数、端元可分性和线性混合假设，不承诺业务效果。",
    application: "稀疏植被覆盖度、矿物/材料混合、藻华与水体混合。",
    hook: "SKY 出苗期覆盖度试点，用解混比例代替 NDVI 阈值。",
    fits: [
      fit("sky-w417", "direct", "航飞混合像元"),
      fit("vix-w330", "direct", "近距混合物"),
      fit("shis-n220", "direct", "实验室端元"),
      fit("max-s810", "no", "7 通道欠定"),
      fit("svc-2p4m30", "no", "离散通道数量与覆盖需以项目所用型号官方规格为准；当前不按连续谱解混接入"),
    ],
  },
  {
    id: "42_anomaly_detect",
    verdict: "找不像周围的点。工业除杂、农田胁迫都能讲，且常无需标注。",
    product: "RX 需要足够样本估计背景协方差。SKY-W417、VIX-W330 等连续光谱输入可接入；MAX-S810 为离散少通道，需单独评估协方差稳定性。其他型号能力需以项目所用型号官方规格为准。",
    business: "适配取决于背景样本、波段协方差和算力；异常分数不等于原因或业务告警结论。",
    application: "烟叶除杂、塑料异物、溢油、未知病害苗头、物证痕迹。",
    hook: "工业 VIX-S230 除杂；SVC 能力需以项目所用型号官方规格为准。",
    fits: [
      fit("vix-s230", "direct", "高速工业除杂"),
      fit("sky-w417", "direct", "田间光谱异常"),
      fit("svc-2p4m30", "adapt", "需以项目所用型号官方规格为准"),
      fit("shis-n220", "direct", "痕迹/污染点"),
      fit("max-s810", "direct", "空间+浅谱异常"),
      fit("iriscube", "adapt", "无标注叙事可对接"),
    ],
  },
  {
    id: "43_change_detect",
    verdict: "多时相是监测订阅的核心。机载复飞直接用；SVC 是视频时序，要改编。",
    product: "IR-MAD 接收共注册的两期反射率影像，并要求波段与辐射口径可比。连续视频不是当前两景影像对接口；其他型号采集模式需以项目所用型号官方规格为准。",
    business: "把一次性卖相机变成按年监测。水务、农服、林业火险都靠变化。对方云平台存储多期数据后，本算法是「为什么要续费存储」的理由。",
    application: "病虫害扩散、水体变化、砍伐、倒伏前后、应急溢油扩散。",
    hook: "套餐：MAX 定期复飞 + 变化图 + 告警 API，按测区订阅。",
    fits: [
      fit("sky-w417", "direct", "高光谱复飞变化"),
      fit("max-s810", "direct", "农情/水质周报"),
      fit("cloud", "adapt", "多期数据调度"),
      fit("svc-2p4m30", "adapt", "视频时序，需换模型"),
      fit("shis-n220", "adapt", "重复实验前后"),
    ],
  },
  {
    id: "44_postprocess_smooth",
    verdict: "分类图需经图斑整理后方可交付。所有出图斑的产品都应接入这一步。",
    product: "机载分类图小斑剔除后才能进报告。实验室分类图同样。SVC 叠加结果也可做空间平滑，但实时性要求不同。",
    business: "应设为 34/37/40 的默认后处理，不单独作为算法模块。椒盐噪声会被误判为分类器失效。工业像素级分选场景需提供关闭开关。",
    application: "所有专题制图。工业像素级分选有时不能平滑（会吞小异物），要可关闭。",
    hook: "分类接口默认打开，工业模式提供关闭开关。",
    fits: [
      fit("sky-w417", "direct", "专题图整理"),
      fit("max-s810", "direct", "处方图前清理"),
      fit("shis-n220", "direct", "实验室分类图"),
      fit("vix-s230", "adapt", "小异物场景需可关"),
      fit("svc-2p4m30", "adapt", "叠加层平滑"),
    ],
  },
  {
    id: "45_parcel_zonal_stats",
    verdict: "地块分区统计是机载农业、林业、水务产品的闭环输出，对应处方图或统计表的最后一公里。",
    product: "MAX 官方讲处方图植入植保无人机；SKY 更能按地块出均值/分位。输入是指数或分类图 + 地块 GeoJSON。实验室改成 ROI 统计。SVC 改成站点时间序列，不是地块。工业改成批次/工单统计。",
    business: "这是合作最应该盯住的交付物：相机厂商缺「一块地一个数」的业务对象。对方有指数和拼接，缺承包地、告警阈值、API 给农服系统。本算法让硬件方案能进政府耕地项目和农企 SaaS。",
    application: "官网产量预估、耕地调查、草地森林覆盖统计、处方图。实验室课题用 ROI 即可。",
    hook: "用对方一次 MAX/SKY 飞行 + 一份地块界线，出可验收的地块 CSV/GeoJSON，作为联合方案封面。",
    fits: [
      fit("max-s810", "direct", "处方图/地块报表闭环"),
      fit("sky-w417", "direct", "高光谱地块统计更细"),
      fit("cloud", "adapt", "报表 API 部署"),
      fit("shis-n220", "adapt", "改为 ROI 而非承包地"),
      fit("svc-2p4m30", "adapt", "站点统计，不是地块多边形"),
      fit("vix-s230", "adapt", "批次/工单汇总"),
    ],
  },
  {
    id: "46_reci",
    verdict: "RECI 要真红边。MAX 官方若列出红边窄带则可接入；纯 SWIR 相机不能做。",
    product: "需要红边与近红外反射率。SKY-W417 官方覆盖红边区；MAX-S810 是否具备所用红边通道，须以项目所用型号官方规格为准。",
    business: "适配只表示存在红边与近红外输入，不承诺叶绿素含量。",
    application: "密冠层叶绿素相关相对对照。工业 SWIR 分选无关。",
    hook: "接入前核对红边中心波长与反射率输入。",
    fits: [
      fit("max-s810", "adapt", "须确认官方红边通道"),
      fit("sky-w417", "direct", "连续谱含红边"),
      fit("vix-n320", "direct", "便携 VNIR 含红边"),
      fit("vix-s230", "no", "无红边波段"),
    ],
  },
  {
    id: "47_gndvi",
    verdict: "GNDVI 只要绿光和近红外，波段条件与 NDVI 同类，只是可见光端换成绿光。",
    product: "VNIR 产品通常可选取绿光与近红外。纯 SWIR 不能做。",
    business: "适配只表示具备绿光与近红外输入。",
    application: "同一处理链下的相对绿度。不能直接当叶绿素含量。",
    hook: "接入前按传感器光谱响应选绿光窗口。",
    fits: [
      fit("max-s810", "direct", "多光谱含绿/NIR 时可做"),
      fit("sky-w417", "direct", "全谱可选取绿/NIR"),
      fit("vix-s230", "no", "纯 SWIR，无绿光"),
    ],
  },
  {
    id: "48_osavi",
    verdict: "OSAVI 与 NDVI 相同波段，土壤背景重时作为对照指数。",
    product: "红光与近红外即可。L 默认 0.16 是文献常用值，不是现场标定。",
    business: "适配只表示具备红光近红外输入。",
    application: "稀疏植被、土壤背景明显时的相对绿度。不是叶面积。",
    hook: "接入前核对流 L 是否保持 0.16。",
    fits: [
      fit("max-s810", "direct", "与 NDVI 相同输入"),
      fit("sky-w417", "direct", "标准波段可复现"),
      fit("vix-s230", "no", "无红光波段"),
    ],
  },
  {
    id: "49_arvi",
    verdict: "ARVI 需要可靠蓝光。蓝光差时不要承诺比 NDVI 更稳。",
    product: "需要蓝、红、近红外。蓝光信噪差的机型应标明限制。",
    business: "适配不表示已经完成大气校正。",
    application: "气溶胶残差可见时的相对绿度对照。",
    hook: "接入前核对蓝光通道质量，不要用 ARVI 替代大气校正。",
    fits: [
      fit("sky-w417", "direct", "蓝/红/NIR 可选取"),
      fit("max-s810", "adapt", "须确认蓝光通道可用"),
      fit("vix-s230", "no", "无可见光蓝光"),
    ],
  },
  {
    id: "50_vari",
    verdict: "VARI 只用可见光，没有近红外的相机也能接；有近红外时不要拿它替代 NDVI。",
    product: "RGB 或 VNIR 的蓝绿红即可。纯 SWIR 不能做。",
    business: "适配只表示可见光三通道可用，不承诺覆盖度百分数。",
    application: "仅有可见光时的相对覆盖示意。",
    hook: "接入前确认通道是定标反射率或至少辐射一致，不要用未定标 JPEG 声称物理 VARI。",
    fits: [
      fit("max-s810", "direct", "可见光通道可做"),
      fit("hsc-sc035", "direct", "可见光多通道"),
      fit("vix-s230", "no", "纯 SWIR"),
    ],
  },
  {
    id: "51_lai_index",
    verdict: "这是 EVI 线性经验式，不是 #33 PROSAIL。有蓝红近红外就能跑，但不能当化验叶面积卖。",
    product: "波段需求与 EVI 相同。输出文件名是 lai_index.tif，不要和物理反演的 lai.tif 混。",
    business: "适配不承诺叶面积真值。",
    application: "指数菜单里的经验叶面积示意。要机理反演走 #33。",
    hook: "材料里写明演示数据系数，避免和 #33 混成一个 SKU。",
    fits: [
      fit("max-s810", "adapt", "可算经验式，须标明不是物理反演"),
      fit("sky-w417", "direct", "EVI 波段可复现"),
      fit("vix-s230", "no", "缺可见光与近红外组合"),
    ],
  },
  {
    id: "52_nbr",
    verdict: "NBR 必须有真实 SWIR。MAX 官方波段若不含短波红外则不能做。",
    product: "SKY-W417 官方 400–1700 nm 覆盖演示数据所用短波红外窗口；Landsat NBR 常用 SWIR2 约 2.1 μm，须在项目里写清窗口。",
    business: "适配只表示存在 SWIR 输入，不承诺过火面积。",
    application: "过火相对对照。不是灾损金额。",
    hook: "接入前核对 SWIR 中心波长，避免把 1600 nm 结果写成 Landsat SWIR2 产品。",
    fits: [
      fit("sky-w417", "direct", "覆盖短波红外"),
      fit("vix-s230", "adapt", "有 SWIR，须另配近红外或全谱数据"),
      fit("max-s810", "no", "官方波段不含短波红外"),
    ],
  },
  {
    id: "53_sipi",
    verdict: "SIPI 要蓝、红、近红外。蓝光差时分母和分子都会受影响。",
    product: "VNIR 产品通常可做。纯 SWIR 不能做。",
    business: "适配不承诺色素含量。",
    application: "色素比值相关相对对照。",
    hook: "接入前核对流蓝光质量，并说明 NIR 接近红光时数值不稳定。",
    fits: [
      fit("sky-w417", "direct", "蓝/红/NIR 可选取"),
      fit("max-s810", "adapt", "须确认蓝光通道"),
      fit("vix-s230", "no", "无可见光蓝光"),
    ],
  },
  {
    id: "54_gci",
    verdict: "GCI 要绿光和近红外，不要求红边。不要和 RECI 混成一个产品。",
    product: "VNIR 可选取绿光与近红外。纯 SWIR 不能做。",
    business: "适配不承诺叶绿素含量。",
    application: "无红边时的叶绿素相关相对对照。",
    hook: "接入前按传感器选绿光窗口，并与 RECI 分开展示。",
    fits: [
      fit("max-s810", "direct", "绿/NIR 可做"),
      fit("sky-w417", "direct", "全谱可选取"),
      fit("vix-s230", "no", "无绿光"),
    ],
  },
  {
    id: "55_ndsi",
    verdict: "NDSI 必须有真实 SWIR。与 MNDWI 同型，材料里必须写清用途是雪不是水。",
    product: "需要绿光与短波红外。MAX 若无 SWIR 则不能做。",
    business: "适配不承诺积雪面积。",
    application: "积雪相对格局。水体请走 #30 MNDWI。",
    hook: "接入前核对 SWIR，并避免与 MNDWI 共用同一张阈值表。",
    fits: [
      fit("sky-w417", "direct", "绿光与 SWIR 都覆盖"),
      fit("vix-w330", "direct", "便携全谱"),
      fit("max-s810", "no", "无短波红外则不能做 NDSI"),
    ],
  },
];
