-- 参数字典：仅空库首次写入。已有行 ON CONFLICT 不覆盖（方案与取值以数据库为准）。
INSERT INTO param_definitions (key, stage_id, value_type, default_value, description, advanced, sort_order) VALUES
('input_dir', 'S0_io', 'path', 'null'::jsonb, $d$输入测区架次目录。容器内约定 /data/input/<测区名>/<架次目录>，例如 /data/input/MAX_20251017/MAX_20251017_001。只读扫描，禁止把输出写进此树。$d$, false, 10),
('output_dir', 'S0_io', 'path', 'null'::jsonb, $d$本次运行输出根。容器内约定 /data/output/runs/<任务名>，对应宿主机 server/data/output/runs/<任务名>。其下生成 拼图结果/、附件/、cache/、log/ 等。$d$, false, 20),
('memory_gb', 'S0_io', 'float', '0'::jsonb, $d$本任务进程内存预算（GB）。0 表示按容器当前可用内存自动下调并行度。全量 668 张建议 36。须把 Docker 引擎内存调到不少于此值。$d$, false, 25),
('cache_dir', 'S0_io', 'path', 'null'::jsonb, $d$特征/空三缓存目录。续跑可复用，避免重复提特征。默认 {output_dir}/cache/features。$d$, false, 30),
('log_dir', 'S0_io', 'path', 'null'::jsonb, $d$明码文本日志目录；执行记录保存此路径便于溯源。默认 {output_dir}/log。$d$, false, 40),
('process_dir', 'S0_io', 'path', 'null'::jsonb, $d$中间过程图/调试产物根（与拼图结果分离）。默认 {output_dir}/附件。$d$, true, 50),
('products_dir_name', 'S0_io', 'string', '"拼图结果"'::jsonb, $d$成果子目录名（与交付目录约定一致）。$d$, true, 60),
('run_mode', 'S0_io', 'enum', '"full"'::jsonb, $d$运行模式：full 全流程；until_stage 跑到 stop_after_stage 后等待继续；step 每阶段确认。$d$, false, 70),
('start_stage', 'S0_io', 'enum', '"S0_io"'::jsonb, $d$从哪一阶段开始（须有检查点或从 S0）。$d$, false, 80),
('stop_after_stage', 'S0_io', 'enum', 'null'::jsonb, $d$until_stage 时必填：跑完该阶段后进入 awaiting_continue。$d$, false, 90),
('preset', 'S0_io', 'enum', 'null'::jsonb, $d$快捷预设：通用=全波段；RGB 快速预览=仅 Color 正射。$d$, false, 100),
('benchmark_dir', 'S0_io', 'path', 'null'::jsonb, $d$调试对照 拼图结果：只写比对报告，不改出图。$d$, false, 110),
('match_reference_color', 'S0_io', 'bool', 'false'::jsonb, $d$调试套色。合格主路径保持关闭。$d$, true, 120),
('max_index', 'S1_catalog', 'int', 'null'::jsonb, $d$只扫描文件名编号 ≤ 该值的曝光，便于小范围调试。$d$, false, 10),
('max_frames', 'S1_catalog', 'int', 'null'::jsonb, $d$过滤后最多使用前 N 个可用曝光。$d$, false, 20),
('min_agl_m', 'S1_catalog', 'float', '5.0'::jsonb, $d$相对航高低于此值视为地面/无效帧丢弃。$d$, false, 30),
('max_tilt_deg', 'S1_catalog', 'float', '60.0'::jsonb, $d$光轴偏离天底超过此角度丢弃（REQ-03-03）。$d$, false, 40),
('drop_white_panel', 'S1_catalog', 'bool', 'true'::jsonb, $d$丢弃文件名角色 _W 白板帧（不参与重建）。$d$, false, 50),
('require_pos', 'S1_catalog', 'bool', 'true'::jsonb, $d$无 XMP/EXIF POS 的帧丢弃。$d$, true, 60),
('primary_band', 'S2_at', 'enum', '"Color"'::jsonb, $d$主波段：仅此波段做特征匹配与空三；其余波段迁移外方位。$d$, false, 10),
('workers_at', 'S2_at', 'int', '12'::jsonb, $d$空三/特征提取并行度。$d$, false, 20),
('sigma_xy_m', 'S2_at', 'float', '3.0'::jsonb, $d$GNSS 平面先验标准差（米）。$d$, true, 30),
('sigma_z_m', 'S2_at', 'float', '5.0'::jsonb, $d$GNSS 高程先验标准差（米）。$d$, true, 40),
('sigma_attitude_deg', 'S2_at', 'float', '3.0'::jsonb, $d$IMU 姿态先验标准差（度）。$d$, true, 50),
('outlier_threshold_px', 'S2_at', 'float', '6.0'::jsonb, $d$重投影外点阈值（像素）。$d$, true, 60),
('calibrate_intrinsics', 'S2_at', 'bool', 'true'::jsonb, $d$是否分阶段释放内参自标定。$d$, true, 70),
('dsm_gsd', 'S3_dense', 'float', 'null'::jsonb, $d$DSM 地面分辨率（米）。空则按航高/焦距估计，正射为其一半。$d$, false, 10),
('reuse_dsm', 'S3_dense', 'path', 'null'::jsonb, $d$若指定，跳过密集匹配，复用已有 DSM.tif。$d$, false, 20),
('n_layers', 'S3_dense', 'int', '48'::jsonb, $d$沿高程扫描层数；越大越慢越细。$d$, true, 30),
('z_margin_m', 'S3_dense', 'float', 'null'::jsonb, $d$高程搜索半宽（米）。空则按稀疏点 p90−p10 起伏估计。$d$, true, 40),
('workers_dense', 'S3_dense', 'int', 'null'::jsonb, $d$密集匹配进程数，默认 CPU-1。$d$, false, 50),
('spike_tolerance_m', 'S4_dsm', 'float', '2.5'::jsonb, $d$相对中值超过此高差视为尖刺剔除。$d$, true, 10),
('max_fill_gap_m', 'S4_dsm', 'float', '40.0'::jsonb, $d$空洞填充最大跨度（米）。$d$, true, 20),
('bands', 'S5_ortho', 'string[]', '["Color","450nm","550nm","650nm","720nm","750nm","800nm","850nm"]'::jsonb, $d$参与正射的波段。仅 RGB 快速预览时设为 ["Color"]。$d$, false, 10),
('color_correction', 'S5_ortho', 'enum', '"off_for_ms"'::jsonb, $d$RGB 可开增益均衡；多光谱强制禁用保辐射。$d$, true, 20),
('seamline_enabled', 'S5_ortho', 'bool', 'true'::jsonb, $d$是否计算拼接线。$d$, false, 30),
('workers_ortho', 'S5_ortho', 'int', 'null'::jsonb, $d$正射并行度。$d$, false, 40),
('write_pdf_report', 'S6_report', 'bool', 'true'::jsonb, $d$生成质量报告.pdf。$d$, false, 10),
('write_json_report', 'S6_report', 'bool', 'true'::jsonb, $d$生成机器可读质量 JSON。$d$, false, 20)
ON CONFLICT (key) DO NOTHING;
