# 算法目录元数据（编号对齐《采集到算法-算法清单》）
ALGORITHMS = [
    {"id": "01_flight_planning", "title": "航线规划与覆盖优化", "level": "L0前", "implemented": True},
    {"id": "02_sync_timestamp", "title": "同步曝光与时间戳对齐", "level": "L0", "implemented": True},
    {"id": "03_pos_solution", "title": "POS解算（GPS+IMU）", "level": "L0", "implemented": True},
    {"id": "04_flight_qc", "title": "架次质检（丢帧/过曝）", "level": "L0", "implemented": True},
    {"id": "05_cloud_shadow", "title": "云/云影检测", "level": "L0", "implemented": True},
    {"id": "06_dark_current", "title": "暗电流校正", "level": "L0→L1", "implemented": True},
    {"id": "07_bad_pixel", "title": "坏线/坏像元修复", "level": "L0→L1", "implemented": True},
    {"id": "08_destriping", "title": "条带噪声去除", "level": "L0→L1", "implemented": True},
    {"id": "09_smile_keystone", "title": "光谱微笑/关键畸变校正", "level": "L0→L1", "implemented": True},
    {"id": "10_radiance_calibration", "title": "辐射定标 DN→辐亮度", "level": "L0→L1", "implemented": True},
    {"id": "11_relative_radiometric", "title": "相对辐射归一", "level": "L1", "implemented": True},
    {"id": "12_panel_reflectance", "title": "白板/灰板反射率定标", "level": "L1→L2", "implemented": True},
    {"id": "13_atmospheric_correction", "title": "大气校正", "level": "L1→L2", "implemented": True},
    {"id": "14_brdf_correction", "title": "BRDF/观测几何校正", "level": "L1→L2", "implemented": True},
    {"id": "15_geo_locate", "title": "几何粗校正/地理定位", "level": "L1→L2", "implemented": True},
    {"id": "16_orthorectify", "title": "正射校正", "level": "L1→L2", "implemented": True},
    {"id": "17_mosaic", "title": "影像匹配与镶嵌", "level": "L2", "implemented": True},
    {"id": "18_color_balance", "title": "匀色与接缝线优化", "level": "L2", "implemented": True},
    {"id": "19_multi_source_register", "title": "多源配准 HSI-RGB-矢量", "level": "L2", "implemented": True},
    {"id": "20_bad_band_remove", "title": "坏波段剔除与光谱去噪", "level": "L2", "implemented": True},
    {"id": "21_savgol_smooth", "title": "Savitzky-Golay平滑", "level": "L2", "implemented": True},
    {"id": "22_normalize", "title": "标准化/归一化", "level": "L2", "implemented": True},
    {"id": "23_pca", "title": "PCA/MNF降维", "level": "L2", "implemented": True},
    {"id": "24_band_select", "title": "波段/特征选择", "level": "L2", "implemented": True},
    {"id": "25_superpixel", "title": "超像素/对象分割", "level": "L2", "implemented": True},
    {"id": "26_patch_build", "title": "Patch/样本构建", "level": "L2", "implemented": True},
    {"id": "27_ndvi", "title": "NDVI植被指数", "level": "L3", "implemented": True},
    {"id": "28_ndre", "title": "NDRE红边植被指数", "level": "L3", "implemented": True},
    {"id": "29_evi_savi", "title": "EVI/SAVI/MSAVI", "level": "L3", "implemented": True},
    {"id": "30_ndmi_ndwi", "title": "NDMI/NDWI/MNDWI", "level": "L3", "implemented": True},
    {"id": "31_red_edge_params", "title": "红边位置与光谱特征参数", "level": "L3", "implemented": True},
    {"id": "32_regression_inversion", "title": "经验回归反演", "level": "L3", "implemented": True},
    {"id": "33_physical_inversion", "title": "辐射传输物理反演", "level": "L3", "implemented": True},
    {"id": "34_svm_rf_classify", "title": "SVM/随机森林分类", "level": "L3", "implemented": True},
    {"id": "35_spectral_matching", "title": "光谱匹配分类(SAM)", "level": "L3", "implemented": True},
    {"id": "36_cnn1d_classify", "title": "1D-CNN/RNN光谱分类", "level": "L3", "implemented": True},
    {"id": "37_cnn3d_classify", "title": "2D/3D-CNN空谱分类", "level": "L3", "implemented": True},
    {"id": "38_transformer_classify", "title": "Transformer/GCN分类", "level": "L3", "implemented": True},
    {"id": "39_few_shot_classify", "title": "少样本/迁移学习分类", "level": "L3", "implemented": True},
    {"id": "40_detect_segment", "title": "语义分割/目标检测", "level": "L3", "implemented": True},
    {"id": "41_unmixing", "title": "混合像元分解", "level": "L3", "implemented": True},
    {"id": "42_anomaly_detect", "title": "异常检测", "level": "L3", "implemented": True},
    {"id": "43_change_detect", "title": "多时相变化检测", "level": "L3", "implemented": True},
    {"id": "44_postprocess_smooth", "title": "分类后处理平滑/小斑剔除", "level": "L3→L4", "implemented": True},
    {"id": "45_parcel_zonal_stats", "title": "地块汇总与专题统计", "level": "L4", "implemented": True},
]
