"""算法 12–26 的专属输出知识。"""
from __future__ import annotations

from typing import Any

from .common import make_output


def _summary(what: str, value: str, caution: str) -> dict[str, str]:
    """构造算法级摘要。"""
    return {"what": what, "value": value, "caution": caution}


def _output(
    path: str,
    label: str,
    *,
    description: str,
    effect: str,
    business: str,
    interpretation: str,
    check: str,
    abnormal: list[str],
    downstream: str,
    warning: str,
    **kwargs: Any,
) -> dict[str, Any]:
    """构造具备完整专业语义的输出记录。"""
    return make_output(
        path,
        label,
        description=description,
        effect=effect,
        business_meaning=business,
        interpretation=interpretation,
        quality_check=check,
        abnormal_signs=abnormal,
        downstream_use=downstream,
        misuse_warning=warning,
        **kwargs,
    )


def _metric(
    path: str,
    label: str,
    description: str,
    business: str,
    interpretation: str,
    check: str,
    warning: str,
    downstream: str,
    **kwargs: Any,
) -> dict[str, Any]:
    """声明一个有明确计算口径和使用边界的结果字段。"""
    return _output(
        path,
        label,
        description=description,
        effect=f"记录本次处理的{label}，供结果解释与复算。",
        business=business,
        interpretation=interpretation,
        check=check,
        abnormal=[warning],
        downstream=downstream,
        warning=warning,
        **kwargs,
    )


L2_OUTPUT_KNOWLEDGE: dict[str, dict[str, Any]] = {
    "12_panel_reflectance": {
        "summary": _summary(
            "以参考板和暗点光谱执行单点经验线反射率定标。",
            "把辐亮度或可比数字量转换为可用于指数和分类的近似反射率。",
            "当前实现只有一个参考板反射率和暗点，结果截到 [0,1.5]；不是多板线性回归或完整大气校正。",
        ),
        "outputs": {
            "files.reflectance_tif": _output(
                "files.reflectance_tif", "经验线反射率立方体",
                description="按 ρ_panel×(L-L_dark)/(L_panel-L_dark) 逐波段计算并截到 [0,1.5] 的 GeoTIFF。",
                effect="利用参考板与暗点校正各波段的照明和响应尺度。",
                business="形成植被指数、光谱比较和分类可直接读取的反射率近似产品。",
                interpretation="空间网格与输入一致；各波段仍按输入顺序排列，超出常见反射率范围的值可能被截到 1.5。",
                check="抽查像元按公式复算，核对参考板 ROI、亮暗百分位、波段数及 [0,1.5] 范围。",
                abnormal=["大片 0 或 1.5 表示参考板、暗点或数据尺度可能不合适"],
                downstream="用于指数计算、光谱特征和分类前处理。",
                warning="不得把单板加暗点的经验线结果宣称为经多板回归或大气辐射传输验证的绝对地表反射率。",
                format_name="GeoTIFF", vis="raster_cube",
                related_outputs=["data.panel_reflectance", "data.panel_radiance", "data.dark_radiance"],
            ),
            "data.panel_reflectance": _metric(
                "data.panel_reflectance", "参考板反射率", "公式中使用的参考板反射率标称值或逐波段数组。",
                "决定经验线输出的绝对比例尺度。", "标量对全部波段共用；数组应按输入波段顺序解释。",
                "核对参考板证书、波段顺序和观测条件。", "不得用不匹配波段或老化参考板的标称值。",
                "用于复算经验线公式和结果追溯。", unit="比例", vis="array",
            ),
            "data.panel_radiance": _metric(
                "data.panel_radiance", "参考板光谱", "从指定 ROI 或最亮百分位像元均值提取的动态逐波段光谱。",
                "提供经验线分母中的亮参考端。", "第 i 项对应输入第 i 波段，不假定固定波段数。",
                "核对动态数组长度等于实际波段数，并检查参考区域是否均匀、未饱和。", "饱和或混入背景会使反射率尺度失真。",
                "用于逐波段经验线复算和参考板质检。", unit="输入辐射量", range_text="动态长度：每个输入波段一项", vis="spectrum",
            ),
            "data.dark_radiance": _metric(
                "data.dark_radiance", "暗点光谱", "由影像最暗百分位像元均值估计的动态逐波段暗端光谱。",
                "提供经验线公式的暗端基线。", "第 i 项对应输入第 i 波段；这是场景暗点估计而非实测暗帧。",
                "核对数组长度、暗区位置及 panel_radiance-dark_radiance 是否远离零。", "把暗地物估计当传感器暗电流会夸大物理可追溯性。",
                "用于经验线暗端修正与异常分母排查。", unit="输入辐射量", range_text="动态长度：每个输入波段一项", vis="spectrum",
            ),
            "data.min": _metric(
                "data.min", "最小反射率", "输出立方体全局最小值。", "快速检查暗端与截零情况。",
                "实现截值后应位于 [0,1.5]。", "从 GeoTIFF 排除 NoData 后复算。", "单个最小值不能代表各波段质量。",
                "用于范围质检。", unit="比例", range_text="[0, 1.5]", vis="number",
            ),
            "data.max": _metric(
                "data.max", "最大反射率", "输出立方体全局最大值。", "提示亮端截值或参考板尺度异常。",
                "实现截值后应位于 [0,1.5]；等于 1.5 可能表示已发生上限裁剪。", "从 GeoTIFF 复算并定位波段和区域。",
                "不得把 1.5 解释为未经裁剪的真实反射率。", "用于亮端质量检查。", unit="比例", range_text="[0, 1.5]", vis="number",
            ),
            "data.mean": _metric(
                "data.mean", "平均反射率", "输出立方体全部像元和波段的全局均值。", "概括本景经验线定标后的总体尺度。",
                "应位于 min 与 max 之间，且受地物和波段组成共同影响。", "与 GeoTIFF 全局均值及各波段均值交叉核对。",
                "不得跨地物组成或波段范围不同的数据直接比较。", "用于批次尺度快检。", unit="比例", vis="number",
            ),
        },
    },
    "13_atmospheric_correction": {
        "summary": _summary(
            "使用 Chavez DOS2 暗目标法估计路径辐射并计算表面反射率。",
            "在缺少完整大气参数时提供可复现的暗目标近似校正。",
            "当前实现以太阳天顶角近似双向透过率、必要时用 gain/offset 转辐亮度，并把结果截到 [0,1.5]；不等同 6S。",
        ),
        "outputs": {
            "files.reflectance_tif": _output(
                "files.reflectance_tif", "DOS2 反射率立方体",
                description="按逐波段暗百分位估计路径辐射后执行 DOS2，并截到 [0,1.5] 的 GeoTIFF。",
                effect="降低加性路径辐射对地表光谱的影响。",
                business="为跨区域光谱比较、指数和分类提供近似表面反射率。",
                interpretation="波段顺序与 wavelengths_nm 对应；结果依赖太阳角、日期、输入辐亮度单位和暗目标假设。",
                check="核对输入是否按 W/m²/sr/μm 尺度进入公式，检查波长数组、暗目标区域和裁剪比例。",
                abnormal=["大片 0 或 1.5 常见于单位、gain/offset、太阳角或暗目标估计错误"],
                downstream="用于定量光谱分析和 L2 产品生成。",
                warning="不得把 DOS2 近似结果包装成使用水汽、气溶胶和传感器响应函数的完整辐射传输反演。",
                format_name="GeoTIFF", vis="raster_cube",
                related_outputs=["data.haze_radiance", "data.wavelengths_nm", "data.solar_zenith", "data.doy"],
            ),
            "data.solar_zenith": _metric(
                "data.solar_zenith", "太阳天顶角", "DOS2 公式实际使用的太阳天顶角。",
                "控制入射余弦和当前实现的透过率近似。", "0° 为太阳位于天顶方向；角度增大时余弦减小。",
                "核对采集时间地点的太阳位置及度单位。", "误填太阳高度角会造成系统性尺度错误。",
                "用于公式复算和元数据追溯。", unit="度", vis="number",
            ),
            "data.doy": _metric(
                "data.doy", "年积日", "计算日地距离时使用的年内日序号。",
                "修正季节性日地距离变化对太阳辐照度尺度的影响。", "应对应实际采集日期。",
                "由日期独立换算并核对合法范围。", "跨年或把月份当 DOY 会使尺度错误。",
                "用于日地距离复算。", unit="天序号", range_text="通常 1–365/366", vis="number",
            ),
            "data.haze_radiance": _metric(
                "data.haze_radiance", "路径辐射估计", "按动态波段顺序输出的 DOS2 路径辐射数组。",
                "表征每个波段从输入辐亮度中扣除的加性大气项。", "第 i 项对应 wavelengths_nm[i] 与输出第 i 波段。",
                "核对动态数组长度等于实际波段数，检查非负性及与暗端辐亮度的关系。", "不能把暗目标场景估计当作实测大气剖面。",
                "用于 DOS2 复算和逐波段校正诊断。", unit="输入辐亮度单位", range_text="动态长度：每个实际波段一项", vis="spectrum",
            ),
            "data.wavelengths_nm": _metric(
                "data.wavelengths_nm", "波长数组", "DOS2 使用的动态中心波长数组；长度不匹配时实现会改用 450–850 nm 等间隔默认值。",
                "把 ESUN 插值和路径辐射对应到实际波段。", "第 i 项对应输入与输出第 i 波段。",
                "核对动态数组长度、单调性及是否来自真实传感器元数据。", "默认等间隔波长不能替代真实中心波长标定。",
                "用于光谱轴标注和公式复算。", unit="nm", range_text="动态长度：每个实际波段一项", vis="spectrum",
            ),
            "data.min": _metric(
                "data.min", "最小 DOS2 反射率", "校正结果全局最小值。", "提示暗端裁剪和校正强度。",
                "实现截值后位于 [0,1.5]。", "从输出栅格复算。", "不能由全局最小值判断所有波段质量。",
                "用于范围质检。", unit="比例", range_text="[0, 1.5]", vis="number",
            ),
            "data.max": _metric(
                "data.max", "最大 DOS2 反射率", "校正结果全局最大值。", "提示亮端裁剪和单位异常。",
                "等于 1.5 可能已触发实现上限。", "从输出栅格复算并定位极值。", "不得把裁剪值当真实高反射率。",
                "用于范围质检。", unit="比例", range_text="[0, 1.5]", vis="number",
            ),
        },
    },
    "14_brdf_correction": {
        "summary": _summary(
            "使用固定 Ross-Thick/Li-Sparse 核权重，按列视场角把反射率归一到天底。",
            "减弱宽视场影像中由观测几何引起的横向亮度梯度。",
            "当前视天顶角仅按列从负边缘角线性变化到正边缘角，核权重为参数或默认值，不是逐像元姿态与地表反演。",
        ),
        "outputs": {
            "files.cube_tif": _output(
                "files.cube_tif", "BRDF 天底归一立方体",
                description="按列线性视天顶角和 Ross-Li 核比值缩放各波段的 GeoTIFF。",
                effect="将当前观测几何近似归一到视天顶角 0°。",
                business="提高宽幅航带内部及多角度数据的相对辐射一致性。",
                interpretation="同一列全部行和波段共用几何因子；未使用逐像元地形、姿态或波段专属核参数。",
                check="比较归一前后横向剖面并核对角度符号、边缘角和核参数，确认没有放大异常。",
                abnormal=["边缘亮暗差增大表示角度符号或核参数不适配"],
                downstream="用于镶嵌、时序比较和光谱分析前的角度近似校正。",
                warning="不得宣称结果基于逐像元观测几何、地形 BRDF 或从数据反演的核系数。",
                format_name="GeoTIFF", vis="raster_cube",
            ),
            "data.solar_zenith": _metric(
                "data.solar_zenith", "太阳天顶角", "Ross-Li 核计算使用的统一太阳天顶角。",
                "决定天底参考核和当前观测核。", "全景使用同一角度，单位为度。",
                "核对采集时间地点和角度定义。", "太阳高度角与天顶角混用会反向解释几何。",
                "用于 BRDF 因子复算。", unit="度", vis="number",
            ),
            "data.view_zenith_edge": _metric(
                "data.view_zenith_edge", "边缘视天顶角", "列向视场模型两端的视天顶角绝对值。",
                "控制从 -edge 到 +edge 的线性列向角度范围。", "中心列接近 0°，两侧符号相反。",
                "依据镜头视场和列数核对。", "该值不是逐像元姿态解或全场最大实测角。",
                "用于重建列向角度数组。", unit="度", vis="number",
            ),
            "data.relative_azimuth": _metric(
                "data.relative_azimuth", "相对方位角", "Ross-Li 核使用的统一太阳—观测相对方位角。",
                "控制散射平面关系。", "全景使用同一度数，不随列或像元变化。",
                "核对太阳方位、航向和角度约定。", "绝对方位与相对方位混用会改变核因子。",
                "用于 BRDF 因子复算。", unit="度", vis="number",
            ),
        },
    },
    "15_geo_locate": {
        "summary": _summary(
            "以单个 POS 点为影像中心，按 GSD 构造 EPSG:4326 北向上仿射。",
            "为无地理参考影像提供快速落图和处理预览。",
            "当前实现不使用姿态旋转、相机畸变、逐行 POS 或地形；yaw 只记录不参与仿射。",
        ),
        "outputs": {
            "files.cube_tif": _output(
                "files.cube_tif", "粗定位立方体",
                description="保持原像元值，以中心经纬度和 GSD 写入 EPSG:4326 北向上仿射的 GeoTIFF。",
                effect="为输入影像赋予近似空间范围和分辨率。",
                business="支持快速地图预览、任务落区核验及后续精校正准备。",
                interpretation="影像中心固定在 lon/lat，未按 yaw、roll、pitch 或地形旋转和纠正。",
                check="在 GIS 中核对中心、范围、像元分辨率和方向，并与控制点或底图比较。",
                abnormal=["整体旋转或局部错位属于简化模型预期限制，巨大平移则需检查经纬度与单位"],
                downstream="用于快速落图和粗配准，不用于精确量测。",
                warning="不得把 POS+GSD 北向上仿射当作摄影测量正射或逐像元精确地理定位。",
                format_name="GeoTIFF", vis="raster_cube",
                related_outputs=["files.meta_json", "data.lon", "data.lat", "data.gsd_m", "data.crs"],
            ),
            "files.meta_json": _output(
                "files.meta_json", "粗定位元数据",
                description="保存中心经纬高、GSD、角分辨率、yaw 和 CRS 的 JSON。",
                effect="把构造仿射所需参数与未参与计算的 yaw 一并留档。",
                business="便于审计粗定位来源和复现空间参考。",
                interpretation="yaw 可为空且当前不改变输出 transform；res_deg 顺序为经度、纬度方向。",
                check="与接口 data 字段和 GeoTIFF transform 逐项核对。",
                abnormal=["元数据与栅格 transform 不一致表示写出或参数传播错误"],
                downstream="用于定位追溯和后续精校正配置。",
                warning="不得根据元数据中存在 yaw 就推断影像已按航向旋转。",
                format_name="JSON", vis="json_table",
            ),
            "data.lon": _metric("data.lon", "中心经度", "用于放置影像中心的经度。", "决定粗定位东西向位置。", "单位为十进制度。", "核对合法范围及 POS 来源。", "经纬度互换会导致严重落区错误。", "用于重建仿射。", unit="度", vis="number"),
            "data.lat": _metric("data.lat", "中心纬度", "用于放置影像中心的纬度。", "决定粗定位南北向位置并参与米/度换算。", "单位为十进制度。", "核对合法范围及 POS 来源。", "经纬度互换会导致严重落区错误。", "用于重建仿射。", unit="度", vis="number"),
            "data.alt_m": _metric("data.alt_m", "飞行高度参数", "用于默认 GSD 公式的高度值。", "影响未显式给定 gsd_m 时的空间尺度。", "实现不区分相对地高与海拔。", "核对高度基准、焦距和像元尺寸。", "把海拔当相对地高会导致 GSD 偏差。", "用于 GSD 复算。", unit="m", vis="number"),
            "data.gsd_m": _metric("data.gsd_m", "地面采样距离", "写入仿射前使用的米/像素尺度。", "决定粗定位输出的空间覆盖范围。", "可由参数直接给出，或按高度×像元尺寸/焦距估算。", "独立复算并与已知目标尺度比较。", "理论 GSD 不等于经正射验证的实际分辨率。", "用于空间范围估算。", unit="m/像素", vis="number"),
            "data.res_deg": _metric("data.res_deg", "角分辨率", "由 GSD 和中心纬度处米/度换算得到的 [经度分辨率, 纬度分辨率]。", "把米制 GSD 转为 EPSG:4326 仿射步长。", "两项通常不同且均为动态计算值。", "从 gsd_m、lat 和 transform 交叉复算。", "不得把两个分量当作统一米制像元大小。", "用于重建 GeoTransform。", unit="度/像素", vis="array"),
            "data.yaw": _metric("data.yaw", "记录的偏航角", "从 POS 中透传的 yaw，可为空。", "保留可能供后续精校正使用的姿态线索。", "当前算法不使用该值旋转影像。", "与 POS 原文核对，并确认 transform 仍为北向上。", "不得因该字段存在就认为输出已航向改正。", "用于后续几何处理参考。", unit="度", vis="number", optional=True),
            "data.crs": _metric("data.crs", "坐标参考系", "粗定位输出固定写入的 EPSG:4326。", "声明经纬度坐标的解释基准。", "值应为 EPSG:4326。", "读取 GeoTIFF CRS 与元数据 JSON 交叉核对。", "固定 CRS 不代表输入 POS 基准已完成转换。", "用于 GIS 数据交换。", vis="text"),
        },
    },
    "16_orthorectify": {
        "summary": _summary(
            "以共线方程、单组姿态和 DEM 将输出格网点反投影到输入影像重采样。",
            "生成与输入同尺寸的单片地形与姿态校正结果。",
            "必须提供 file2 DEM；当前输出沿用输入 profile，模型不是空三加密或控制点约束的测绘级正射。",
        ),
        "outputs": {
            "files.ortho_tif": _output(
                "files.ortho_tif", "单片正射结果",
                description="使用 file2 DEM、单组 RPY 和相机参数执行双线性重采样的 GeoTIFF；缺少 file2 DEM 不会产生有效输出。",
                effect="按简化共线模型补偿地形高程和统一姿态导致的像点位移。",
                business="为单片落图、叠加和后续镶嵌提供几何校正影像。",
                interpretation="输出尺寸与输入相同，边界采用 nearest 模式取值；空间 profile 沿用输入而非新求完整地面包络。",
                check="确认 file2 DEM 有效，比较控制点残差，核对姿态角、焦距、像元尺寸和输出 profile。",
                abnormal=["缺少 file2 DEM 不会产生有效输出", "边缘拉伸或错位提示姿态、DEM 高程基准或模型不适配"],
                downstream="用于单片地图叠加和地理镶嵌前处理。",
                warning="file2 DEM 为必需输入，缺少不会产生有效输出；不得把该单姿态简化模型结果宣称为有控制点检核的测绘级正射。",
                format_name="GeoTIFF", vis="raster_cube",
            ),
            "data.gsd_m": _metric("data.gsd_m", "内部反投影格网尺度", "共线方程内部反投影格网使用的计算尺度；保存结果时沿用输入 profile，不会据此重写 GeoTIFF transform。", "控制内部地面格网坐标与像方采样位置的计算，不决定输出文件的空间参考。", "默认由高度、像元尺寸和焦距计算；该值不是输出像元分辨率，实际输出像元分辨率必须读取 GeoTIFF transform。", "独立复算内部尺度，并从输出 GeoTIFF transform 读取实际像元分辨率，确认输出仍沿用输入 profile。", "不得称为“输出 GSD”或用它代替 GeoTIFF transform；它只控制内部反投影格网/计算尺度，不是输出像元分辨率。", "用于复核内部共线反投影计算，不用于声明输出栅格分辨率。", unit="m/像素", vis="number"),
            "data.focal_px": _metric("data.focal_px", "像素焦距", "焦距除以像元尺寸得到的像素单位焦距。", "把地面方向向量映射到像平面采样位置。", "应为正，且与相机参数一致。", "按 focal_mm/pixel_um 复算。", "毫米与微米混用会造成千倍误差。", "用于共线方程复算。", unit="像素", vis="number"),
            "data.altitude_m": _metric("data.altitude_m", "相机高度参数", "共线模型采用的统一相机高度。", "决定透视投影比例。", "当前全景共用单一高度。", "核对高度基准与 DEM 基准。", "绝对海拔与相对高度混用会造成投影偏差。", "用于几何模型复现。", unit="m", vis="number"),
            "data.roll_deg": _metric("data.roll_deg", "横滚角", "ZYX 旋转矩阵使用的横滚角。", "控制左右倾斜校正。", "全景使用单一角度。", "核对机体系、符号和度单位。", "姿态约定错误会放大错位。", "用于旋转矩阵复算。", unit="度", vis="number"),
            "data.pitch_deg": _metric("data.pitch_deg", "俯仰角", "ZYX 旋转矩阵使用的俯仰角。", "控制前后倾斜校正。", "全景使用单一角度。", "核对机体系、符号和度单位。", "姿态约定错误会放大错位。", "用于旋转矩阵复算。", unit="度", vis="number"),
            "data.yaw_deg": _metric("data.yaw_deg", "偏航角", "ZYX 旋转矩阵使用的偏航角。", "控制地面平面内方向。", "全景使用单一角度。", "核对北向、航向和正方向约定。", "方位基准错误会产生整体旋转。", "用于旋转矩阵复算。", unit="度", vis="number"),
            "data.dem_min": _metric("data.dem_min", "DEM 最小高程", "file2 DEM 重采样到影像尺寸后的最小值。", "给出参与投影的地形高程下界。", "受 NoData 是否被识别影响。", "与 DEM 统计和高程基准核对。", "异常极值可能是 NoData 被当作高程。", "用于 DEM 输入质检。", unit="DEM 高程单位", vis="number"),
            "data.dem_max": _metric("data.dem_max", "DEM 最大高程", "file2 DEM 重采样到影像尺寸后的最大值。", "给出参与投影的地形高程上界。", "应与作业区地形量级一致。", "与 DEM 统计和高程基准核对。", "异常极值会造成局部投影畸变。", "用于 DEM 输入质检。", unit="DEM 高程单位", vis="number"),
        },
    },
    "17_mosaic": {
        "summary": _summary(
            "将两条带按 GeoTransform 重投影到统一网格，并按到边缘距离羽化重叠区。",
            "形成覆盖两景地理范围的连续多波段镶嵌。",
            "必须提供 file2 第二条带且两景必须同 CRS；实现不会正确完成跨 CRS 统一重投影，不同 CRS 时结果无效、不可直接使用；当前仅处理两景并取共同最少波段数。",
        ),
        "outputs": {
            "files.mosaic_tif": _output(
                "files.mosaic_tif", "地理羽化镶嵌",
                description="将 file 与 file2 第二条带在相同 CRS 下按地理变换重投影并羽化的 GeoTIFF；缺少 file2 第二条带不会产生有效输出，且两景必须同 CRS。",
                effect="合并两景覆盖范围，并在重叠区进行距离边缘加权平均。",
                business="生成可供整景分析、制图和交付的合并立方体。",
                interpretation="两景必须同 CRS；分辨率取两景各方向较小像元步长，波段数取两景较少者。不同 CRS 时实现不会正确统一坐标，结果无效、不可直接使用。",
                check="确认 file2 第二条带存在、两景必须同 CRS 且 GeoTransform 有效，再核对范围、分辨率、共同波段及接缝。",
                abnormal=["缺少 file2 第二条带不会产生有效输出", "两景不同 CRS 时范围和网格会被错误混合，结果无效", "重叠区双影表示上游地理参考不准"],
                downstream="用于整景统计、专题分析和可视化。",
                warning="file2 第二条带为必需输入，缺少不会产生有效输出；两景必须同 CRS，不同 CRS 时结果无效、不可直接使用，也不得宣称实现支持跨坐标系镶嵌。",
                format_name="GeoTIFF", vis="raster_cube",
            ),
            "data.n_scenes": _metric("data.n_scenes", "参与景数", "实际传入镶嵌核心的场景数量。", "说明结果合并的数据规模。", "当前服务正常输出时为两景。", "与 file 和 file2 输入及日志核对。", "不要把该字段理解为可由接口动态接收任意多文件。", "用于处理审计。", unit="景", vis="number"),
            "data.bounds": _metric("data.bounds", "镶嵌范围", "两景必须同 CRS 时，统一网格的 [west, south, east, north] 动态边界数组。", "声明输出空间覆盖外包矩形。", "坐标单位由共同 CRS 决定；不同 CRS 时实现会直接混合不可比较的边界数值，结果无效。", "先确认两景必须同 CRS，再与两景 array_bounds 和输出 transform 复算。", "不同 CRS 时 bounds 结果无效、不可直接使用，不能解释为空间覆盖范围。", "用于同 CRS 镶嵌结果的地图缩放和覆盖检查。", unit="共同 CRS 坐标单位", vis="array"),
            "data.resolution": _metric("data.resolution", "镶嵌分辨率", "两景必须同 CRS 时，输出网格 [x, y] 方向动态像元步长绝对值。", "说明同一坐标系内重投影采用的空间采样尺度。", "各方向取输入两景中的较小步长；不同 CRS 的单位不可比较，所得结果无效。", "先确认两景必须同 CRS，再与输出 transform 及输入分辨率核对。", "不同 CRS 时 resolution 结果无效、不可直接使用；更小步长也不等于实际空间分辨能力提高。", "用于同 CRS 栅格后续对齐。", unit="共同 CRS 单位/像素", vis="array"),
        },
    },
    "18_color_balance": {
        "summary": _summary(
            "逐波段应用 Wallis 局部均值与标准差匀光，并生成均波段预览。",
            "减弱缓慢变化的亮度不均，改善镶嵌视觉连续性。",
            "当前不是接缝线搜索或多景颜色传递；局部滤波会改变像元定量值。",
        ),
        "outputs": {
            "files.cube_tif": _output(
                "files.cube_tif", "Wallis 匀光立方体",
                description="逐波段按局部窗口统计调整对比度与亮度的 GeoTIFF。",
                effect="抑制低频照度差异并调整局部对比度。",
                business="改善地图浏览和视觉交付中的亮度均匀性。",
                interpretation="每个波段独立处理，输出已不再保持原始反射率或辐亮度尺度。",
                check="比较处理前后直方图、均匀区、真实边缘和光谱形状，检查过增强与光晕。",
                abnormal=["边缘光晕、噪声放大或光谱比例变化过大表示参数不合适"],
                downstream="用于视觉增强和展示型镶嵌，不宜直接进入定量反演。",
                warning="不得把 Wallis 增强结果当作保持绝对辐射定量关系的校正产品。",
                format_name="GeoTIFF", vis="raster_cube",
                related_outputs=["files.preview_png", "data.window", "data.contrast", "data.brightness"],
            ),
            "files.preview_png": _output(
                "files.preview_png", "Wallis 预览图",
                description="对匀光后全部波段求均值并渲染的 PNG。",
                effect="提供快速目视检查匀光空间效果的缩略表示。",
                business="便于报告和无需 GIS 的质量沟通。",
                interpretation="颜色或灰度仅来自均波段渲染，不保留定量像元值。",
                check="与 cube_tif 的均波段图对照，核对尺寸和主要结构。",
                abnormal=["与定量栅格结构不一致表示渲染或文件关联错误"],
                downstream="用于人工质检和展示。",
                warning="不得从 PNG 反推反射率、波段值或地理坐标。",
                format_name="PNG", vis="image", related_outputs=["files.cube_tif"],
            ),
            "data.window": _metric("data.window", "局部窗口尺寸", "uniform_filter 使用的方形窗口边长。", "控制局部亮度与标准差统计尺度。", "窗口越大越偏向低频匀光。", "结合影像尺寸和目标尺度核对。", "过小会放大纹理噪声，过大会削弱大尺度变化。", "用于复现 Wallis 处理。", unit="像素", vis="number"),
            "data.contrast": _metric("data.contrast", "对比度参数", "Wallis 局部标准差增益中的 contrast 系数。", "调节局部对比增强强度。", "需结合全局和局部标准差解释。", "比较处理前后标准差和噪声。", "不能按普通线性对比度滑块直接解释。", "用于参数追溯。", unit="无量纲", vis="number"),
            "data.brightness": _metric("data.brightness", "亮度参数", "全局均值与局部均值混合中的 brightness 权重。", "调节输出亮度中心对全局均值的依赖。", "值越高越偏向全局均值项。", "复算均值混合并比较输出亮度。", "不能解释为简单加法亮度值。", "用于参数追溯。", unit="无量纲", vis="number"),
        },
    },
    "19_multi_source_register": {
        "summary": _summary(
            "以 HSI 均波段图为参考，对 RGB 均波段图估计相位相关亚像元平移并重采样。",
            "把 RGB 对齐到 HSI 网格，支持目视标注与多源联合分析。",
            "必须提供 file2 RGB；当前只估计全局平移，尺寸不同时先缩放，不处理旋转、透视、CRS 或局部形变。",
        ),
        "outputs": {
            "files.hsi_tif": _output(
                "files.hsi_tif", "HSI 参考立方体",
                description="将 file HSI 原值写出到参考 profile 的 GeoTIFF；缺少 file2 RGB 不会产生有效输出。",
                effect="固定配准参考网格并与 RGB 对齐结果成对交付。",
                business="为光谱分析提供未平移的参考数据层。",
                interpretation="该文件不是经配准变换后的 HSI，而是本次配准使用的参考影像。",
                check="确认 file2 RGB 存在，并与输入 HSI 像元值、形状和 profile 对照。",
                abnormal=["缺少 file2 RGB 不会产生有效输出", "与原 HSI 不一致表示写出或数据类型转换异常"],
                downstream="与 rgb_aligned_tif 联合显示和标注。",
                warning="file2 RGB 为必需输入，缺少不会产生有效输出；不得把参考文件称为已被几何纠正的 HSI。",
                format_name="GeoTIFF", vis="raster_cube",
            ),
            "files.rgb_aligned_tif": _output(
                "files.rgb_aligned_tif", "对齐 RGB 立方体",
                description="将 file2 RGB 缩放到 HSI 尺寸后按 dy、dx 三次插值平移的 GeoTIFF；缺少 file2 RGB 不会产生有效输出。",
                effect="在 HSI 网格上应用全局亚像元平移。",
                business="支持 RGB 目视信息与 HSI 光谱位置联合使用。",
                interpretation="仅校正全局平移；输出沿用 HSI profile，边缘使用 nearest 填充。",
                check="确认 file2 RGB 有效，叠加边缘和控制点，核对平移方向、缩放影响和重采样边界。",
                abnormal=["缺少 file2 RGB 不会产生有效输出", "局部仍错位表示存在旋转、透视或非刚性差异"],
                downstream="用于联合显示、样本标注和多源特征提取。",
                warning="file2 RGB 为必需输入，缺少不会产生有效输出；不得把全局平移配准描述为完整正射、CRS 转换或局部形变校正。",
                format_name="GeoTIFF", vis="raster_rgb", related_outputs=["files.hsi_tif", "data.dy", "data.dx"],
            ),
            "data.dy": _metric("data.dy", "行方向平移", "施加到 RGB 的亚像元行方向 shift。", "量化 RGB 对齐 HSI 所需的垂直平移。", "正负号遵循 scipy.ndimage.shift 的数组轴约定。", "用控制点和反向平移实验核对符号。", "不得直接当作地图北向距离。", "用于配准复现和残差分析。", unit="像素", vis="number"),
            "data.dx": _metric("data.dx", "列方向平移", "施加到 RGB 的亚像元列方向 shift。", "量化 RGB 对齐 HSI 所需的水平平移。", "正负号遵循数组列轴约定。", "用控制点和反向平移实验核对符号。", "不得直接当作地图东向距离。", "用于配准复现和残差分析。", unit="像素", vis="number"),
            "data.peak_response": _metric("data.peak_response", "相位相关峰响应", "归一化互功率谱反变换相关面的主峰值。", "提供本次平移峰显著程度的相对诊断量。", "值受纹理、窗函数和模态差异影响，当前没有通过阈值。", "与相关面次峰和控制点残差联合检查。", "不得把该值当作概率、精度或已通过质量门控。", "用于配准可信度辅助诊断。", unit="相对响应", vis="number"),
        },
    },
    "20_bad_band_remove": {
        "summary": _summary(
            "合并手动索引、场景 mean/std 相对指标和固定大气吸收窗口剔除波段。",
            "减少明显低质量或不适用波段，形成波段数更少的立方体。",
            "自动指标受场景纹理影响，且实现至少保留最高指标的两个波段；波长缺失时使用默认等间隔波长。",
        ),
        "outputs": {
            "files.cube_tif": _output(
                "files.cube_tif", "清洗后波段立方体",
                description="按 kept 动态索引从输入立方体抽取波段的 GeoTIFF。",
                effect="移除手动指定、低相对 SNR 或落入固定吸收窗口的波段。",
                business="降低下游模型维度并避免部分低质量波段干扰。",
                interpretation="输出波段 k 对应原始索引 kept[k]；输出不保留被剔除位置的空槽。",
                check="核对输出波段数等于 len(kept)，逐项验证输出波段 k 与输入 kept[k] 像元一致。",
                abnormal=["波段顺序错位会使波长、模型和指数全部失配"],
                downstream="用于光谱平滑、降维、分类和反演。",
                warning="不得按输出 k 直接查原始波长；必须通过 kept[k] 映射，且场景 mean/std 指标不能替代实验室传感器 SNR。",
                format_name="GeoTIFF", vis="raster_cube",
                related_outputs=["data.dropped", "data.kept", "data.wavelength_nm", "data.snr_per_band"],
            ),
            "data.input_bands": _metric("data.input_bands", "输入波段数", "剔除前立方体的实际波段数。", "提供 dropped、kept 和动态数组的索引上界。", "应等于原始 cube 第三维长度。", "与输入栅格 band count 核对。", "不得当作清洗后波段数。", "用于完整性检查。", unit="波段", vis="number"),
            "data.dropped": _metric("data.dropped", "剔除索引", "按升序给出被移除的动态原始波段索引数组。", "说明哪些原始特征未进入输出。", "索引基于输入波段且不假定固定长度。", "检查索引唯一、合法，并与 kept 构成完整分区。", "不得把索引值当作波长 nm。", "用于波长映射和处理审计。", range_text="动态长度：由本次检测与手动配置决定", vis="array"),
            "data.kept": _metric("data.kept", "保留索引", "按原始波段顺序给出输出所采用的动态索引数组。", "建立清洗后波段与原始光谱轴的映射。", "输出波段 k 对应 kept[k]，长度等于输出波段数。", "逐项对照输入与输出像元，检查与 dropped 互斥且并集完整。", "不得假定 kept 连续或长度固定。", "用于同步波长、模型特征和后续解释。", range_text="动态长度：等于本次输出波段数", vis="array"),
            "data.snr_per_band": _metric("data.snr_per_band", "逐波段场景相对指标", "按原始波段顺序计算的动态 mean/std 数组。", "为低指标剔除提供场景内比较依据。", "第 i 项对应输入第 i 波段，受场景纹理和地物组成影响。", "核对动态长度等于 input_bands，并查看完整曲线。", "不能当作实验室传感器 SNR 或单独判定坏波段。", "用于解释自动剔除来源。", unit="比值", range_text="动态长度：每个输入波段一项", vis="spectrum"),
            "data.wavelength_nm": _metric("data.wavelength_nm", "检测波长数组", "输出 data 键 wavelength_nm 记录吸收窗口判断所用的动态波长数组；配置来源是输入参数 wavelengths_nm。", "把固定吸收区间映射到原始波段索引。", "输入参数 wavelengths_nm 未提供时实现生成与 input_bands 等长的默认数组；用户提供时，长度等于 input_bands 是有效输入前提，服务不校验该长度。", "先核对用户输入 wavelengths_nm 长度等于 input_bands，再核对第 i 项与输入第 i 波段及输出 data 键 wavelength_nm 一致。", "服务不校验用户波长数组长度：过短会造成波长—波段错配和吸收窗口漏判，过长可产生越界 dropped 索引；不得无条件断言输出数组长度正确。", "用于有效输入前提满足时解释 dropped 和同步输出波长。", unit="nm", range_text="动态长度：用户输入时原样返回；有效输入应每个输入波段一项", vis="spectrum"),
            "data.snr_ratio": _metric("data.snr_ratio", "低指标比例阈值", "以逐波段指标中位数为基准的剔除比例。", "控制低于 snr_ratio×中位数的候选波段。", "仅用于场景相对指标分支。", "用 snr_per_band 中位数复算低值索引。", "不得把比例阈值解释为绝对 SNR 标准。", "用于参数追溯和敏感性分析。", unit="比例", vis="number"),
        },
    },
    "21_savgol_smooth": {
        "summary": _summary(
            "沿每个像元的波段轴执行 Savitzky–Golay 平滑。",
            "降低高频光谱起伏，同时尽量保留局部谱形。",
            "偶数窗口会自动加一；当前仅平滑，不实现包络线去除，且波段轴应具有合理的连续顺序。",
        ),
        "outputs": {
            "files.cube_tif": _output(
                "files.cube_tif", "SG 平滑立方体",
                description="沿第三维使用 nearest 边界模式执行 Savitzky–Golay 滤波的 GeoTIFF。",
                effect="在每个像元光谱上以局部多项式抑制高频变化。",
                business="改善光谱匹配、特征提取和模型输入稳定性。",
                interpretation="空间维不参与平滑，波段数量与顺序不变；边缘谱段受 nearest 模式影响。",
                check="比较处理前后代表性光谱、吸收峰位置与深度，核对窗口和多项式阶数。",
                abnormal=["窄吸收峰消失或出现振荡表示窗口或阶数不合适"],
                downstream="用于降维、光谱匹配和分类前处理。",
                warning="不得把 SG 平滑描述成包络线去除、坏波段修复或空间去噪。",
                format_name="GeoTIFF", vis="raster_cube",
            ),
            "data.window_length": _metric("data.window_length", "实际窗口长度", "滤波实际采用的波段窗口长度；输入偶数时实现加一。", "决定局部拟合跨越的谱段数量。", "应为奇数且不大于实际波段数。", "与请求参数和输出响应核对。", "窗口过大会抹平窄特征。", "用于处理复现。", unit="波段", vis="number"),
            "data.polyorder": _metric("data.polyorder", "多项式阶数", "Savitzky–Golay 局部拟合使用的多项式阶数。", "控制局部谱形拟合自由度。", "应小于 window_length。", "核对 scipy 滤波参数约束和输出曲线。", "阶数过高可能产生振荡，过低可能损失形状。", "用于处理复现。", unit="阶", vis="number"),
        },
    },
    "22_normalize": {
        "summary": _summary(
            "按配置执行逐波段全景 minmax/zscore，或逐像元光谱 SNV/L2 归一。",
            "统一特征尺度，减少量纲和整体幅值对模型的影响。",
            "不同 method 的归一轴和物理含义不同；未知方法会回落为 snv，输出通常不再保持反射率单位。",
        ),
        "outputs": {
            "files.cube_tif": _output(
                "files.cube_tif", "归一化立方体",
                description="按 method 执行 minmax、zscore、snv 或 l2 后写出的 GeoTIFF。",
                effect="调整逐波段全景分布或逐像元光谱尺度。",
                business="为机器学习、光谱角和跨特征联合建模提供数值预处理。",
                interpretation="minmax/zscore 按空间维逐波段计算；snv/l2 按光谱维逐像元计算，四者不可互换。",
                check="按返回 method 和对应轴复算抽样像元或波段，检查常量数据的 epsilon 处理。",
                abnormal=["按错误轴复算不一致表示方法语义被误解或实现异常"],
                downstream="用于模型训练、推理和特征比较。",
                warning="不得跨 method 直接比较 mean/std，也不得把归一化值继续解释为原物理量。",
                format_name="GeoTIFF", vis="raster_cube",
            ),
            "data.method": _metric("data.method", "实际归一方法", "实际执行的 minmax、zscore、snv 或 l2 标识。", "决定归一轴、目标统计和结果解释。", "未知请求值会被实现改为 snv。", "与请求参数、抽样复算和响应消息核对。", "不得只看请求值而忽略实际返回方法。", "用于模型流水线追溯。", vis="text"),
            "data.mean": _metric("data.mean", "输出全局均值", "归一化后全部像元与波段的总体均值。", "提供结果数值中心的快速诊断。", "其期望值取决于 method 和数据组成，不是所有方法都必为零。", "从输出 GeoTIFF 全量复算。", "不得用全局均值代替按正确轴的归一化检验。", "用于运行级质量快检。", unit="归一化值", vis="number"),
            "data.std": _metric("data.std", "输出全局标准差", "归一化后全部像元与波段的总体标准差。", "提供结果离散程度的快速诊断。", "其期望值取决于 method，不是所有方法都必为一。", "从输出 GeoTIFF 全量复算。", "不得用全局标准差断言每波段或每像元都满足同一目标。", "用于运行级质量快检。", unit="归一化值", vis="number"),
        },
    },
    "23_pca": {
        "summary": _summary(
            "执行标准化 PCA，或先按空间列差分估计噪声并白化后执行 MNF。",
            "把高维光谱压缩为按特征值排序的低维成分。",
            "MNF 噪声模型仅基于相邻列差分；explained_variance_ratio 只在保留成分内归一，不是相对全部原始成分的累计贡献率。",
        ),
        "outputs": {
            "files.pca_tif": _output(
                "files.pca_tif", "PCA/MNF 成分立方体",
                description="输出 K 个线性变换成分的 GeoTIFF；波段顺序为按特征值降序的第 1..K 主成分。",
                effect="将相关原始波段投影到方差或噪声白化后方差最大的正交方向。",
                business="降低模型输入维度和冗余，支持可视化及特征工程。",
                interpretation="输出波段不对应单个原始波长，符号可整体翻转；PCA 与 MNF 的成分空间不同。",
                check="核对输出波段数、特征值降序、正交性和重跑稳定性，并分别按 method 复算。",
                abnormal=["特征值未降序或 K 与输出波段数不一致表示排序或写出错误"],
                downstream="用于低维建模、成分可视化和噪声筛选。",
                warning="不得把第 1..K 主成分当作原始波段，也不得把当前 MNF 描述成使用传感器实测噪声协方差。",
                format_name="GeoTIFF", vis="raster_cube",
                related_outputs=["data.method", "data.eigenvalues", "data.explained_variance_ratio", "data.n_components"],
            ),
            "data.method": _metric("data.method", "实际降维方法", "标识本次实际执行 PCA 或 MNF。", "决定预标准化和噪声白化步骤。", "非 pca 请求会执行 mnf。", "与参数、文件名和特征统计核对。", "不得只凭文件键 pca_tif 判断实际一定是 PCA。", "用于模型与结果追溯。", vis="text"),
            "data.eigenvalues": _metric("data.eigenvalues", "保留成分特征值", "按降序给出本次 K 个输出成分的动态特征值数组。", "量化各输出方向在对应变换空间中的方差。", "第 j 项对应输出第 j+1 主成分，不固化 K。", "检查动态长度等于 n_components 且非递增、非负。", "PCA 与 MNF 特征值不能脱离方法直接比较。", "用于成分筛选和降维诊断。", range_text="动态长度：等于实际保留成分数 K", vis="array"),
            "data.explained_variance_ratio": _metric("data.explained_variance_ratio", "保留成分内方差比例", "各保留特征值除以保留特征值总和得到的动态数组。", "描述 K 个已保留成分之间的相对方差分配。", "数组和约为 1，但不表示 K 成分占全部原始维度总方差的比例。", "由 eigenvalues 复算并核对动态长度。", "不得据此直接声称保留了相对于全部原始成分的某百分比信息。", "用于保留成分内部排序解释。", unit="比例", range_text="动态长度：等于实际保留成分数 K", vis="array"),
            "data.n_components": _metric("data.n_components", "实际成分数", "经输入波段数和像元数约束后的实际输出 K。", "说明降维产品的特征维度。", "至少 1，且不超过输入波段数和像元数。", "与 pca_tif 波段数及两个动态数组长度核对。", "不得假定总是等于请求值。", "用于配置下游模型输入维度。", unit="成分", vis="number"),
        },
    },
    "24_band_select": {
        "summary": _summary(
            "无有效标签时按全景方差，有有效多类标签时按 ANOVA F 值选择最高分波段。",
            "保留与当前无监督变化或监督类别区分最相关的原始波段子集。",
            "标签分支要求尺寸匹配、正标签像元不少于 8 且至少两类；否则静默使用方差，selected 顺序按得分降序而非原波段顺序。",
        ),
        "outputs": {
            "files.cube_tif": _output(
                "files.cube_tif", "优选波段立方体",
                description="按得分降序从输入抽取 K 个原始波段的 GeoTIFF。",
                effect="将输入压缩为本次排名最高的波段子集。",
                business="减少采集或建模维度并保留当前任务的高分特征。",
                interpretation="输出波段 j 对应 selected[j]；输出顺序是得分排名顺序，不保证按原波长递增。",
                check="逐项验证输出波段 j 与输入 selected[j] 完全一致，并核对实际 method。",
                abnormal=["忽略 selected 映射会导致波长和模型特征错配"],
                downstream="用于轻量化分类、特征工程和传感器波段设计初筛。",
                warning="不得按输出 j 直接套原始第 j 波长，也不得把单景方差或当前标签 ANOVA 排名当作跨场景稳定因果重要性。",
                format_name="GeoTIFF", vis="raster_cube",
                related_outputs=["files.ranking_json", "data.method", "data.selected", "data.scores"],
            ),
            "files.ranking_json": _output(
                "files.ranking_json", "完整波段排名数据",
                description="记录 method、全部原始波段 scores、selected 和 K 的 JSON。",
                effect="保留完整评分向量及最终选择，便于审计和复现。",
                business="支持重新选择 K、绘制排名和比较不同标签方案。",
                interpretation="JSON 中 scores 按原始波段索引排列；接口 data.scores 只返回 selected 对应得分。",
                check="核对完整 scores 动态长度等于输入波段数，selected 与接口 data 一致。",
                abnormal=["把完整 scores 与接口筛选后 scores 混为一谈会造成索引错位"],
                downstream="用于排名审计、波段曲线和参数复现。",
                warning="不得根据数组位置混淆原始波段得分与选中顺序。",
                format_name="JSON", vis="json_table",
            ),
            "data.method": _metric("data.method", "实际评分方法", "实际使用 variance 或 anova_f。", "说明排名是否利用了有效标签。", "提供 file2 不保证使用 ANOVA，标签须满足尺寸、样本数和类别条件。", "与标签尺寸、正样本数和类别数核对。", "不得因上传标签就宣称结果为监督选择。", "用于选择流程追溯。", vis="text"),
            "data.selected": _metric("data.selected", "选中原始索引", "按得分降序给出的动态原始波段索引数组。", "建立优选输出与原始光谱轴的映射。", "输出波段 j 对应 selected[j]，长度为实际 K。", "检查唯一性、合法范围及与输出像元逐项一致。", "不得假定 selected 按数值升序或长度固定。", "用于同步波长和模型特征。", range_text="动态长度：等于实际选择波段数 K", vis="array"),
            "data.scores": _metric("data.scores", "选中波段得分", "按 selected 顺序返回的动态方差或 ANOVA F 值数组。", "量化本次入选波段的排名依据。", "第 j 项是原始波段 selected[j] 的得分。", "与 ranking_json 完整 scores 按 selected 索引交叉核对。", "不同 method 的分数尺度不可直接比较。", "用于入选依据解释和阈值分析。", range_text="动态长度：等于实际选择波段数 K", vis="array"),
        },
    },
    "25_superpixel": {
        "summary": _summary(
            "在输入前三个波段（不足时补齐通道）上执行 SLIC 超像素分割。",
            "把像元组织为空间连续的小对象，便于对象级统计和分类。",
            "当前没有计算 PCA，尽管服务说明提到主成分；实际直接使用前三波段。标签是对象编号，不是语义类别。",
        ),
        "outputs": {
            "files.labels_tif": _output(
                "files.labels_tif", "SLIC 对象标签图",
                description="与输入空间网格一致、标签从 1 开始的单波段对象编号 GeoTIFF。",
                effect="将相邻且在前三通道上相似的像元聚合为超像素对象。",
                business="支持对象级特征统计、分类和椒盐噪声抑制。",
                interpretation="数值只是对象编号，从 1 开始；编号大小、相邻差值和出现顺序没有类别或相似度含义。",
                check="核对最小标签为 1、唯一值数等于 n_unique，并叠加原图检查边界贴合。",
                abnormal=["大量碎片或跨越明显边界表示 n_segments、compactness 或输入尺度不合适"],
                downstream="用于对象级汇总、图结构构建和分类后处理。",
                warning="不得把对象编号当作语义类别、连续数值或对象大小；当前实际使用前三波段而非自动 PCA。",
                format_name="GeoTIFF", vis="raster_classes",
                related_outputs=["files.preview_png", "data.n_unique"],
            ),
            "files.preview_png": _output(
                "files.preview_png", "超像素预览图",
                description="将对象编号渲染为颜色或灰度的 PNG 预览。",
                effect="快速展示超像素边界和对象分布。",
                business="便于无需 GIS 的参数目视质检。",
                interpretation="颜色不代表类别大小、对象面积或相似度，仅用于区分编号。",
                check="与 labels_tif 边界位置核对，确认尺寸和对象分区一致。",
                abnormal=["预览颜色相近不表示对象属于同类，边界不一致才是渲染异常"],
                downstream="用于人工检查和报告展示。",
                warning="颜色不代表类别大小；不得从 PNG 颜色反推对象编号、面积或定量类别。",
                format_name="PNG", vis="image", related_outputs=["files.labels_tif"],
            ),
            "data.n_segments": _metric("data.n_segments", "请求对象数", "用户请求的目标超像素数量参数。", "控制 SLIC 分割粒度目标。", "实现至少向 SLIC 传入 2，但实际对象数可能不同。", "与请求参数和 n_unique 比较。", "不得把请求值当实际生成对象数。", "用于参数追溯。", unit="对象", vis="number"),
            "data.compactness": _metric("data.compactness", "紧致度参数", "SLIC 平衡空间距离与通道差异的 compactness。", "控制超像素形状规则性与光谱边界贴合。", "更大通常更强调空间紧致，但效果受输入尺度影响。", "在代表区域比较不同参数的边界贴合。", "跨未归一化数据直接比较参数意义有限。", "用于分割调参。", unit="无量纲", vis="number"),
            "data.n_unique": _metric("data.n_unique", "实际对象数", "labels_tif 中唯一对象编号的动态计数。", "给出本次真正生成的对象规模。", "通常接近但不保证等于 n_segments。", "从标签唯一值复算，并确认标签从 1 开始。", "不得将对象数解释为语义类别数。", "用于对象级任务规模估算。", unit="对象", vis="number"),
        },
    },
    "26_patch_build": {
        "summary": _summary(
            "以每个正标签像元为中心，边缘复制填充并切取奇数尺寸谱空邻域。",
            "生成可直接供 CNN/Transformer 训练或评估使用的样本张量、标签和坐标。",
            "必须提供 file2 标签图；0 和负标签被忽略，不做抽样、类别平衡、数据划分或增强。",
        ),
        "outputs": {
            "files.patches_npz": _output(
                "files.patches_npz", "Patch 样本 NPZ",
                description="包含 patches、labels、coords 三个数组的压缩 NPZ；缺少 file2 标签不会产生有效输出。",
                effect="把每个正标签中心组织为谱空邻域、类别及原图行列坐标。",
                business="为监督学习提供可追溯到原图位置的样本集合。",
                interpretation="patches 形状为 (N,W,W,B)，末维保持输入波段顺序；labels 为中心像元标签，coords 为 [row,col]。",
                check="确认 file2 标签存在，核对三个成员、首维 N、patch 尺寸、坐标回查和末维逐波段像元值。",
                abnormal=["缺少 file2 标签不会产生有效输出", "成员首维不一致或 coords 回查标签不一致表示样本构建错误"],
                downstream="用于谱空模型训练、验证和样本审计。",
                warning="file2 标签为必需输入，缺少不会产生有效输出；不得打乱末维输入波段顺序，也不得把全部样本视为已完成独立训练/测试划分。",
                format_name="NPZ", vis="none",
                related_outputs=["files.manifest_json", "files.preview_png", "data.n", "data.classes"],
            ),
            "files.manifest_json": _output(
                "files.manifest_json", "Patch 清单",
                description="记录 N、patch_size、输入 bands、完整 shape 和动态 classes 的 JSON；缺少 file2 标签不会产生有效输出。",
                effect="提供无需加载大数组即可检查的数据集结构摘要。",
                business="支持模型配置、数据版本审计和批次兼容性检查。",
                interpretation="classes 仅包含实际进入样本的正标签唯一值；不重编码为连续类别。",
                check="确认 file2 标签存在，并与 NPZ 三个成员和标签唯一值复算。",
                abnormal=["缺少 file2 标签不会产生有效输出", "shape、N、bands 或 classes 与 NPZ 不一致表示清单失配"],
                downstream="用于训练配置和数据登记。",
                warning="file2 标签为必需输入，缺少不会产生有效输出；不得假定 classes 连续、从 0 开始或长度固定。",
                format_name="JSON", vis="json_table",
            ),
            "files.preview_png": _output(
                "files.preview_png", "平均 Patch 预览",
                description="对 patches 的样本维和波段维求均值后得到的 W×W PNG；缺少 file2 标签不会产生有效输出。",
                effect="展示全部样本平均邻域的空间强度结构。",
                business="用于快速发现中心偏移、边缘填充或整体亮度异常。",
                interpretation="不展示单个样本、类别差异或光谱维，不能代表训练数据分布全貌。",
                check="确认 file2 标签存在，并从 NPZ 按 axis=(0,3) 复算均值图。",
                abnormal=["缺少 file2 标签不会产生有效输出", "与复算均值结构不一致表示预览关联错误"],
                downstream="用于样本构建人工快检。",
                warning="file2 标签为必需输入，缺少不会产生有效输出；不得从 PNG 恢复 patches、labels、coords 或类别统计。",
                format_name="PNG", vis="image", related_outputs=["files.patches_npz"],
            ),
            "data.n": _metric("data.n", "样本数", "正标签像元产生的 Patch 数量 N。", "量化可用于监督学习的样本规模。", "每个 label>0 像元恰好产生一个样本。", "统计 labels 长度并与正标签像元数核对。", "空间邻近样本高度相关，数量大不等于独立信息多。", "用于批次规模和训练步数配置。", unit="样本", vis="number"),
            "data.patch_size": _metric("data.patch_size", "Patch 边长", "实际使用的正奇数空间窗口边长 W。", "决定每个样本的空间上下文范围。", "patches 两个空间维均为 W。", "与 NPZ shape 和请求参数核对。", "不得把边长当半径；偶数或非正值不会产生输出。", "用于模型输入配置。", unit="像素", vis="number"),
            "data.bands": _metric("data.bands", "输入波段数", "patches 末维 B 的实际长度。", "声明模型接收的光谱特征维度。", "末维保持输入波段顺序，不固化长度。", "与输入立方体和 NPZ 末维逐项核对。", "不得在未同步波长和模型权重时改变顺序。", "用于模型通道配置。", unit="波段", vis="number"),
            "data.classes": _metric("data.classes", "样本类别值", "按数值升序列出 labels 中实际出现的动态正标签数组。", "说明本批样本覆盖哪些原始类别编码。", "保留 file2 标签原值，不保证连续或从 0 开始。", "与 NPZ labels 唯一值复算。", "不得把数组位置当类别编码，也不得固化类别数量。", "用于类别映射和覆盖检查。", range_text="动态长度：由本次正标签唯一值决定", vis="array"),
        },
    },
}
